/**
 * @file lwip_geth_private_phy_dp83825i.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip_geth_conf.h"
#if (PHY_DEVICE_NAME == PHY_DP83825I)
#include "lwip_geth_private_phy_dp83825i.h"

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
#define IFXGETH_PHY_DP83825I_MDIO_BMCR          0x00
#define IFXGETH_PHY_DP83825I_MDIO_BMSR          0x01
#define IFXGETH_PHY_DP83825I_MDIO_PHYIDR1       0x02
#define IFXGETH_PHY_DP83825I_MDIO_PHYIDR2       0x03
#define IFXGETH_PHY_DP83825I_MDIO_ANAR          0x04
#define IFXGETH_PHY_DP83825I_MDIO_ALNPAR        0x05
#define IFXGETH_PHY_DP83825I_MDIO_ANER          0x06
#define IFXGETH_PHY_DP83825I_MDIO_PHYSTS        0x10
#define IFXGETH_PHY_DP83825I_MDIO_WAIT_POLLS    100000u
#define IFXGETH_PHY_DP83825I_RESET_POLLS        2000u

/***********************************************************************************************************************
 * PRIVATE DATA
 **********************************************************************************************************************/
static uint32 IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 0;
volatile uint32 IfxGeth_Eth_Phy_Dp83825i_mdioTimeoutCnt;
volatile uint32 IfxGeth_Eth_Phy_Dp83825i_resetTimeoutCnt;

/***********************************************************************************************************************
 * FUNCTION IMPLEMENTATIONS
 **********************************************************************************************************************/
static uint32 lwip_geth_private_Phy_Dp83825i_wait_mdio_ready(void)
{
  uint32 timeout = IFXGETH_PHY_DP83825I_MDIO_WAIT_POLLS;

  while ((GETH_MAC_MDIO_ADDRESS.B.GB != 0u) && (timeout > 0u))
  {
    timeout--;
  }

  if (timeout == 0u)
  {
    IfxGeth_Eth_Phy_Dp83825i_mdioTimeoutCnt++;
    return 0u;
  }

  return 1u;
}

void lwip_geth_private_Phy_Dp83825i_reset(void)
{
  /*
   * reset PHY
   * first we test to readout the reset bit to avoid timing issues (phy not yet ready)
   */
  uint32 value;
  uint32 uiTimeout = IFXGETH_PHY_DP83825I_RESET_POLLS;
  do
  {
    lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0u, IFXGETH_PHY_DP83825I_MDIO_BMCR, &value);
  } while ((value & 0x8000) && (uiTimeout--));      /* wait for reset to finish */

  if (uiTimeout != 0xFFFFFFFFu)
  {
    lwip_geth_private_Phy_Dp83825i_write_mdio_reg(0u, IFXGETH_PHY_DP83825I_MDIO_BMCR, 0x8000u);

    uiTimeout = IFXGETH_PHY_DP83825I_RESET_POLLS;
    do
    {
      lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0u, IFXGETH_PHY_DP83825I_MDIO_BMCR, &value);
    } while ((value & 0x8000u) && (uiTimeout--));                       /* wait for reset to finish */

    if (uiTimeout == 0xFFFFFFFFu)
    {
      IfxGeth_Eth_Phy_Dp83825i_resetTimeoutCnt++;
      return;
    }

    /* get ID */
    lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0u, IFXGETH_PHY_DP83825I_MDIO_PHYIDR1, &value);
    lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0u, IFXGETH_PHY_DP83825I_MDIO_PHYIDR2, &value);
  }
  else
  {
    IfxGeth_Eth_Phy_Dp83825i_resetTimeoutCnt++;
  }
}

uint32 lwip_geth_private_Phy_Dp83825i_init(void)
{
  uint32 value;
  uint32 uiTimeout = IFXGETH_PHY_DP83825I_RESET_POLLS;

  /* reset PHY */
  lwip_geth_private_Phy_Dp83825i_write_mdio_reg(0, IFXGETH_PHY_DP83825I_MDIO_BMCR, 0x8000);

  do
  {
    lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0, IFXGETH_PHY_DP83825I_MDIO_BMCR, &value);
  } while ((value & 0x8000u) && (uiTimeout--));                         /* wait for reset to finish */

  if (uiTimeout == 0xFFFFFFFFu)
  {
    IfxGeth_Eth_Phy_Dp83825i_resetTimeoutCnt++;
    IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 0;
    return 0u;
  }

  /* Start Phy activity: enable auto-negotiation, restart auto-negotiation */
  lwip_geth_private_Phy_Dp83825i_write_mdio_reg(0, IFXGETH_PHY_DP83825I_MDIO_BMCR, 0x1200);

  /* done */
  IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 1;

  return 1;
}

uint32 lwip_geth_private_Phy_Dp83825i_link_status(void)
{
  Ifx_GETH_MAC_PHYIF_CONTROL_STATUS link_status;
  uint32 value;
  link_status.U = 0;

  if (IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone)
  {
    /* We read the phy status register */
    lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0, IFXGETH_PHY_DP83825I_MDIO_PHYSTS, &value);
    if (!(value & 0x2))
    {
      link_status.B.LNKSPEED = 1;
    }
    if (value & 0x4)
    {
      link_status.B.LNKMOD = 1;
    }
    lwip_geth_private_Phy_Dp83825i_read_mdio_reg(0, IFXGETH_PHY_DP83825I_MDIO_BMSR, &value);
    if (value & 0x4) link_status.B.LNKSTS = 1;
  }

  return link_status.U;
}

void lwip_geth_private_Phy_Dp83825i_read_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 *pdata)
{
  if (pdata == 0)
  {
    return;
  }

  if (lwip_geth_private_Phy_Dp83825i_wait_mdio_ready() == 0u)
  {
    *pdata = 0x8000u;
    return;
  }

  /* 5bit Physical Layer Adddress, 5bit GMII Regnr, 4bit csrclock divider, Read, Busy */
  GETH_MAC_MDIO_ADDRESS.U = (layeraddr << 21) | (regaddr << 16) | (0 << 8) | (3 << 2) | (1 << 0);

  if (lwip_geth_private_Phy_Dp83825i_wait_mdio_ready() == 0u)
  {
    *pdata = 0x8000u;
    return;
  }

  /* get data */
  *pdata = GETH_MAC_MDIO_DATA.U;
}


void lwip_geth_private_Phy_Dp83825i_write_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 data)
{
  if (lwip_geth_private_Phy_Dp83825i_wait_mdio_ready() == 0u)
  {
    return;
  }

  /* put data */
  GETH_MAC_MDIO_DATA.U = data;

  /* 5bit Physical Layer Adddress, 5bit GMII Regnr, 4bit csrclock divider, Write, Busy */
  GETH_MAC_MDIO_ADDRESS.U = (layeraddr << 21) | (regaddr << 16) | (0 << 8) |  (1 << 2) | (1 << 0);

  (void)lwip_geth_private_Phy_Dp83825i_wait_mdio_ready();
}

#endif /* (PHY_DEVICE_NAME == PHY_DP83825I) */
/* CODE_BLOCK_END */
