/**
 * @file lwip_geth.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */

#ifndef LWIP_GETH_H_
#define LWIP_GETH_H_

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "IfxGeth_Eth.h"
#include "lwip_geth_lwip.h"
#include "timer_stm.h"
/***********************************************************************************************************************
 * enumS
 **********************************************************************************************************************/
/**
 * @ingroup LWIP_GETH_enumerations
 * @{
 */
/**
 * @brief enum to describe the possible status values, returned by LWIP_GETH APIs.
 */
typedef enum LWIP_GETH_STATUS
{
  LWIP_GETH_STATUS_SUCCESS = 0U,                            /**< Indicates App initialization state successful */
  LWIP_GETH_STATUS_FAILURE                                  /**< Unknown error */

} LWIP_GETH_STATUS_t;
/**
 * @}
 */

/***********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/
/**
 * @ingroup LWIP_GETH_datastructures
 * @{
 */
/**
 * @brief Structure for holding the configuration parameters of the GETH module.
 */
typedef struct LWIP_GETH_CONF
{
  const IfxGeth_Eth_Config * const  geth_lld_config;        /**< Module configuration from the GUI */
  const char*  hostname;                                    /**< Fetch the Hostname for the stack */
  uint16 mtu;                                               /**< Maximum data in one frame */

} LWIP_GETH_CONF_t;

/**
 * @brief Handler structure with pointers to static parameters.
 */
typedef struct LWIP_GETH
{
  const LWIP_GETH_CONF_t * const    app_config;             /**< LWIP_GETH_CONFIG configuration structure pointer */
  IfxGeth_Eth * const               geth_module;            /**< GETH module handle */
#if NO_SYS
  TIMER_STM_t * const               stm_module;             /**< STM module handle */
#endif
#if LWIP_GETH_DEBUG_ENABLED
  PRINTF_ASCLIN_t * const           printf_asclin_app;      /**< ASCLIN module handle */
#endif
  boolean                           app_is_initialized;     /**< APP initialization status */

} LWIP_GETH_t;

/**
 * @}
 */

/***********************************************************************************************************************
 * API Prototypes
 **********************************************************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @ingroup LWIP_GETH_apidoc
 * @{
 */

/**
 * @brief Get the LWIP_GETH APP version.
 * @return ACS_APP_VERSION_t APP version information (major, minor and patch number)
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 *
 * #include "DAVE.h"
 *
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 *
 * void core0_main(void)
 * {
 *   ACS_APP_VERSION_t app_version;
 *   IfxCpu_enableInterrupts();
 *
 *   // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
 *   // Enable the watchdogs and service them periodically if it is required
 *
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *
 *   // Wait for CPU sync event
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 *
 *   // Initialization of DAVE APPs
 *   DAVE_STATUS_t status = DAVE_Init();
 *
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     // Placeholder for error handler code. The while loop below can be replaced with an user error handler.
 *     while (1U) {
 *     }
 *   }
 *   app_version = LWIP_GETH_GetAppVersion();
 *   if ((app_version.major == 1) && (app_version.minor == 0) && (app_version.patch == 2))
 *   {
 *     // version of APP met
 *   }
 *
 *   while(1);
 * }
 * @endcode
 */

/**
 * @brief Function to initialize the GETH module and LWIP stack along with TIMER_STM as per the configuration made
 * in GUI.
 * @param handle Pointer to static content of APP configuration.
 * @return LWIP_GETH_STATUS_t: Status of the LWIP_GETH module initialization.\n
 *  @ref LWIP_GETH_STATUS_SUCCESS - on successful initialization.\n
 *  @ref LWIP_GETH_STATUS_FAILURE - if initialization fails.\n
 *
 * \par<b>Description</b><br>
 * This function configures GETH registers and LWIP stack based on the settings provided in the GUI.
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 * #include "DAVE.h"
 *
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 *
 * void core0_main(void)
 * {
 *   // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
 *   // Enable the watchdogs and service them periodically if it is required
 *
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *
 *   // Wait for CPU sync event
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 *
 *   // Initialization of APP
 *   LWIP_GETH_STATUS_t status = LWIP_GETH_Init(&LWIP_GETH_0);
 *   if (status != LWIP_GETH_STATUS_SUCCESS) {
 *     while (1) {
 *       // Implement your code to handle the error here!
 *     }
 *   }
 *
 *   while (1);
 * }
 * @endcode
 * @note Normally this will be called automatically from DAVE_Init() that are located in corresponding main function.
 */
LWIP_GETH_STATUS_t LWIP_GETH_Init(LWIP_GETH_t *handle);

/**
 * @brief Timer interrupt callback.
 * @return None.\n
 *
 * \par<b>Description</b><br>
 * Every user defined us LwIP timers are increased for all the enabled protocols (ARP, TCP, DHCP, LINK).
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 *
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 *
 * void core0_main(void)
 * {
 *   // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
 *   // Enable the watchdogs and service them periodically if it is required
 *
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *
 *   // Wait for CPU sync event
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 *
 *   // Initialization of DAVE APPs
 *   DAVE_STATUS_t status = DAVE_Init();
 *
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     // Placeholder for error handler code. The while loop below can be replaced with an user error handler.
 *     while (1U) {
 *     }
 *   }
 *   while(1);
 * }
 * // Inside interrupt definition call the lwip_geth_Lwip_onTimerTick() to update LwIP Stack.
 * void updateLwIPStackISR(void)
 * {
 *    // Configure STM to generate an interrupt in 1 ms
 *    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, 100000);
 *    g_TickCount_1ms++;
 *    lwip_geth_Lwip_onTimerTick();
 * }
 * @endcode
 * @note Normally this will be called automatically from DAVE_Init() that are located in corresponding main function.
 */
void lwip_geth_Lwip_onTimerTick(void);

/**
 * @brief  Polling the timer event flags.
 * @return None.\n
 *
 * \par<b>Description</b><br>
 * Poll LwIP timers and trigger protocols execution.
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 *
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 *
 * void core0_main(void)
 * {
 *   // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
 *   // Enable the watchdogs and service them periodically if it is required
 *
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *
 *   // Wait for CPU sync event
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 *
 *   // Initialization of DAVE APPs
 *   DAVE_STATUS_t status = DAVE_Init();
 *
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     // Placeholder for error handler code. The while loop below can be replaced with an user error handler.
 *     while (1U) {
 *     }
 *   }
 *   while(1)
 *   {
 *     lwip_geth_Lwip_pollTimerFlags();
 *   }
 * }
 * @endcode
 * @note Normally this will be called automatically from DAVE_Init() that are located in corresponding main function.
 */
void lwip_geth_Lwip_pollTimerFlags(void);

/**
 * @brief  Polling the GETH receive event flags.
 * @return None.\n
 *
 * \par<b>Description</b><br>
 * Receive data package through GETH.
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 *
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 *
 * void core0_main(void)
 * {
 *   // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
 *   // Enable the watchdogs and service them periodically if it is required
 *
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *
 *   // Wait for CPU sync event
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 *
 *   // Initialization of DAVE APPs
 *   DAVE_STATUS_t status = DAVE_Init();
 *
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     // Placeholder for error handler code. The while loop below can be replaced with an user error handler.
 *     while (1U) {
 *     }
 *   }
 *   while(1)
 *   {
 *     lwip_geth_Lwip_pollReceiveFlags();
 *   }
 * }
 * @endcode
 * @note Normally this will be called automatically from DAVE_Init() that are located in corresponding main function.
 */
void lwip_geth_Lwip_pollReceiveFlags(void);

/**
 * @brief  Increases the LwIP system time.
 * @return None.\n
 *
 * \par<b>Description</b><br>
 * Increases the LwIP system time.
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 *
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 *
 * void core0_main(void)
 * {
 *   // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
 *   // Enable the watchdogs and service them periodically if it is required
 *
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *
 *   // Wait for CPU sync event
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 *
 *   // Initialization of DAVE APPs
 *   DAVE_STATUS_t status = DAVE_Init();
 *
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     // Placeholder for error handler code. The while loop below can be replaced with an user error handler.
 *     while (1U) {
 *     }
 *   }
 *   while(1)
 *   {
 *     lwip_geth_UpdateTickCount();
 *   }
 * }
 * @endcode
 * @note Normally this will be called automatically from DAVE_Init() that are located in corresponding main function.
 */
void lwip_geth_UpdateTickCount(void);

/**
 * @}
 */

/* Include App extern declaration file */
#include "lwip_geth_conf.h"

#ifdef __cplusplus
}
#endif

#endif /* LWIP_GETH_H_*/

/* CODE_BLOCK_END */
