/*********************************************************************************************************************
* ACS APP Name : LWIP_GETH       APP Version: 4.0.4
*
* NOTE:
* This file is generated by ACS. Any manual modification done to this file will be lost when the code is regenerated.
*********************************************************************************************************************/
/**
 * @file lwip_geth_conf.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 *
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip_geth_conf.h"

/*======================================================================================================================
 = CONFIGURATION FOR  LWIP_GETH_0
 =====================================================================================================================*/
/***********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/
const IfxGeth_Crsdv_In      ETH_CRSDIV_PIN  = {&MODULE_GETH, {&MODULE_P11, 11}, Ifx_RxSel_a};
const IfxGeth_Refclk_In     ETH_REFCLK_PIN  = {&MODULE_GETH, {&MODULE_P11, 12}, Ifx_RxSel_a};
const IfxGeth_Rxd_In        ETH_RXD0_PIN    = {&MODULE_GETH, {&MODULE_P11, 10}, Ifx_RxSel_a};
const IfxGeth_Rxd_In        ETH_RXD1_PIN    = {&MODULE_GETH, {&MODULE_P11, 9}, Ifx_RxSel_a};
const IfxGeth_Mdc_Out       ETH_MDC_PIN     = {&MODULE_GETH, {&MODULE_P21, 2}, IfxPort_OutputIdx_alt5};
const IfxGeth_Mdio_InOut    ETH_MDIO_PIN    = {&MODULE_GETH, {&MODULE_P21, 3}, Ifx_RxSel_d, IfxPort_OutputIdx_general};
const IfxGeth_Txd_Out       ETH_TXD0_PIN    = {&MODULE_GETH, {&MODULE_P11, 3}, IfxPort_OutputIdx_alt6};
const IfxGeth_Txd_Out       ETH_TXD1_PIN    = {&MODULE_GETH, {&MODULE_P11, 2}, IfxPort_OutputIdx_alt6};
const IfxGeth_Txen_Out      ETH_TXEN_PIN    = {&MODULE_GETH, {&MODULE_P11, 6}, IfxPort_OutputIdx_alt6};

const IfxGeth_Eth_RmiiPins rmii_pins =
{
  .crsDiv                                   = &ETH_CRSDIV_PIN,  /* CRSDIV */
  .refClk                                   = &ETH_REFCLK_PIN,  /* REFCLK */
  .rxd0                                     = &ETH_RXD0_PIN,    /* RXD0 */
  .rxd1                                     = &ETH_RXD1_PIN,    /* RXD1 */
  .mdc                                      = &ETH_MDC_PIN,     /* MDC */
  .mdio                                     = &ETH_MDIO_PIN,    /* MDIO */
  .txd0                                     = &ETH_TXD0_PIN,    /* TXD0 */
  .txd1                                     = &ETH_TXD1_PIN,    /* TXD1 */
  .txEn                                     = &ETH_TXEN_PIN     /* TXEN */
};

/* GETH module configuration  */
const IfxGeth_Eth_Config LWIP_GETH_0_geth_lld_config =
{
  .gethSFR                                  = &MODULE_GETH,
  .phyInterfaceMode                         = IfxGeth_PhyInterfaceMode_rmii,
  .pins =
  {
    .rmiiPins =&rmii_pins,
    .rgmiiPins = NULL_PTR,
    .miiPins = NULL_PTR,
  },
  .mac =
  {
    .duplexMode                             = IfxGeth_DuplexMode_fullDuplex,
    .lineSpeed                              = IfxGeth_LineSpeed_100Mbps,
    .loopbackMode                           = IfxGeth_LoopbackMode_disable,
    .maxPacketSize                          = 1518,
    .macAddress                             = {0, 3, 25, 69, 0, 0}
  },
  .mtl =
  {
    .numOfTxQueues                          = 1,
    .txSchedulingAlgorithm                  = IfxGeth_TxSchedulingAlgorithm_wrr,
    .numOfRxQueues                          = 1,
    .rxArbitrationAlgorithm                 = IfxGeth_RxArbitrationAlgorithm_sp,
    .txQueue =
    {
      {
        .queueEnable                        = TRUE,
        .storeAndForward                    = TRUE,
        .txQueueSize                        = IfxGeth_QueueSize_8192Bytes,
        .txQueueUnderflowInterruptEnabled   = FALSE
      }
    },
    .rxQueue =
    {
      {
        .queueEnable                        = TRUE,
        .storeAndForward                    = TRUE,
        .rxQueueSize                        = IfxGeth_QueueSize_8192Bytes,
        .forwardErrorPacket                 = FALSE,
        .forwardUndersizedGoodPacket        = FALSE,
        .daBasedDmaChannelEnabled           = FALSE,
        .rxDmaChannelMap                    = IfxGeth_RxDmaChannel_0,
        .rxQueueOverflowInterruptEnabled    = FALSE
      }
    },
    .interrupt =
    {
      .serviceRequest                       = IfxGeth_ServiceRequest_1,
      .priority                             = 1,
      .provider                             = IfxSrc_Tos_cpu0
    }
  },
  .dma =
  {
    .numOfTxChannels                        = 1,
    .numOfRxChannels                        = 1,
    .addressAlignedBeatsEnabled             = FALSE,
    .fixedBurstEnabled                      = FALSE,
    .mixedBurstEnabled                      = FALSE,
    .txChannel =
    {
      {
        .channelEnable                      = TRUE,
        .channelId                          = IfxGeth_TxDmaChannel_0,
        .maxBurstLength                     = IfxGeth_DmaBurstLength_0,
        .txDescrList                        = (IfxGeth_TxDescrList *)&IfxGeth_Eth_txDescrList[0], //is gethIndex needed?
        .txBuffer1StartAddress              = (uint32 *)&channel0TxBuffer1[0][0],
        .txBuffer1Size                      = IFXGETH_MAX_TX_BUFFER_SIZE,
        .enableOSF                          = FALSE
      }
    },
    .rxChannel =
    {
      {
        .channelEnable                      = TRUE,
        .channelId                          = IfxGeth_RxDmaChannel_0,
        .maxBurstLength                     = IfxGeth_DmaBurstLength_0,
        .rxDescrList                        = (IfxGeth_RxDescrList *)&IfxGeth_Eth_rxDescrList[0],
        .rxBuffer1StartAddress              = (uint32 *)&channel0RxBuffer1[0][0],
        .rxBuffer1Size                      = IFXGETH_MAX_RX_BUFFER_SIZE
      }
    },
    .txInterrupt =
    {
      {
        .channelId                          = IfxGeth_DmaChannel_0,
        .priority                           = 10,
        .provider                           = IfxSrc_Tos_cpu0,
      }
    },
    .rxInterrupt =
    {
      {
        .channelId                          = IfxGeth_DmaChannel_0,
        .priority                           = 100,
        .provider                           = IfxSrc_Tos_cpu0,
      }
    }
  },
  .rgmiiTxSkewControl                       = 0,
  .rgmiiRxSkewControl                       = 0
};

/* LWIP_GETH APP configuration structure */
const LWIP_GETH_CONF_t LWIP_GETH_0_config =
{
  .geth_lld_config                          = &LWIP_GETH_0_geth_lld_config,
  .hostname                                 = "lwip",
  .mtu                                      = 1500
};

/***********************************************************************************************************************
 * GLOBAL DATA
 **********************************************************************************************************************/
/* LLD handle structure */
IfxGeth_Eth LWIP_GETH_0_lld_handle;

/* APP handle structure */
LWIP_GETH_t LWIP_GETH_0 =
{
  .app_config                               = &LWIP_GETH_0_config,
  .geth_module                              = &LWIP_GETH_0_lld_handle,
#if NO_SYS
  .stm_module                               = &TIMER_STM_0,
#endif
#if LWIP_GETH_DEBUG_ENABLED
  .printf_asclin_app                        = NULL_PTR,
#endif
  .app_is_initialized                       = FALSE
};

LWIP_GETH_t *lwip_geth_handle = &LWIP_GETH_0;

/* CODE_BLOCK_END */

