/**
 * @file lwip_geth_private_phy_dp83825i.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */

#ifndef LWIP_GETH_PRIVATE_PHY_DP83825I_H
#define LWIP_GETH_PRIVATE_PHY_DP83825I_H

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip_geth_conf.h"
#if (PHY_DEVICE_NAME == PHY_DP83825I)
#include "IfxGeth_Eth.h"

/***********************************************************************************************************************
 * FUNCTION PROTOTYPES
 **********************************************************************************************************************/
IFX_EXTERN volatile uint32 IfxGeth_Eth_Phy_Dp83825i_mdioTimeoutCnt;
IFX_EXTERN volatile uint32 IfxGeth_Eth_Phy_Dp83825i_resetTimeoutCnt;
IFX_EXTERN void lwip_geth_private_Phy_Dp83825i_reset(void);
IFX_EXTERN uint32 lwip_geth_private_Phy_Dp83825i_init(void);
IFX_EXTERN uint32 lwip_geth_private_Phy_Dp83825i_link_status(void);
IFX_EXTERN void lwip_geth_private_Phy_Dp83825i_read_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 *pdata);
IFX_EXTERN void lwip_geth_private_Phy_Dp83825i_write_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 data);

#endif /* PHY_DEVICE_NAME == PHY_DP83825I */
#endif /* LWIP_GETH_PRIVATE_PHY_RTL8211F_H */

/* CODE_BLOCK_END */
