#ifndef ETHSTARTUPTIMING_H
#define ETHSTARTUPTIMING_H

#include "Std_Types.h"
#include "BSW/Diag/Dcm/Dcm.h"

#define ETHSTARTUPTIMING_ROUTINE_ID              (0xF192u)
#define ETHSTARTUPTIMING_MAGIC                   (0x45544854u)
#define ETHSTARTUPTIMING_VERSION                 (2u)
#define ETHSTARTUPTIMING_MAX_EVENTS              (52u)
#define ETHSTARTUPTIMING_FLAG_FREQ_INVALID       (0x00000001u)
#define ETHSTARTUPTIMING_FLAG_TX_SUBMIT_VALID    (0x00000002u)
#define ETHSTARTUPTIMING_FLAG_TX_COMPLETE_VALID  (0x00000004u)
#define ETH_TIMING_FLAG_TIMESTAMP_INVALID        (0x00000008u)
#define ETHSTARTUPTIMING_FLAG_EARLY_CAPTURE      (0x00000010u)
#define ETHSTARTUPTIMING_FLAG_CAPTURE_CLOSED     (0x00000020u)
#define ETHSTARTUPTIMING_FLAG_REINIT_OBSERVED    (0x00000040u)

#define ETHSTARTUPTIMING_RX_NONE                 (0u)
#define ETHSTARTUPTIMING_RX_ARP                  (1u)
#define ETHSTARTUPTIMING_RX_IPV4_ICMP            (2u)
#define ETHSTARTUPTIMING_RX_IPV4_UDP             (3u)
#define ETHSTARTUPTIMING_RX_IPV4_TCP             (4u)
#define ETHSTARTUPTIMING_RX_DOIP                 (5u)
#define ETHSTARTUPTIMING_RX_OTHER                (6u)

typedef enum
{
    ETHSTARTUPTIMING_EVENT_REFERENCE = 0u,
    ETHSTARTUPTIMING_EVENT_ETH_STARTUP_ENTER,
    ETHSTARTUPTIMING_EVENT_ETH_STARTUP_COMPLETE,
    ETHSTARTUPTIMING_EVENT_GETH_INIT_ENTER,
    ETHSTARTUPTIMING_EVENT_GETH_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_GETH_DMA_INIT_ENTER,
    ETHSTARTUPTIMING_EVENT_GETH_DMA_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_GETH_RX_READY,
    ETHSTARTUPTIMING_EVENT_GETH_TX_READY,
    ETHSTARTUPTIMING_EVENT_RMII_INIT_ENTER,
    ETHSTARTUPTIMING_EVENT_RMII_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_MDIO_INIT_ENTER,
    ETHSTARTUPTIMING_EVENT_MDIO_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_PHY_RESET_ASSERT,
    ETHSTARTUPTIMING_EVENT_PHY_RESET_RELEASE,
    ETHSTARTUPTIMING_EVENT_PHY_INIT_ENTER,
    ETHSTARTUPTIMING_EVENT_PHY_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_PHY_AUTONEG_START,
    ETHSTARTUPTIMING_EVENT_PHY_AUTONEG_WAIT_ENTER,
    ETHSTARTUPTIMING_EVENT_PHY_AUTONEG_WAIT_EXIT,
    ETHSTARTUPTIMING_EVENT_PHY_AUTONEG_COMPLETE,
    ETHSTARTUPTIMING_EVENT_PHY_LINK_DETECTED,
    ETHSTARTUPTIMING_EVENT_LWIP_INIT_ENTER,
    ETHSTARTUPTIMING_EVENT_LWIP_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_TCPIP_THREAD_READY,
    ETHSTARTUPTIMING_EVENT_NETIF_ADD_ENTER,
    ETHSTARTUPTIMING_EVENT_NETIF_ADD_COMPLETE,
    ETHSTARTUPTIMING_EVENT_NETIF_ADMIN_UP,
    ETHSTARTUPTIMING_EVENT_NETIF_LINK_UP,
    ETHSTARTUPTIMING_EVENT_TCPIP_READY,
    ETHSTARTUPTIMING_EVENT_SOAD_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_DOIP_INIT_COMPLETE,
    ETHSTARTUPTIMING_EVENT_SOCKET_OPEN_REQUEST,
    ETHSTARTUPTIMING_EVENT_SOCKET_READY,
    ETHSTARTUPTIMING_EVENT_FIRST_MAC_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_GETH_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_LWIP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_IP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_UDP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_TCP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_APP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_DOIP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_ARP_REQUEST,
    ETHSTARTUPTIMING_EVENT_FIRST_ARP_RX,
    ETHSTARTUPTIMING_EVENT_FIRST_ARP_RESOLVED,
    ETHSTARTUPTIMING_EVENT_FIRST_APP_TX_REQUEST,
    ETHSTARTUPTIMING_EVENT_FIRST_LWIP_TX,
    ETHSTARTUPTIMING_EVENT_FIRST_NETIF_LINKOUTPUT,
    ETHSTARTUPTIMING_EVENT_FIRST_GETH_TX_REQUEST,
    ETHSTARTUPTIMING_EVENT_FIRST_DMA_TX_SUBMIT,
    ETHSTARTUPTIMING_EVENT_FIRST_DMA_TX_COMPLETE,
    ETHSTARTUPTIMING_EVENT_FIRST_TX_SUCCESS
} EthStartupTiming_EventIdType;

uint64 EthTiming_ReadStmTicks(void);
void EthStartupTiming_Init(void);
void EthStartupTiming_EnableNvMStatus(void);
void EthStartupTiming_OnNvMReadAllComplete(void);
void EthStartupTiming_NotifyReinitialization(void);
void EthStartupTiming_Capture(EthStartupTiming_EventIdType eventId);
void EthStartupTiming_CaptureWithMeta(EthStartupTiming_EventIdType eventId, uint32 metadata);
void EthStartupTiming_CaptureFirstRx(uint32 rxClass);
void EthStartupTiming_CaptureFirstTxSubmit(void);
void EthStartupTiming_CaptureFirstTxComplete(void);
boolean EthStartupTiming_IsRoutineId(uint16 routineId);
Dcm_ReturnType EthStartupTiming_HandleRoutineControl(
        Dcm_OpStatusType opStatus,
        uint8 routineControlType,
        uint16 routineId,
        const uint8* reqData,
        Dcm_PduLengthType reqLen,
        uint8* respData,
        Dcm_PduLengthType* respLen);

typedef struct
{
    uint16 eventId;
    uint16 valid;
    uint64 timestampTicks;
    uint32 metadata;
    uint32 reserved;
} EthStartupTiming_NvEventType;

typedef struct
{
    uint32 magic;
    uint16 version;
    uint16 eventCapacity;
    uint64 stmFrequencyHz;
    uint64 referenceTicks;
    uint32 capturedMask[2];
    uint32 flags;
    uint32 missedLockCount;
    uint32 measurementState;
    uint32 firstRxClass;
    uint32 reserved[4];
    EthStartupTiming_NvEventType events[ETHSTARTUPTIMING_MAX_EVENTS];
} EthStartupTiming_NvImageType;

#define ETHSTARTUPTIMING_NVM_IMAGE_SIZE          ((uint32)sizeof(EthStartupTiming_NvImageType))

#endif /* ETHSTARTUPTIMING_H */
