/*********************************************************************************************************************
* ACS APP Name : LWIP_GETH       APP Version: 4.0.4
*
* NOTE:
* This file is generated by ACS. Any manual modification done to this file will be lost when the code is regenerated.
*********************************************************************************************************************/
/**
 * @file lwip_geth_conf.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */

#ifndef LWIP_GETH_CONF_H_
#define LWIP_GETH_CONF_H_

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip_geth.h"

/***********************************************************************************************************************
 * EXTERN DECLARATIONS
***********************************************************************************************************************/
extern  LWIP_GETH_t LWIP_GETH_0;
extern  LWIP_GETH_t *lwip_geth_handle;
extern void netif_status_cb(struct netif *netif);

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
/* Macros for APP version */
#define LWIP_GETH_MAJOR_VERSION         (4U)
#define LWIP_GETH_MINOR_VERSION         (0U)
#define LWIP_GETH_PATCH_VERSION         (4U)

#define PHY_DP83825I                    (0U)
#define PHY_RTL8211F                    (1U)
#define PHY_USER_DEFINED                (2U)

#ifndef PHY_DEVICE_NAME

#define PHY_DEVICE_NAME  PHY_DP83825I
#endif

/* IPv4 address */
/* Static IPv4 address */
#define IP_ADDR0                        (192U)
#define IP_ADDR1                        (168U)
#define IP_ADDR2                        (1U)
#define IP_ADDR3                        (10U)

/*IPv4 subnet mask*/
/*Static IPv4 address*/
#define NETMASK_ADDR0                   (255U)
#define NETMASK_ADDR1                   (255U)
#define NETMASK_ADDR2                   (255U)
#define NETMASK_ADDR3                   (0U)

/*IPv4 gateway address*/
/*Static IPv4 address*/
#define GW_ADDR0                        (192U)
#define GW_ADDR1                        (168U)
#define GW_ADDR2                        (1U)
#define GW_ADDR3                        (1U)

#define CPU_WHICH_SERVICE_ETHERNET      2
#define ISR_PRIORITY_GETH_TX            29
#define ISR_PRIORITY_GETH_RX            30
#define LWIP_GETH_IS_ISR                1

#define LWIP_GETH_TASK_PRIO_RX          configMAX_PRIORITIES_core2 - 4
#define LWIP_GETH_TASK_STACK_SIZE       512
#define LWIP_GETH_PHY_TASK_PRIO         tskIDLE_PRIORITY_core2 + 4
#define LWIP_GETH_PHY_TASK_STACK_SIZE   256

#define LWIP_GETH_RTOS_ENABLED      1

/* Lab bring-up: keep lwIP netif link-up even if PHY status readout is wrong. */
#define LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP 1

/* Callback function name */
#define LWIP_GETH_NETIF_STATUS_CB_FUNCTION  netif_status_cb
#endif /* ifndef LWIP_GETH_CONF_H_ */

/* CODE_BLOCK_END */
