/**
 * @file lwip_geth_netif.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * Copyright (c) 2015-2025, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG.
 ***********************************************************************************************************************
 *
 * @endcond
 */

#ifndef LWIP_GETH_NETIF_H
#define LWIP_GETH_NETIF_H

#include "Ifx_Types.h"

extern volatile uint32 lwip_geth_DebugMdioWaitTimeoutCnt;
extern volatile uint32 lwip_geth_DebugPhyResetTimeoutCnt;
extern volatile uint32 lwip_geth_DebugLowLevelInitState;
extern volatile uint32 lwip_geth_DebugRxInvalidFrameCnt;
extern volatile uint32 lwip_geth_DebugRxAllocFailCnt;
extern volatile uint32 lwip_geth_DebugTxNoBufferCnt;
extern volatile uint32 lwip_geth_DebugLowLevelOutputCount;
extern volatile uint32 lwip_geth_DebugLowLevelOutputOkCount;
extern volatile uint32 lwip_geth_DebugLowLevelOutputErrCnt;
extern volatile uint32 lwip_geth_DebugLowLevelInputCallCount;
extern volatile uint32 lwip_geth_DebugLowLevelInputPacketCount;
extern volatile uint32 lwip_geth_DebugNetifInputLoopCount;
extern volatile uint32 lwip_geth_DebugNetifInputOnceCount;
extern volatile uint32 lwip_geth_DebugNetifInputOkCount;
extern volatile uint32 lwip_geth_DebugNetifInputFailCount;
extern volatile uint32 lwip_geth_DebugNetifInputUnknownTypeCount;
extern volatile uint32 lwip_geth_DebugRxWaitCount;
extern volatile uint32 lwip_geth_DebugLastRxLen;
extern volatile uint32 lwip_geth_DebugLastTxLen;
extern volatile uint32 lwip_geth_DebugLastEthType;
extern volatile uint32 lwip_geth_DebugLastTxDescrAddr;
extern volatile uint32 lwip_geth_DebugLastTxBufferAddr;
extern volatile uint32 lwip_geth_DebugLastRxDescrAddr;
extern volatile uint32 lwip_geth_DebugLastRxBufferAddr;

err_t lwip_geth_netif_init(struct netif *netif);
uint8 lwip_geth_netif_input_once(struct netif *netif);
void lwip_geth_netif_input(void * pvParameters);

#endif
