#ifndef DEM_CFG_H_
#define DEM_CFG_H_

#include "Dem_Types.h"
#include "GatewaySwc.h"

#define DEM_AIMODEL_EVENT_COUNT        4u
#define DEM_AIMODEL_CONSUMER_EVENT_COUNT  75u
#define DEM_ETHERNET_DIAG_EVENT_COUNT  15u
#define DEM_CAN_BUS_DIAG_EVENT_COUNT   8u
#define DEM_LIN_BUS_DIAG_EVENT_COUNT   5u
#define DEM_STATIC_EVENT_COUNT         (4u + DEM_AIMODEL_EVENT_COUNT + \
        DEM_ETHERNET_DIAG_EVENT_COUNT + DEM_CAN_BUS_DIAG_EVENT_COUNT + \
        DEM_LIN_BUS_DIAG_EVENT_COUNT)
#define DEM_GATEWAY_RX_MESSAGE_EVENT_COUNT  GATEWAYSWC_RX_MESSAGE_DIAG_COUNT
#define DEM_MAX_EVENTS                 (DEM_STATIC_EVENT_COUNT + \
        DEM_AIMODEL_CONSUMER_EVENT_COUNT + \
        DEM_GATEWAY_RX_MESSAGE_EVENT_COUNT)
#define DEM_PRIMARY_MEMORY_SIZE        96u
#define DEM_STORED_DATA_EVENT_LIMIT    DEM_PRIMARY_MEMORY_SIZE
#define DEM_DTC_TIMESTAMP_DATA_SIZE    22u
#define DEM_SNAPSHOT_DATA_SIZE         256u

#define DEM_SNAPSHOT_VEHICLE_TIME_NS_OFFSET    0u
#define DEM_SNAPSHOT_UTC_TIME_NS_OFFSET        8u
#define DEM_SNAPSHOT_UTC_VALID_OFFSET          16u
#define DEM_SNAPSHOT_TIME_SOURCE_OFFSET        17u
#define DEM_SNAPSHOT_MCU_TEMP_CDEG_OFFSET      18u
#define DEM_SNAPSHOT_VERSION_OFFSET            20u
#define DEM_SNAPSHOT_KIND_OFFSET               21u
#define DEM_SNAPSHOT_VERSION                   2u
#define DEM_SNAPSHOT_KIND_COMMON               0u
#define DEM_SNAPSHOT_KIND_ETHERNET             1u
#define DEM_SNAPSHOT_KIND_AIMODEL              2u
#define DEM_SNAPSHOT_KIND_AIMODEL_CONSUMER     3u
#define DEM_SNAPSHOT_KIND_CAN_BUS              4u
#define DEM_SNAPSHOT_KIND_LIN_BUS              5u

#define DEM_NVM_ENABLED                1u
#define DEM_NVM_BLOCK_ID_PRIMARY       1u
#define DEM_NVM_WRITE_RETRY_LIMIT      3u
#define DEM_NVM_INCLUDE_NVM_H         1u

#define DEM_DEFAULT_OPERATION_CYCLE    0u

#define DEM_EVENT_ID_MCUSM_SW_ERROR               1u
#define DEM_EVENT_ID_PMS_ERRATA_STARTUP           ((Dem_EventIdType)(DEM_EVENT_ID_MCUSM_SW_ERROR + 1u))
#define DEM_EVENT_ID_CODING_ECU_NOT_CODED         ((Dem_EventIdType)(DEM_EVENT_ID_PMS_ERRATA_STARTUP + 1u))
#define DEM_EVENT_ID_CODING_INVALID               ((Dem_EventIdType)(DEM_EVENT_ID_CODING_ECU_NOT_CODED + 1u))
#define DEM_EVENT_ID_AIMODEL_INPUT_INVALID        ((Dem_EventIdType)(DEM_EVENT_ID_CODING_INVALID + 1u))
#define DEM_EVENT_ID_AIMODEL_INFERENCE_INVALID    ((Dem_EventIdType)(DEM_EVENT_ID_AIMODEL_INPUT_INVALID + 1u))
#define DEM_EVENT_ID_AIMODEL_DEADLINE_EXCEEDED    ((Dem_EventIdType)(DEM_EVENT_ID_AIMODEL_INFERENCE_INVALID + 1u))
#define DEM_EVENT_ID_AIMODEL_OUTPUT_OUT_OF_RANGE  ((Dem_EventIdType)(DEM_EVENT_ID_AIMODEL_DEADLINE_EXCEEDED + 1u))
#define DEM_EVENT_ID_ETH_LINK_LOST                ((Dem_EventIdType)(DEM_EVENT_ID_AIMODEL_OUTPUT_OUT_OF_RANGE + 1u))
#define DEM_EVENT_ID_ETH_CTRL_DMA_FAILURE         ((Dem_EventIdType)(DEM_EVENT_ID_ETH_LINK_LOST + 1u))
#define DEM_EVENT_ID_ETH_RX_COMM_FAILURE          ((Dem_EventIdType)(DEM_EVENT_ID_ETH_CTRL_DMA_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_TX_COMM_FAILURE          ((Dem_EventIdType)(DEM_EVENT_ID_ETH_RX_COMM_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_TCP_UNEXPECTED_TERMINATION ((Dem_EventIdType)(DEM_EVENT_ID_ETH_TX_COMM_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_TCP_ESTABLISHMENT_FAILURE ((Dem_EventIdType)(DEM_EVENT_ID_ETH_TCP_UNEXPECTED_TERMINATION + 1u))
#define DEM_EVENT_ID_ETH_UDP_SUPERVISION_TIMEOUT  ((Dem_EventIdType)(DEM_EVENT_ID_ETH_TCP_ESTABLISHMENT_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_SERVICE_AVAILABILITY_FAILURE ((Dem_EventIdType)(DEM_EVENT_ID_ETH_UDP_SUPERVISION_TIMEOUT + 1u))
#define DEM_EVENT_ID_ETH_DOIP_COMM_FAILURE        ((Dem_EventIdType)(DEM_EVENT_ID_ETH_SERVICE_AVAILABILITY_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_PARTNER_COMM_TERMINATED  ((Dem_EventIdType)(DEM_EVENT_ID_ETH_DOIP_COMM_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_PHY_COMMUNICATION_FAULT  ((Dem_EventIdType)(DEM_EVENT_ID_ETH_PARTNER_COMM_TERMINATED + 1u))
#define DEM_EVENT_ID_ETH_PHY_FAULT                ((Dem_EventIdType)(DEM_EVENT_ID_ETH_PHY_COMMUNICATION_FAULT + 1u))
#define DEM_EVENT_ID_ETH_NEGOTIATION_FAILURE      ((Dem_EventIdType)(DEM_EVENT_ID_ETH_PHY_FAULT + 1u))
#define DEM_EVENT_ID_ETH_UNEXPECTED_LINK_MODE     ((Dem_EventIdType)(DEM_EVENT_ID_ETH_NEGOTIATION_FAILURE + 1u))
#define DEM_EVENT_ID_ETH_RESOURCE_EXHAUSTION      ((Dem_EventIdType)(DEM_EVENT_ID_ETH_UNEXPECTED_LINK_MODE + 1u))
#define DEM_EVENT_ID_ETH_DIAG_LAST                DEM_EVENT_ID_ETH_RESOURCE_EXHAUSTION
#define DEM_EVENT_ID_CAN_BUS_DIAG_FIRST           ((Dem_EventIdType)(DEM_EVENT_ID_ETH_DIAG_LAST + 1u))
#define DEM_EVENT_ID_CAN_CLASSIC_BUS_OFF          DEM_EVENT_ID_CAN_BUS_DIAG_FIRST
#define DEM_EVENT_ID_CAN_CLASSIC_ERROR_PASSIVE    ((Dem_EventIdType)(DEM_EVENT_ID_CAN_CLASSIC_BUS_OFF + 1u))
#define DEM_EVENT_ID_CAN_CLASSIC_CONTROLLER_FAULT ((Dem_EventIdType)(DEM_EVENT_ID_CAN_CLASSIC_ERROR_PASSIVE + 1u))
#define DEM_EVENT_ID_CAN_CLASSIC_PROTOCOL_ERROR   ((Dem_EventIdType)(DEM_EVENT_ID_CAN_CLASSIC_CONTROLLER_FAULT + 1u))
#define DEM_EVENT_ID_CANFD_BUS_OFF                ((Dem_EventIdType)(DEM_EVENT_ID_CAN_CLASSIC_PROTOCOL_ERROR + 1u))
#define DEM_EVENT_ID_CANFD_ERROR_PASSIVE          ((Dem_EventIdType)(DEM_EVENT_ID_CANFD_BUS_OFF + 1u))
#define DEM_EVENT_ID_CANFD_CONTROLLER_FAULT       ((Dem_EventIdType)(DEM_EVENT_ID_CANFD_ERROR_PASSIVE + 1u))
#define DEM_EVENT_ID_CANFD_PROTOCOL_ERROR         ((Dem_EventIdType)(DEM_EVENT_ID_CANFD_CONTROLLER_FAULT + 1u))
#define DEM_EVENT_ID_CAN_BUS_DIAG_LAST            DEM_EVENT_ID_CANFD_PROTOCOL_ERROR
#define DEM_EVENT_ID_LIN_BUS_DIAG_FIRST           ((Dem_EventIdType)(DEM_EVENT_ID_CAN_BUS_DIAG_LAST + 1u))
#define DEM_EVENT_ID_LIN1_HVDCDC_NO_COMMUNICATION DEM_EVENT_ID_LIN_BUS_DIAG_FIRST
#define DEM_EVENT_ID_LIN1_PROTOCOL_ERROR          ((Dem_EventIdType)(DEM_EVENT_ID_LIN1_HVDCDC_NO_COMMUNICATION + 1u))
#define DEM_EVENT_ID_LIN1_CONTROLLER_FAULT        ((Dem_EventIdType)(DEM_EVENT_ID_LIN1_PROTOCOL_ERROR + 1u))
#define DEM_EVENT_ID_LIN1_WAKEUP_FAILURE          ((Dem_EventIdType)(DEM_EVENT_ID_LIN1_CONTROLLER_FAULT + 1u))
#define DEM_EVENT_ID_LIN1_SLEEP_FAILURE           ((Dem_EventIdType)(DEM_EVENT_ID_LIN1_WAKEUP_FAILURE + 1u))
#define DEM_EVENT_ID_LIN_BUS_DIAG_LAST            DEM_EVENT_ID_LIN1_SLEEP_FAILURE
#define DEM_EVENT_ID_AIMODEL_CONSUMER_FAULT_FIRST ((Dem_EventIdType)(DEM_EVENT_ID_LIN_BUS_DIAG_LAST + 1u))
#define DEM_EVENT_ID_AIMODEL_CONSUMER_FAULT_LAST  ((Dem_EventIdType)(DEM_EVENT_ID_AIMODEL_CONSUMER_FAULT_FIRST + DEM_AIMODEL_CONSUMER_EVENT_COUNT - 1u))
#define DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT   ((Dem_EventIdType)(DEM_EVENT_ID_AIMODEL_CONSUMER_FAULT_LAST + 1u))
#define DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_FIRST DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT
#define DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_LAST  ((Dem_EventIdType)(DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_FIRST + DEM_GATEWAY_RX_MESSAGE_EVENT_COUNT - 1u))

#define DEM_DTC_MCUSM_SW_ERROR                    0x00010101u
#define DEM_DTC_PMS_ERRATA_STARTUP                0x00010102u
#define DEM_DTC_CODING_ECU_NOT_CODED              0x00023000u
#define DEM_DTC_CODING_INVALID                    0x00023001u
#define DEM_DTC_AIMODEL_INPUT_INVALID             0x00024000u
#define DEM_DTC_AIMODEL_INFERENCE_INVALID         0x00024001u
#define DEM_DTC_AIMODEL_DEADLINE_EXCEEDED         0x00024002u
#define DEM_DTC_AIMODEL_OUTPUT_OUT_OF_RANGE       0x00024003u
#define DEM_DTC_AIMODEL_CONSUMER_FAULT            0x00024100u
#define DEM_DTC_ETH_LINK_LOST                     0x00022000u
#define DEM_DTC_ETH_CTRL_DMA_FAILURE              0x00022001u
#define DEM_DTC_ETH_RX_COMM_FAILURE               0x00022002u
#define DEM_DTC_ETH_TX_COMM_FAILURE               0x00022003u
#define DEM_DTC_ETH_TCP_UNEXPECTED_TERMINATION    0x00022004u
#define DEM_DTC_ETH_TCP_ESTABLISHMENT_FAILURE     0x00022005u
#define DEM_DTC_ETH_UDP_SUPERVISION_TIMEOUT       0x00022006u
#define DEM_DTC_ETH_SERVICE_AVAILABILITY_FAILURE  0x00022007u
#define DEM_DTC_ETH_DOIP_COMM_FAILURE             0x00022008u
#define DEM_DTC_ETH_PARTNER_COMM_TERMINATED       0x00022009u
#define DEM_DTC_ETH_PHY_COMMUNICATION_FAULT       0x0002200Au
#define DEM_DTC_ETH_PHY_FAULT                     0x0002200Bu
#define DEM_DTC_ETH_NEGOTIATION_FAILURE           0x0002200Cu
#define DEM_DTC_ETH_UNEXPECTED_LINK_MODE          0x0002200Du
#define DEM_DTC_ETH_RESOURCE_EXHAUSTION           0x0002200Eu
#define DEM_DTC_CAN_BUS_DIAG                      0x00022100u
#define DEM_DTC_CAN_CLASSIC_BUS_OFF               0x00022100u
#define DEM_DTC_CAN_CLASSIC_ERROR_PASSIVE         0x00022101u
#define DEM_DTC_CAN_CLASSIC_CONTROLLER_FAULT      0x00022102u
#define DEM_DTC_CAN_CLASSIC_PROTOCOL_ERROR        0x00022103u
#define DEM_DTC_CANFD_BUS_OFF                     0x00022104u
#define DEM_DTC_CANFD_ERROR_PASSIVE               0x00022105u
#define DEM_DTC_CANFD_CONTROLLER_FAULT            0x00022106u
#define DEM_DTC_CANFD_PROTOCOL_ERROR              0x00022107u
#define DEM_DTC_LIN_BUS_DIAG                      0x00022200u
#define DEM_DTC_LIN1_HVDCDC_NO_COMMUNICATION      0x00022200u
#define DEM_DTC_LIN1_PROTOCOL_ERROR               0x00022201u
#define DEM_DTC_LIN1_CONTROLLER_FAULT             0x00022202u
#define DEM_DTC_LIN1_WAKEUP_FAILURE               0x00022203u
#define DEM_DTC_LIN1_SLEEP_FAILURE                0x00022204u
#define DEM_DTC_GATEWAY_RX_MESSAGE_TIMEOUT        0x00021000u

void Dem_EnterCritical(void);
void Dem_ExitCritical(void);

#ifndef DEM_ENTER_CRITICAL
#define DEM_ENTER_CRITICAL() Dem_EnterCritical()
#endif

#ifndef DEM_EXIT_CRITICAL
#define DEM_EXIT_CRITICAL() Dem_ExitCritical()
#endif

extern const Dem_ConfigType Dem_Config;
Std_ReturnType Dem_Cfg_GetEventConfig(uint16 eventIndex, Dem_EventConfigType *eventConfig);
Std_ReturnType Dem_Cfg_CaptureTimestampTemperatureData(uint8 *buffer, uint16 *length, uint8 snapshotKind);

#endif
