#ifndef DEM_CFG_H_
#define DEM_CFG_H_

#include "Dem_Types.h"
#include "GatewaySwc.h"

#define DEM_STATIC_EVENT_COUNT         3u
#define DEM_GATEWAY_RX_MESSAGE_EVENT_COUNT  GATEWAYSWC_RX_MESSAGE_DIAG_COUNT
#define DEM_GATEWAY_RX_SIGNAL_EVENT_COUNT   GATEWAYSWC_RX_SIGNAL_DIAG_COUNT
#define DEM_MAX_EVENTS                 (DEM_STATIC_EVENT_COUNT + \
        DEM_GATEWAY_RX_MESSAGE_EVENT_COUNT + \
        DEM_GATEWAY_RX_SIGNAL_EVENT_COUNT)
#define DEM_PRIMARY_MEMORY_SIZE        64u
#define DEM_STORED_DATA_EVENT_LIMIT    DEM_PRIMARY_MEMORY_SIZE
#define DEM_FREEZE_FRAME_SIZE          32u
#define DEM_EXTENDED_DATA_SIZE         16u

#define DEM_NVM_ENABLED                1u
#define DEM_NVM_BLOCK_ID_PRIMARY       1u
#define DEM_NVM_WRITE_RETRY_LIMIT      3u
#define DEM_NVM_INCLUDE_NVM_H         1u

#define DEM_CRC32_INITIAL_VALUE        0xFFFFFFFFu
#define DEM_NV_MAGIC                   0x44454D31u
#define DEM_NV_VERSION                 0x0002u

#define DEM_DEFAULT_OPERATION_CYCLE    0u

#define DEM_EVENT_ID_MCUSM_SW_ERROR               1u
#define DEM_EVENT_ID_CODING_ECU_NOT_CODED         ((Dem_EventIdType)(DEM_EVENT_ID_MCUSM_SW_ERROR + 1u))
#define DEM_EVENT_ID_CODING_INVALID               ((Dem_EventIdType)(DEM_EVENT_ID_CODING_ECU_NOT_CODED + 1u))
#define DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT   ((Dem_EventIdType)(DEM_EVENT_ID_CODING_INVALID + 1u))
#define DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_FIRST DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT
#define DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_LAST  ((Dem_EventIdType)(DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_FIRST + DEM_GATEWAY_RX_MESSAGE_EVENT_COUNT - 1u))
#define DEM_EVENT_ID_GATEWAY_RX_SIGNAL_INVALID    ((Dem_EventIdType)(DEM_EVENT_ID_GATEWAY_RX_MESSAGE_TIMEOUT_LAST + 1u))
#define DEM_EVENT_ID_GATEWAY_RX_SIGNAL_INVALID_FIRST DEM_EVENT_ID_GATEWAY_RX_SIGNAL_INVALID
#define DEM_EVENT_ID_GATEWAY_RX_SIGNAL_INVALID_LAST   ((Dem_EventIdType)(DEM_EVENT_ID_GATEWAY_RX_SIGNAL_INVALID_FIRST + DEM_GATEWAY_RX_SIGNAL_EVENT_COUNT - 1u))

#define DEM_DTC_MCUSM_SW_ERROR                    0x00010101u
#define DEM_DTC_CODING_ECU_NOT_CODED              0x00023000u
#define DEM_DTC_CODING_INVALID                    0x00023001u
#define DEM_DTC_GATEWAY_RX_MESSAGE_TIMEOUT        0x00021000u
#define DEM_DTC_GATEWAY_RX_SIGNAL_INVALID         0x00022000u

void Dem_EnterCritical(void);
void Dem_ExitCritical(void);

#ifndef DEM_ENTER_CRITICAL
#define DEM_ENTER_CRITICAL() Dem_EnterCritical()
#endif

#ifndef DEM_EXIT_CRITICAL
#define DEM_EXIT_CRITICAL() Dem_ExitCritical()
#endif

extern const Dem_ConfigType Dem_Config;
Std_ReturnType Dem_Cfg_GetEventConfig(uint16 eventIndex, Dem_EventConfigType *eventConfig);

#endif
