/**********************************************************************************************************************
 * \file Ifx_Cfg.h
 * \brief Project configuration file.
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef IFX_CFG_H
#define IFX_CFG_H 1

#include "Platform_Types.h"

#define DEVICE_TC375DP                  1
#define DEVICE_TC37X                    1
#define IFX_PIN_PACKAGE_LQFP176         1
#define IFX_CFG_ZGW_CPU0_ONLY           1
#define IFXCPU_NUM_MODULES              (1)

/*********************************************************************************************************************/
/*------------------------------------------Explicit DLMU placement--------------------------------------------------*/
/*********************************************************************************************************************/
/* Ethernet DMA memory is a single explicit non-cached CPU0 DLMU window.
 * Legacy *_CACHED section names remain accepted for source compatibility, but
 * Ethernet DMA users must use AURIX_ETH_DMA so the linker can keep the whole
 * ring/buffer block non-cached. */
#define AURIX_CPU0_DLMU_NC_BASE         (0xB0000000u)
#define AURIX_CPU0_DLMU_NC_SIZE         (64u * 1024u)
#define AURIX_ETH_DMA_BASE              (AURIX_CPU0_DLMU_NC_BASE)
#define AURIX_ETH_DMA_END               (AURIX_CPU0_DLMU_NC_BASE + AURIX_CPU0_DLMU_NC_SIZE)
#define AURIX_ETH_DMA_WINDOW_BYTES      (AURIX_CPU0_DLMU_NC_SIZE)
#define AURIX_ETH_DMA_ALIGNMENT         (32u)

#define AURIX_LMU_CACHED_BSS            __attribute__((section(".bss.lmu_cached")))
#define AURIX_LMU_CACHED_DATA           __attribute__((section(".data.lmu_cached")))
#define AURIX_ETH_DMA                   __attribute__((section(".bss.eth_dma")))
#define AURIX_ETH_DMA_CACHED            AURIX_ETH_DMA
#define AURIX_SHARED_CACHED             __attribute__((section(".bss.shared_cached")))

#define AURIX_LMU_NC_BSS                __attribute__((section(".bss.lmu_nc")))
#define AURIX_LMU_NC_DATA               __attribute__((section(".data.lmu_nc")))
#define AURIX_ETH_DMA_NC                AURIX_ETH_DMA
#define AURIX_SHARED_NC                 __attribute__((section(".bss.shared_nc")))

/* APP uses 16/16 descriptors, but the FBL's fixed non-cached DMA linker window
 * is only 64 KiB at 0xb0000000..0xb0010000. With 2592-byte RX/TX buffers,
 * 16/16 descriptors require ~82 KiB and do not link. Use the largest depth
 * that still fits the FBL DMA window while increasing headroom beyond the iLLD
 * default 8/8. */
#define IFXGETH_MAX_TX_DESCRIPTORS      (12)
#define IFXGETH_MAX_RX_DESCRIPTORS      (12)

#if defined(__TASKING__) && !defined(Ifx__dsync)
#define Ifx__dsync()                    __dsync()
#endif

/*********************************************************************************************************************/
/*------------------------------------------Configuration for IfxScu_cfg.h-------------------------------------------*/
/*********************************************************************************************************************/
/* External oscillator frequency in Hz */
#define IFX_CFG_SCU_XTAL_FREQUENCY        (20000000)  /* Allowed values are: 40000000, 25000000, 20000000, 16000000 */

/* PLL,PLL1 and PLL2 frequency are defined in IfxScu_Cfg.h. To change the default frequency, uncomment below lines
 * and choose one of the supported values.
 */

/* System PLL frequency in Hz */
/* #define IFX_CFG_SCU_PLL_FREQUENCY      (300000000) */   /* Allowed values are: 300000000, 240000000, 200000000, 160000000, 
                                                             * 133000000, 80000000 */
/* Peripheral PLL1 frequency in Hz */
/*#define IFX_CFG_SCU_PLL1_FREQUENCY      (320000000) */    /* Allowed values are: 320000000, 160000000 */
/* Peripheral PLL2 frequency in Hz */
/*#define IFX_CFG_SCU_PLL2_FREQUENCY      (200000000) */    /* Allowed values are: 200000000 */

/*********************************************************************************************************************/
/*-----------------------------------Configuration for Software managed interrupt------------------------------------*/
/*********************************************************************************************************************/
/* #define IFX_USE_SW_MANAGED_INT */ /* Decomment this line if the project needs to use Software managed interrupts */

/*********************************************************************************************************************/
/*---------------------------------Configuration for Trap Hook Functions' Extensions---------------------------------*/
/*********************************************************************************************************************/
/* #define IFX_CFG_EXTEND_TRAP_HOOKS */ /* Decomment this line if the project needs to extend trap hook functions */

/* #define IFX_CFG_SSW_RETURN_FROM_MAIN */

/*********************************************************************************************************************/
/*---------------------------------Configuration for Device and Pin package------------------------------------------*/
/*********************************************************************************************************************/

#endif /* IFX_CFG_H */
