/**
 * @file lwip_geth_private_phy_rtl8211f.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip_geth_conf.h"
#if (PHY_DEVICE_NAME == PHY_RTL8211F)
#include "lwip_geth_private_phy_rtl8211f.h"

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
#define IFXGETH_PHY_RTL8211F_MDIO_BMCR          0x00
#define IFXGETH_PHY_RTL8211F_MDIO_BMSR          0x01
#define IFXGETH_PHY_RTL8211F_MDIO_PHYID1        0x02
#define IFXGETH_PHY_RTL8211F_MDIO_PHYID2        0x03
#define IFXGETH_PHY_RTL8211F_MDIO_ANAR          0x04
#define IFXGETH_PHY_RTL8211F_MDIO_ANLPAR        0x05
#define IFXGETH_PHY_RTL8211F_MDIO_ANER          0x06
#define IFXGETH_PHY_RTL8211F_MDIO_ANNPTR        0x07
#define IFXGETH_PHY_RTL8211F_MDIO_ANNPRR        0x08
#define IFXGETH_PHY_RTL8211F_MDIO_GBCR          0x09
#define IFXGETH_PHY_RTL8211F_MDIO_GBSR          0x0A
#define IFXGETH_PHY_RTL8211F_MDIO_MACR          0x0D
#define IFXGETH_PHY_RTL8211F_MDIO_MAADR         0x0E
#define IFXGETH_PHY_RTL8211F_MDIO_GBESR         0x0F
#define IFXGETH_PHY_RTL8211F_MDIO_INER          0x12
#define IFXGETH_PHY_RTL8211F_MDIO_PHYCR1        0x18
#define IFXGETH_PHY_RTL8211F_MDIO_PHYCR2        0x19
#define IFXGETH_PHY_RTL8211F_MDIO_PHYSR         0x1A
#define IFXGETH_PHY_RTL8211F_MDIO_INSR          0x1D
#define IFXGETH_PHY_RTL8211F_MDIO_PAGSR         0x1F
#define IFXGETH_PHY_RTL8211F_MDIO_PHYSCR        0x14
#define IFXGETH_PHY_RTL8211F_MDIO_LCR           0x10
#define IFXGETH_PHY_RTL8211F_MDIO_EEELCR        0x11
#define IFXGETH_PHY_RTL8211F_WAIT_MDIO_READY()  while (GETH_MAC_MDIO_ADDRESS.B.GB) {}

/***********************************************************************************************************************
 * PRIVATE DATA
 **********************************************************************************************************************/
static uint32 IfxGeth_Eth_Phy_Rtl8211f_iPhyInitDone = 0;

/***********************************************************************************************************************
 * FUNCTION IMPLEMENTATIONS
 **********************************************************************************************************************/
uint32 lwip_geth_private_Phy_Rtl8211f_init(void)
{
  IFXGETH_PHY_RTL8211F_WAIT_MDIO_READY();

  /* reset PHY */
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_BMCR, 0x8000);
  uint32 value;

  do
  {
    lwip_geth_private_Phy_Rtl8211f_read_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_BMCR, &value);
  } while (value & 0x8000);                         /* wait for reset to finish */

  /* setup PHY */
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_PAGSR, 0xd08);
  lwip_geth_private_Phy_Rtl8211f_read_mdio_reg(0, 0x11, &value);
  value |= 0x100;                                   /* enable TX-delay */
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, 0x11, value);
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_PAGSR, 0x0);
  /* Set LEDs */
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_PAGSR, 0xd04);
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_LCR, 0x8170);
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_EEELCR, 0x0);
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_PAGSR, 0x0);

  /* enable auto-negotiation, restart auto-negotiation */
  lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(0, IFXGETH_PHY_RTL8211F_MDIO_BMCR, 0x1200);

  /* done */
  IfxGeth_Eth_Phy_Rtl8211f_iPhyInitDone = 1;

  return 1;
}

void lwip_geth_private_Phy_Rtl8211f_read_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 *pdata)
{
  /* 5bit Physical Layer Adddress, 5bit GMII Regnr, 4bit csrclock divider, Read, Busy */
  GETH_MAC_MDIO_ADDRESS.U = (layeraddr << 21) | (regaddr << 16) | (0 << 8) | (3 << 2) | (1 << 0);

  IFXGETH_PHY_RTL8211F_WAIT_MDIO_READY();

  /* get data */
  *pdata = GETH_MAC_MDIO_DATA.U;
}

void lwip_geth_private_Phy_Rtl8211f_write_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 data)
{
  /* put data */
  GETH_MAC_MDIO_DATA.U = data;

  /* 5bit Physical Layer Adddress, 5bit GMII Regnr, 4bit csrclock divider, Write, Busy */
  GETH_MAC_MDIO_ADDRESS.U = (layeraddr << 21) | (regaddr << 16) | (0 << 8) |  (1 << 2) | (1 << 0);

  IFXGETH_PHY_RTL8211F_WAIT_MDIO_READY();
}

#endif /* (PHY_DEVICE_NAME == PHY_RTL8211F) */
/* CODE_BLOCK_END */
