/*********************************************************************************************************************
* ACS APP Name : LWIP_GETH       APP Version: 4.0.4
*
* NOTE:
* This file is generated by ACS. Any manual modification done to this file will be lost when the code is regenerated.
*********************************************************************************************************************/

/**
 * @file lwipopts.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 *
 */
#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

#ifdef __cplusplus
extern "C" {
#endif

#define NO_SYS                              0
#define LWIP_SOCKET                         1
#define LWIP_NETCONN                        1
#define SYS_LIGHTWEIGHT_PROT                1
#define LWIP_TCPIP_CORE_LOCKING             0
#define LWIP_TCPIP_CORE_LOCKING_INPUT       0
#define SO_REUSE                            1
#define LWIP_COMPAT_SOCKETS                 0
#define LWIP_FCNTL                          1
#define LWIP_POSIX_SOCKETS_IO_NAMES         0

#define LWIP_HAVE_SLIPIF 0

#define DEFAULT_TCP_RECVMBOX_SIZE           48
#define DEFAULT_UDP_RECVMBOX_SIZE           32
#define DEFAULT_ACCEPTMBOX_SIZE             8
#define DEFAULT_RAW_RECVMBOX_SIZE           8
#define TCPIP_MBOX_SIZE                     96
#define MEMP_NUM_NETCONN                    12
#define MEMP_NUM_TCPIP_MSG_API              24
#define MEMP_NUM_TCPIP_MSG_INPKT            96
#define MEMP_NUM_SYS_TIMEOUT                (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 8)

/* FreeRTOS/lwIP thread sizing. Required when NO_SYS == 0.
 * Values are in stack words for the Infineon FreeRTOS port.
 */
#define LWIP_FREERTOS_THREAD_STACKSIZE_IS_STACKWORDS 1
#define TCPIP_THREAD_STACKSIZE             1024
#define TCPIP_THREAD_PRIO                  29
#define DEFAULT_THREAD_STACKSIZE           512
#define DEFAULT_THREAD_PRIO                2

#define LWIP_NETIF_HOSTNAME                 0
#define LWIP_NETIF_STATUS_CALLBACK          0
#define LWIP_NETIF_LINK_CALLBACK            1
#define ETH_PAD_SIZE                        2
#define LWIP_NETIF_TX_SINGLE_PBUF           1
#define TCP_LISTEN_BACKLOG                  1
#define LWIP_SO_RCVTIMEO                    1
#define LWIP_SO_LINGER                      1
#define MEM_SIZE                            16384
#define PBUF_POOL_SIZE                      96
#define PBUF_POOL_BUFSIZE                   512
#define MEMP_NUM_PBUF                       64
#define MEMP_NUM_RAW_PCB                    4
#define MEM_ALIGNMENT                       8

/* --------------------------------------------------------------------------
 * Memory-integrity instrumentation (DIAGNOSTIC).
 *
 * The gateway takes an intermittent MPU null-pointer trap on core 2 whose root
 * cause is a wild write originating in the lwIP/socket layer (the same
 * corruption also shows up as an occasional total TX freeze when it lands on a
 * pool/pcb/mbox instead of a task context). These checks make lwIP validate
 * every pool element and heap block on each alloc/free and assert at the exact
 * instant a canary or free-list is found corrupted, turning a far-away symptom
 * into a localized stop. LWIP_PLATFORM_ASSERT is wired to a real trap in
 * arch/cc.h. NOTE: this adds per-element padding (more RAM) and runtime cost -
 * dial MEMP_/MEM_*_CHECK back to 0 once the corruptor is found and fixed.
 * ------------------------------------------------------------------------ */
#define MEMP_OVERFLOW_CHECK                 2
#define MEMP_SANITY_CHECK                   1
#define MEM_OVERFLOW_CHECK                  2
#define MEM_SANITY_CHECK                    1

#define LWIP_UDP                            1
#define MEMP_NUM_UDP_PCB                    8

#define IP_SOF_BROADCAST                    1
#define IP_SOF_BROADCAST_RECV               1
#define SO_REUSE_RXTOALL                    1

#define LWIP_TCP                            1
/* DoIP is a single-client diagnostic server that the tester (FCD) opens and
 * closes repeatedly. Three PCBs (the previous value) is too tight: a freshly
 * arriving SYN, the active connection, and connections still draining in
 * FIN_WAIT/TIME_WAIT from the previous session all compete for the same pool.
 * When it is exhausted lwIP silently drops the incoming SYN (TCP has no
 * out-of-memory response), and the tester's connect() times out with "no TCP
 * listener answered". Give the pool real headroom. */
#define MEMP_NUM_TCP_PCB                    8
#define MEMP_NUM_TCP_PCB_LISTEN             3
#define MEMP_NUM_TCP_SEG                    32
#define TCP_MSS                             536
#define TCP_WND                             4288
#define TCP_SND_BUF                         4288
#define TCP_SND_QUEUELEN                    24
/* Keep TIME-WAIT short so a closed connection frees its PCB within a couple of
 * seconds on this controlled point-to-point lab link, instead of the 60 s lwIP
 * default that keeps reconnect pressure on the PCB pool. */
#define TCP_MSL                             3000
/* Reap a tester that vanished without a TCP FIN/RST (cable pull, PC sleep,
 * killed tool) at the TCP layer. Without this a half-open ESTABLISHED PCB
 * lingers forever while the lab DoIP application inactivity abort is disabled.
 * Keepalive timers are configured per accepted socket in TcpIpH.c. */
#define LWIP_TCP_KEEPALIVE                  1

#define LWIP_DHCP                           0

#define LWIP_ARP                            1
#define ARP_TABLE_SIZE                      10
#define MEMP_NUM_ARP_QUEUE                  10

#define LWIP_AUTOIP                         0

#define LWIP_ICMP                           1

#define LWIP_IGMP                           0

#define LWIP_DNS                            0

#define LWIP_SNMP                           0

#define IP_OPTIONS_ALLOWED                  0

#define IP_FRAG                             0

#define IP_REASSEMBLY                       0

#define LWIP_GETH_DEBUG_ENABLED             0

#define IP_DEFAULT_TTL                      255

#define CHECKSUM_GEN_IP                     0
#define CHECKSUM_GEN_UDP                    0
#define CHECKSUM_GEN_TCP                    0
#define CHECKSUM_GEN_ICMP                   0
#define CHECKSUM_CHECK_IP                   0
#define CHECKSUM_CHECK_UDP                  0
#define CHECKSUM_CHECK_TCP                  0

#define LWIP_RAW                            1

#ifdef __cplusplus
}
#endif

#endif /* __LWIPOPTS_H__ */

/* CODE_BLOCK_END */
