/*********************************************************************************************************************
* ACS APP Name : TIMER_STM       APP Version: 4.0.4
*
* NOTE:
* This file is generated by ACS. Any manual modification done to this file will be lost when the code is regenerated.
*********************************************************************************************************************/
/**
 * @file timer_stm_conf.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved. 
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 *
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "timer_stm.h"


/*======================================================================================================================
  = CONFIGURATION FOR TIMER_STM_0
  ====================================================================================================================*/
/***********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/
const TIMER_STM_CONF_t TIMER_STM_0_config =
{
  .stm                     = &MODULE_STM0,
  .frequency               = 100000000
};

TIMER_STM_t TIMER_STM_0 =
{
  .app_config              = &TIMER_STM_0_config,
  .ch =
  {
    [TIMER_STM_COMP_CHANNEL_0] =
    {
      .user_interval         = 10000,
      .auto_start            = TRUE,
      .config =
      {
        .comparator          = IfxStm_Comparator_0,
        .comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0,
        .compareSize         = IfxStm_ComparatorSize_32Bits,
        .ticks               = 0,
        .triggerPriority     = 0
      }
    },
    [TIMER_STM_COMP_CHANNEL_1] =
    {
      .user_interval         = 10000,
      .auto_start            = TRUE,
      .config =
      {
        .comparator          = IfxStm_Comparator_1,
        .comparatorInterrupt = IfxStm_ComparatorInterrupt_ir1,
        .compareSize         = IfxStm_ComparatorSize_32Bits,
        .ticks               = 0,
        .triggerPriority     = 0
      }
    }
  },
  .app_is_initialized      = FALSE
};

/* CODE_BLOCK_END */

