/**
 * @file timer_stm.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * TIMER_STM - Configures a STM timer peripheral to perform timer operations.
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved. 
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "timer_stm.h"

/**********************************************************************************************************************
 * API IMPLEMENTATION
 **********************************************************************************************************************/
/* Function to get the TIMER_STM APP version */

/* Function to initialize the STM timer */
TIMER_STM_STATUS_t TIMER_STM_Init(TIMER_STM_t *handle)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));
  TIMER_STM_STATUS_t status = TIMER_STM_STATUS_SUCCESS;

  if (!handle->app_is_initialized)
  {
    for (TIMER_STM_COMP_CHANNEL_t ch = TIMER_STM_COMP_CHANNEL_0; ch < (uint8)TIMER_STM_COMP_CHANNEL_MAX; ch++)
    {
      /* Set initial timer interval */
      status = TIMER_STM_SetTimeInterval(handle, ch, handle->ch[ch].user_interval);
      if (status == TIMER_STM_STATUS_SUCCESS)
      {
        /* If start after initialization is enabled */
        if (handle->ch[ch].auto_start)
        {
          /* Start timer */
          status = TIMER_STM_Start(handle, ch);
        }
      }
    }
    handle->app_is_initialized = TRUE;
  }

  return status;
}

/* Function to set time interval */
TIMER_STM_STATUS_t TIMER_STM_SetTimeInterval(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel, uint32 user_interval)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));
  TIMER_STM_STATUS_t status = TIMER_STM_STATUS_SUCCESS;

  /* Specified user interval is out of range, or specified compare channel is already active */
  if ((comp_channel >= TIMER_STM_COMP_CHANNEL_MAX) || (user_interval < 100))
  {
    status = TIMER_STM_STATUS_FAILURE;
  }
  else
  {
    uint32 fSTM = handle->app_config->frequency;                /* Store the STM clock frequency in fSTM variable */

    /* Decide the compare offset */
    uint32 compare_offset;
    for (compare_offset = 0; compare_offset <= 31; compare_offset++)
    {
      uint64 max_period = 0;                                    /* maximum period value */
      uint64 max_counter_value = 1;                             /* maximum STM counter value */

      /* Calculate the maximum value which is can be reached by counter */
      for (int i = 0; i < (32 + compare_offset); i++)
      {
        max_counter_value *= 2;                                 /* maximum counter value */
      }

      max_period = (uint64)max_counter_value / fSTM * (1000 * 1000);
                                                                /* Maximum obtainable period in the given offset value in us */
      if ((uint64)user_interval <= max_period)                  /* If the user interval is achievable */
      {
        break;                                                  /* Break with the required compreOffset value */
      }
    }
    handle->ch[comp_channel].config.ticks         = (uint32)(((fSTM * (uint64)user_interval / (1000 * 1000)) >> compare_offset));
    handle->ch[comp_channel].config.compareOffset = (IfxStm_ComparatorOffset)compare_offset;
  }

  return status;
}

/* Function to start the user timer */
TIMER_STM_STATUS_t TIMER_STM_Start(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));
  TIMER_STM_STATUS_t status = TIMER_STM_STATUS_SUCCESS;

  /* Specified user interval is out of range, or specified compare channel is already active */
  if ((comp_channel >= TIMER_STM_COMP_CHANNEL_MAX) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_0) && (handle->app_config->stm->ICR.B.CMP0EN == 1U)) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_1) && (handle->app_config->stm->ICR.B.CMP1EN == 1U)) ||
      (handle->ch[comp_channel].config.ticks == 0))
  {
    status = TIMER_STM_STATUS_FAILURE;
  }
  else
  {
    /* Initialize the STM with the user configuration */
    if (IfxStm_initCompare(handle->app_config->stm, &handle->ch[comp_channel].config))
    {
      /* Log the starting of the interval */
      handle->ch[comp_channel].start_time = (uint32)((double)(IfxStm_get(handle->app_config->stm) / IfxStm_getFrequency(handle->app_config->stm)) * 1000000);
    }
    else
    {
      status = TIMER_STM_STATUS_FAILURE;
    }
  }

  return status;
}

/* Function to update timer compare values to ensure accurate interrupts at the next interval */
TIMER_STM_STATUS_t TIMER_STM_SetNextInterval(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel)
{
  TIMER_STM_STATUS_t status = TIMER_STM_STATUS_SUCCESS;
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));

  /* Specified user interval is out of range, or specified compare channel is already active */
  if ((comp_channel >= TIMER_STM_COMP_CHANNEL_MAX) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_0) && (handle->app_config->stm->ICR.B.CMP0EN == 0U)) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_1) && (handle->app_config->stm->ICR.B.CMP1EN == 0U)) ||
      (handle->ch[comp_channel].config.ticks == 0))
  {
    status = TIMER_STM_STATUS_FAILURE;
  }
  else
  {
    IfxStm_increaseCompare(handle->app_config->stm, (IfxStm_Comparator)comp_channel, handle->ch[comp_channel].config.ticks);
  }

  return status;
}

/* Function to get the total time since the start of STM timer */
uint32 TIMER_STM_GetTotalTime(TIMER_STM_t *handle)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));

  /* Get the total time in microseconds since the start of the timer */
  return (uint32)((double)(IfxStm_get(handle->app_config->stm) / IfxStm_getFrequency(handle->app_config->stm)) * 1000000);
}

/* Function to get the time elapsed within the current user interval */
TIMER_STM_STATUS_t TIMER_STM_GetTime(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel)
{
  TIMER_STM_STATUS_t status = TIMER_STM_STATUS_SUCCESS;

  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));

  /* Check if the user timer is already active for specified compare channel */
  if ((comp_channel >= TIMER_STM_COMP_CHANNEL_MAX) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_0) && (handle->app_config->stm->ICR.B.CMP0EN == 0U)) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_1) && (handle->app_config->stm->ICR.B.CMP1EN == 0U)))
  {
    status = TIMER_STM_STATUS_FAILURE;
  }
  else
  {
    uint32 current_time = (uint32)((double)(IfxStm_get(handle->app_config->stm) / IfxStm_getFrequency(handle->app_config->stm)) * 1000000);
    handle->ch[comp_channel].user_time = current_time - handle->ch[comp_channel].start_time;
  }
  return status;
}

/* Function to stop the user timer */
void TIMER_STM_Stop(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));
  if (comp_channel < TIMER_STM_COMP_CHANNEL_MAX)
  {
    IfxStm_disableComparatorInterrupt(handle->app_config->stm, (IfxStm_Comparator)comp_channel);
  }
}

/* Function to returns the status of the timer */
boolean TIMER_STM_GetTimerStatus(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel)
{
  boolean status = FALSE;

  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));
  if (((comp_channel == TIMER_STM_COMP_CHANNEL_0) && (handle->app_config->stm->ICR.B.CMP0EN == 1U)) ||
      ((comp_channel == TIMER_STM_COMP_CHANNEL_1) && (handle->app_config->stm->ICR.B.CMP1EN == 1U)))
  {
    status = TRUE;
  }

  return status;
}

/* Function to restart the user timer */
TIMER_STM_STATUS_t TIMER_STM_Restart(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel, uint32 user_interval)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));
  TIMER_STM_STATUS_t status;

  IfxStm_disableComparatorInterrupt(handle->app_config->stm, (IfxStm_Comparator)comp_channel);

  status = TIMER_STM_SetTimeInterval(handle, comp_channel, user_interval);

  if (status == TIMER_STM_STATUS_SUCCESS)
  {
    status = TIMER_STM_Start(handle, comp_channel);
  }

  return status;
}

/* Function to clear the flag of compare match interrupt */
void TIMER_STM_ClearInterrupt(TIMER_STM_t *handle, TIMER_STM_COMP_CHANNEL_t comp_channel)
{
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));

  if (comp_channel < TIMER_STM_COMP_CHANNEL_MAX)
  {
    /* Clear the compare match interrupt flag */
    IfxStm_clearCompareFlag(handle->app_config->stm, (IfxStm_Comparator)comp_channel);
  }
}

/* CODE_BLOCK_END */
