/**
 * @file lwip_geth_lwip.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * Copyright (c) 2015-2025, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include <Cpu/Std/Ifx_Types.h>
#include <Cpu/Std/IfxCpu.h>
#include "IfxGeth_Eth.h"
#include "lwip_geth_lwip.h"
#include "lwipopts.h"
#include "lwip_geth_netif.h"
#include <string.h>
#include <stdarg.h>
#include "lwip_geth_conf.h"
#if (PHY_DEVICE_NAME == PHY_DP83825I)
#include "lwip_geth_private_phy_dp83825i.h"
#endif
#if (PHY_DEVICE_NAME == PHY_RTL8211F)
#include "lwip_geth_private_phy_rtl8211f.h"
#endif
#if LWIP_GETH_RTOS_ENABLED
#include <tcpip.h>
#include "FreeRTOS_core2.h"
#include "task_core2.h"
#include "portmacro_core2.h"
#endif

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
#define IFX_LWIP_TIMER_TICK_MS              (1U)    /* number of timer ticks per millisecond */

#define IFX_LWIP_ARP_PERIOD                 (ARP_TMR_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_TCP_FAST_PERIOD            (TCP_FAST_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_TCP_SLOW_PERIOD            (TCP_SLOW_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_DHCP_COARSE_PERIOD         (DHCP_COARSE_TIMER_MSECS / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_DHCP_FINE_PERIOD           (DHCP_FINE_TIMER_MSECS / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_LINK_PERIOD                (100U / IFX_LWIP_TIMER_TICK_MS) /* 100 ms */
#define IFX_LWIP_EMAC_BLOCK_TIME_FOR_INPUT  100
#define LWIP_GETH_OS_POLL_PERIOD_MS         (5U)
#define LWIP_GETH_RX_POLL_BUDGET            (64U)
#define LWIP_GETH_CREATE_RX_TASK            (1U)
#if LWIP_IPV4 && LWIP_ACD
#define IFX_LWIP_ACD_PERIOD                 (ACD_TMR_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#endif

#define IFX_LWIP_FLAG_ARP                   (1U << 1)
#define IFX_LWIP_FLAG_TCP_FAST              (1U << 2)
#define IFX_LWIP_FLAG_TCP_SLOW              (1U << 3)
#define IFX_LWIP_FLAG_LINK                  (1U << 4)
#define IFX_LWIP_FLAG_DHCP_COARSE           (1U << 5)
#define IFX_LWIP_FLAG_DHCP_FINE             (1U << 6)
#if LWIP_IPV4 && LWIP_ACD
#define IFX_LWIP_FLAG_ACD                   (1U << 7)
#endif

#define Ifx_Lwip_timerIncr(var, PERIOD, FLAG) \
        {                                             \
    var += 1;                                   \
    if (var >= PERIOD)                          \
    {                                           \
        var         = 0;                          \
        timerFlags |= FLAG;                       \
    }                                           \
        }

/***********************************************************************************************************************
 * PRIVATE VARIABLES
 **********************************************************************************************************************/
volatile uint32 g_TickCount_1ms;
Ifx_Lwip        g_Lwip;
IfxGeth_Eth     g_IfxGeth;
uint32          isrTxCount = 0;
uint32          isrRxCount = 0;
IFX_ALIGN(32) AURIX_ETH_DMA_NC uint8 channel0TxBuffer1[IFXGETH_MAX_TX_DESCRIPTORS][IFXGETH_MAX_TX_BUFFER_SIZE];
IFX_ALIGN(32) AURIX_ETH_DMA_NC uint8 channel0RxBuffer1[IFXGETH_MAX_RX_DESCRIPTORS][IFXGETH_MAX_RX_BUFFER_SIZE];
volatile uint32 g_LwipEthTxDescriptorCount = (uint32)IFXGETH_MAX_TX_DESCRIPTORS;
volatile uint32 g_LwipEthRxDescriptorCount = (uint32)IFXGETH_MAX_RX_DESCRIPTORS;
volatile uint32 g_LwipEthTxBufferBytes = (uint32)sizeof(channel0TxBuffer1);
volatile uint32 g_LwipEthRxBufferBytes = (uint32)sizeof(channel0RxBuffer1);
volatile uint8  g_LwipNetifReady;
volatile uint8  g_LwipNetifFlagsAfterSet;
volatile uint8  g_LwipNetifFlagsCurrent;
volatile uint8  g_LwipNetifLinkUp;
volatile uint8  g_LwipInitDone;
volatile uint32 g_LwipTcpipInitDoneCounter;
volatile uint32 g_LwipRxTaskCreateResult;
volatile uint32 g_LwipLinkTaskCreateResult;
volatile uint32 g_LwipLinkStatusCallbackFailCounter;
volatile uint32 g_LwipRxIsrBeforeTaskCounter;
volatile uint32 g_LwipGratuitousArpCounter;
volatile uint32 g_LwipSoftwareTimerTickCounter;
volatile uint32 g_LwipRxPollLoopCounter;
volatile uint32 g_LwipRxPollPacketCounter;
volatile uint32 g_LwipRxPollBudgetHitCounter;
volatile uint32 g_LwipForcedMacConfigCounter;
volatile uint32 g_LwipLinkTaskSkippedForForceUp;

/***********************************************************************************************************************
 * FUNCTION IMPLEMENTATIONS
 **********************************************************************************************************************/
void lwip_geth_UpdateTickCount(void);

/** \brief Timer interrupt callback */
void lwip_geth_Lwip_onTimerTick(void)
{
    Ifx_Lwip *lwip       = &g_Lwip;
    uint16    timerFlags = lwip->timerFlags;

    Ifx_Lwip_timerIncr(lwip->timer.arp, IFX_LWIP_ARP_PERIOD, IFX_LWIP_FLAG_ARP);

    Ifx_Lwip_timerIncr(lwip->timer.tcp_fast, IFX_LWIP_TCP_FAST_PERIOD, IFX_LWIP_FLAG_TCP_FAST);
    Ifx_Lwip_timerIncr(lwip->timer.tcp_slow, IFX_LWIP_TCP_SLOW_PERIOD, IFX_LWIP_FLAG_TCP_SLOW);

#if LWIP_DHCP
    Ifx_Lwip_timerIncr(lwip->timer.dhcp_coarse, IFX_LWIP_DHCP_COARSE_PERIOD, IFX_LWIP_FLAG_DHCP_COARSE);
    Ifx_Lwip_timerIncr(lwip->timer.dhcp_fine, IFX_LWIP_DHCP_FINE_PERIOD, IFX_LWIP_FLAG_DHCP_FINE);
#endif

    Ifx_Lwip_timerIncr(lwip->timer.link, IFX_LWIP_LINK_PERIOD, IFX_LWIP_FLAG_LINK);
#if LWIP_IPV4 && LWIP_ACD
    Ifx_Lwip_timerIncr(lwip->timer.acd, IFX_LWIP_ACD_PERIOD, IFX_LWIP_FLAG_ACD);
#endif

    lwip->timerFlags = timerFlags;
}

static void lwip_geth_Lwip_advancePolledTime(uint8 elapsedMs)
{
    uint8 tick;

    for (tick = 0u; tick < elapsedMs; tick++)
    {
        lwip_geth_Lwip_onTimerTick();
        lwip_geth_UpdateTickCount();
        g_LwipSoftwareTimerTickCounter++;
    }
}

static void lwip_geth_Lwip_configureForcedMacMode(IfxGeth_Eth *ethernetif)
{
    if (ethernetif == NULL_PTR)
    {
        return;
    }

    IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
    IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
    g_LwipForcedMacConfigCounter++;
}

static void lwip_geth_Lwip_applyLinkStatus(void)
{
    Ifx_GETH_MAC_PHYIF_CONTROL_STATUS ctrl_status;
    IfxGeth_Eth *ethernetif = g_Lwip.netif.state;

    if (ethernetif == NULL_PTR)
    {
        return;
    }

#if (PHY_DEVICE_NAME == PHY_DP83825I)
    lwip_geth_private_Phy_Dp83825i_mainFunction_100ms();
    ctrl_status.U = lwip_geth_private_Phy_Dp83825i_link_status();
#else
    ctrl_status.U = GETH_MAC_PHYIF_CONTROL_STATUS.U;
#endif
    g_LwipNetifLinkUp = (uint8)ctrl_status.B.LNKSTS;

    if (ctrl_status.B.LNKSTS == 0u)
    {
#if LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
        /* Bring-up fallback: the KIT_A2G_TC375_LITE RJ45 LED may show link while
         * the PHY status helper still reports down. Keep lwIP up so ARP/ping/UDP
         * can be validated. RMII still needs a deterministic MAC mode when the
         * PHY helper reports down, otherwise Tx DMA can hold descriptors forever.
         */
        lwip_geth_Lwip_configureForcedMacMode(ethernetif);
        lwip_geth_Lwip_forceNetifUp();
        return;
#else
        netif_set_link_down(&g_Lwip.netif);
        return;
#endif
    }

    if (ctrl_status.B.LNKMOD == 1u)
    {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
    }
    else
    {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
    }

    if (ctrl_status.B.LNKSPEED == 0u)
    {
        IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
    }
    else
    {
        IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
    }

    lwip_geth_Lwip_forceNetifUp();
}

#if LWIP_GETH_RTOS_ENABLED && !LWIP_TCPIP_CORE_LOCKING
static void lwip_geth_Lwip_applyLinkStatusCb(void *ctx)
{
    (void)ctx;
    lwip_geth_Lwip_applyLinkStatus();
}
#endif

/** \brief Polling the timer event flags */
void lwip_geth_Lwip_pollTimerFlags(void)
{
#if LWIP_GETH_RTOS_ENABLED
    /* With NO_SYS == 0, tcpip_thread already owns and runs the lwIP core timers
     * (tcp_tmr, etharp_tmr, ...) via sys_check_timeouts(), and PHY link status is
     * polled by the dedicated lwip_geth_LinkStatus task. Running those same timer
     * state machines again here - from the cyclic 5 ms OS task, while
     * LOCK_TCPIP_CORE() is a no-op because LWIP_TCPIP_CORE_LOCKING is disabled -
     * races tcpip_thread on tcp_active_pcbs and the ARP table. That corruption is
     * a prime suspect for the intermittent failures this stack shows: a lost
     * listen PCB (no SYN-ACK -> tester TCP connect times out), a corrupted ARP
     * table (UDP vehicle-id and TCP both go silent), or a use-after-free
     * (unintended watchdog reset). So this poll does nothing in the RTOS build;
     * it stays active only for the NO_SYS (raw-API) configuration, e.g. the FBL. */
    return;
#else
    Ifx_Lwip *lwip = &g_Lwip;
    uint16    timerFlags;
    boolean   interruptState;

    /* lwIP timer flags are generated here because this integration calls
     * pollTimerFlags() from the 5 ms OS task instead of a 1 ms ISR.
     */
    lwip_geth_Lwip_advancePolledTime(LWIP_GETH_OS_POLL_PERIOD_MS);

    /* disable interrupts */
    interruptState = IfxCpu_disableInterrupts();

    timerFlags       = lwip->timerFlags;
    lwip->timerFlags = 0;

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);

#if LWIP_TCPIP_CORE_LOCKING
    LOCK_TCPIP_CORE();
#endif

#if LWIP_DHCP
    if (timerFlags & IFX_LWIP_FLAG_DHCP_COARSE)
    {
        /* only if we have a link we will check the dhcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
        {
            dhcp_coarse_tmr();
        }
    }

    if (timerFlags & IFX_LWIP_FLAG_DHCP_FINE)
    {
        /* only if we have a link we will check the dhcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
        {
            dhcp_fine_tmr();
        }
    }
#endif

    if (timerFlags & IFX_LWIP_FLAG_TCP_FAST)
    {
        /* only if we have a link we will check the tcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
        {
            tcp_fasttmr();
        }
    }

    if (timerFlags & IFX_LWIP_FLAG_TCP_SLOW)
    {
        /* only if we have a link we will check the tcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
        {
            tcp_slowtmr();
        }
    }

    if (timerFlags & IFX_LWIP_FLAG_ARP)
    {
        /* only if we have a link we will check the arp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
        {
            etharp_tmr();
            (void)etharp_gratuitous(&g_Lwip.netif);
            g_LwipGratuitousArpCounter++;
        }
    }

    if (timerFlags & IFX_LWIP_FLAG_LINK)
    {
        lwip_geth_Lwip_applyLinkStatus();
    }

#if LWIP_IPV4 && LWIP_ACD
    if (timerFlags & IFX_LWIP_FLAG_ACD)
    {
        /* only if we have a link we will check the arp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
        {
            acd_tmr();
        }
    }
#endif

#if LWIP_TCPIP_CORE_LOCKING
    UNLOCK_TCPIP_CORE();
#endif
#endif /* LWIP_GETH_RTOS_ENABLED */
}

/** \brief Polling the ETH receive event flags */
void lwip_geth_Lwip_pollReceiveFlags(void)
{
    uint8 processed;
    uint8 budget = LWIP_GETH_RX_POLL_BUDGET;

#if LWIP_GETH_CREATE_RX_TASK
    if (g_Lwip.EthRxTask != NULL_PTR)
    {
        return;
    }
#endif

    g_LwipRxPollLoopCounter++;

    do
    {
        processed = lwip_geth_netif_input_once(&g_Lwip.netif);

        if (processed != 0u)
        {
            g_LwipRxPollPacketCounter++;
        }

        if (budget > 0u)
        {
            budget--;
        }
    } while ((processed != 0u) && (budget > 0u));

    if ((processed != 0u) && (budget == 0u))
    {
        g_LwipRxPollBudgetHitCounter++;
    }
}


uint8 lwip_geth_Lwip_isNetifReady(void)
{
    g_LwipNetifFlagsCurrent = g_Lwip.netif.flags;
    return g_LwipNetifReady;
}

void lwip_geth_Lwip_forceNetifUp(void)
{
    netif_set_default(&g_Lwip.netif);

#if LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
    /* Bring-up fallback. Some TC375/DP83825I lab configurations report PHY-link
     * incorrectly while the RJ45 LED and switch link are active. Force the lwIP
     * admin/link flags so sockets can open and ARP/UDP can be validated.
     */
    lwip_geth_Lwip_configureForcedMacMode((IfxGeth_Eth *)g_Lwip.netif.state);
    g_Lwip.netif.flags |= (NETIF_FLAG_UP | NETIF_FLAG_LINK_UP);
#else
    netif_set_up(&g_Lwip.netif);
    netif_set_link_up(&g_Lwip.netif);
#endif

    g_LwipNetifFlagsAfterSet = g_Lwip.netif.flags;
    g_LwipNetifFlagsCurrent = g_Lwip.netif.flags;
    g_LwipNetifLinkUp = ((g_Lwip.netif.flags & NETIF_FLAG_LINK_UP) != 0u) ? 1u : 0u;
    g_LwipNetifReady = 1u;
}

#if LWIP_GETH_RTOS_ENABLED
void lwip_geth_Lwip_WaitForInput( void )
{
    /* Just wait until we are signled from an ISR that data is available, or
     * we simply time out.
     */
    (void)ulTaskNotifyTake_core2(0, 100);
}
#endif

#if LWIP_GETH_RTOS_ENABLED
void lwip_geth_LinkStatus(void *pvParameter)
{
    (void)pvParameter;

    for (;;)
    {
#if LWIP_TCPIP_CORE_LOCKING
        LOCK_TCPIP_CORE();
        lwip_geth_Lwip_applyLinkStatus();
        UNLOCK_TCPIP_CORE();
#else
        if (tcpip_try_callback(lwip_geth_Lwip_applyLinkStatusCb, NULL_PTR) != ERR_OK)
        {
            g_LwipLinkStatusCallbackFailCounter++;
        }
#endif
        vTaskDelay_core2(pdMS_TO_TICKS_core2(100u));
    }
}
#endif

#if LWIP_NETIF_EXT_STATUS_CALLBACK
static netif_ext_callback_t g_extCallback;

void netif_state_changed(struct netif* netif, netif_nsc_reason_t reason, const netif_ext_callback_args_t* args)
{
    if (reason | LWIP_NSC_IPV4_ADDRESS_CHANGED)
    {
        LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE | LWIP_DBG_STATE,
                ("netif: new ip address assigned: %"U16_F".%"U16_F".%"U16_F".%"U16_F"\n",
                        ip4_addr1_16(netif_ip4_addr(netif)),
                        ip4_addr2_16(netif_ip4_addr(netif)),
                        ip4_addr3_16(netif_ip4_addr(netif)),
                        ip4_addr4_16(netif_ip4_addr(netif))));
    }
}
#endif

/** \brief LWIP initialization function */
void lwip_geth_Lwip_init(void *arg)
{
    (void)arg;
    ip_addr_t default_ipaddr, default_netmask, default_gw;
#if LWIP_DHCP
    IP4_ADDR(&default_gw, 0, 0, 0, 0);
    IP4_ADDR(&default_ipaddr, 0, 0, 0, 0);
    IP4_ADDR(&default_netmask, 0, 0, 0, 0);
#else
    IP4_ADDR(&default_gw, GW_ADDR0,GW_ADDR1, GW_ADDR2,GW_ADDR3);
    IP4_ADDR(&default_ipaddr, IP_ADDR0, IP_ADDR1, IP_ADDR2, IP_ADDR3);
    IP4_ADDR(&default_netmask, NETMASK_ADDR0, NETMASK_ADDR1, NETMASK_ADDR2, NETMASK_ADDR3);
#endif

    LWIP_DEBUGF(LWIP_GETH_DEBUG, ("Lwip_geth_lwip_init start!\n"));

    /** - initialise LWIP (lwip_init()) */
#if !LWIP_GETH_RTOS_ENABLED
    lwip_init();
#endif
    /** - initialise and add a \ref netif */
    (void)memcpy(&g_Lwip.eth_addr,
                 lwip_geth_handle->app_config->geth_lld_config->mac.macAddress,
                 sizeof(g_Lwip.eth_addr));

#if LWIP_GETH_RTOS_ENABLED
    if (netif_add(&g_Lwip.netif, &default_ipaddr, &default_netmask, &default_gw,
            (void *)0, lwip_geth_netif_init, tcpip_input) == NULL_PTR)
    {
        LWIP_ASSERT("netif_add failed", 0);
        return;
    }
#if LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
    /* In forced-link bring-up mode the netif is kept up and the MAC is forced
     * to RMII 100M/full-duplex. Do not create the 100 ms link task: it posts a
     * tcpip callback every cycle and can force a scheduler yield from inside
     * xQueueGenericSend() before any useful link-state change exists.
     */
    g_LwipLinkTaskSkippedForForceUp = 1u;
    g_LwipLinkTaskCreateResult = 0xFFFF0001u;
#else
    /* Create a Task for checking the Link */
    g_LwipLinkTaskCreateResult = (uint32)xTaskCreate_core2(lwip_geth_LinkStatus,"Eth Link Stat",LWIP_GETH_PHY_TASK_STACK_SIZE,NULL,LWIP_GETH_PHY_TASK_PRIO,NULL);
#endif
#if LWIP_GETH_CREATE_RX_TASK
    /* Task is woken up by an Rx Ethernet Event using Binary Semaphore */
    g_LwipRxTaskCreateResult = (uint32)xTaskCreate_core2(lwip_geth_netif_input,"Eth RX",LWIP_GETH_TASK_STACK_SIZE,&g_Lwip.netif,LWIP_GETH_TASK_PRIO_RX,&g_Lwip.EthRxTask);
#else
    g_Lwip.EthRxTask = NULL_PTR;
    g_LwipRxTaskCreateResult = 0u;
#endif
#else
    if (netif_add(&g_Lwip.netif, &default_ipaddr, &default_netmask, &default_gw,
            (void *)0, lwip_geth_netif_init, ethernet_input) == NULL_PTR)
    {
        LWIP_ASSERT("netif_add failed", 0);
        return;
    }
#endif

    netif_set_default(&g_Lwip.netif);

#if LWIP_NETIF_STATUS_CALLBACK == 1 /* If callback enabled */
    /* Initialize interface status change callback */
    netif_set_status_callback(&g_Lwip.netif, LWIP_GETH_NETIF_STATUS_CB_FUNCTION);
#endif
    lwip_geth_Lwip_forceNetifUp();
#if !LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
    lwip_geth_Lwip_applyLinkStatus();
#endif

#if LWIP_NETIF_HOSTNAME
    g_Lwip.netif.hostname = lwip_geth_handle->app_config->hostname;
#endif

#if LWIP_DHCP
    /** - assign \ref dhcp to \ref netif */
    dhcp_set_struct(&g_Lwip.netif, &g_Lwip.dhcp);

    /* we start the dhcp always here also when we don't have a link here */
    dhcp_start(&g_Lwip.netif);
#endif

#if LWIP_NETIF_EXT_STATUS_CALLBACK
    netif_add_ext_callback(&g_extCallback, netif_state_changed);
#endif
    LWIP_DEBUGF(LWIP_GETH_DEBUG, ("Lwip_geth_lwip_init end!\n"));
    g_LwipInitDone = 1u;
    g_LwipTcpipInitDoneCounter++;
}

/** Returns the current time in milliseconds, may be the same as sys_jiffies or at least based on it. */
#if !LWIP_GETH_RTOS_ENABLED
inline u32_t sys_now(void)
{
    return g_TickCount_1ms;
}
#endif

/** Increase the system time in milliseconds. */
void lwip_geth_UpdateTickCount(void)
{
    g_TickCount_1ms++;
}

/** This interrupt is raised by the ethernet tx. The initialization is done by IfxGeth_Eth_init(). */
IFX_INTERRUPT(ISR_Geth_Tx, CPU_WHICH_SERVICE_ETHERNET, ISR_PRIORITY_GETH_TX)
{
    isrTxCount++;
}

/** This interrupt is raised by the ethernet rx. The initialization is done by IfxGeth_Eth_init(). */
#if LWIP_GETH_IS_ISR
IFX_INTERRUPT(ISR_Geth_Rx, CPU_WHICH_SERVICE_ETHERNET, ISR_PRIORITY_GETH_RX)
{
#if !LWIP_GETH_RTOS_ENABLED
    lwip_geth_netif_input(&g_Lwip.netif);
#else
    if (g_Lwip.EthRxTask != NULL_PTR)
    {
        portBASE_TYPE_core2 xHigherPriorityTaskWoken = pdFALSE_core2;
        vTaskNotifyGiveFromISR_core2( g_Lwip.EthRxTask, &xHigherPriorityTaskWoken );

        /* If a task was woken by either a frame being received then we may need to
         * switch to another task.  If the unblocked task was of higher priority then
         * the interrupted task it will then execute immediately that the ISR
         * completes.
         */
        portYIELD_FROM_ISR_core2(xHigherPriorityTaskWoken);
    }
    else
    {
        g_LwipRxIsrBeforeTaskCounter++;
    }
#endif
    isrRxCount++;
}
#endif

/* CODE_BLOCK_END */
