/**********************************************************************************************************************
 * \file SafetyKit_SSW_00_LBIST.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SafetyKit_SSW.h"
#include "SafetyKit_SSW_00_LBIST.h"
#include "SafetyKit_Cfg.h"
#include "SafetyKit_Main.h"
#include "McuSm.h"
#include "IfxScuLbist.h"
#include "Ifx_Ssw_Infra.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*---------------------------------------------------Enumerations----------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------Exported Variables/Constants---------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
boolean IfxScuLbist_isTerminatedProperly(void);
boolean IfxScuLbist_isTerminatedPORST(void);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/*
 * This function is for LBIST execution and result check
 * SM:LBIST_CFG
 * SM:LBIST_RESULT
 * */
void safetyKitSswLbist(void)
{
    boolean lbistHasPassed;

    if ((Ifx_Ssw_isColdPoweronReset()) &&
            (FALSE == IfxScuLbist_isTerminatedPORST()) &&
            (FALSE == IfxScuLbist_isTerminatedProperly()))
    {
        McuSm_SswStatusData.lbistRuns = 0u;
        McuSm_SswStatusData.lbistAppSwReq = 0u;
        McuSm_SswStatusData.mcuFwcheckRuns = 0u;
    }

    /* check if LBIST was terminated by a PORST */
    if (FALSE == IfxScuLbist_isTerminatedPORST())
    {
        /* Check if LBIST was already executed, either within firmware of within application SSW */
        if (IfxScuLbist_isDone())
        {
            if (McuSm_SswStatusData.lbistRuns < 0xFFu)
            {
                McuSm_SswStatusData.lbistRuns++;
            }
            else
            {
                /* Saturated retained counter. */
            }

            if (TRUE == IfxScuLbist_isTerminatedProperly())
            {
                /* TC375DP/TC37x uses the derivative default signature provided by the iLLD configuration. */
                lbistHasPassed = IfxScuLbist_evaluateResult(IfxScuLbist_defaultConfig.signature);
            }
            else
            {
                lbistHasPassed = FALSE;
            }

            uint16 password = IfxScuWdt_getSafetyWatchdogPasswordInline();

            IfxScuWdt_clearSafetyEndinitInline(password);

            /* Reset LBIST module and wait till reset is done */
            MODULE_SCU.LBISTCTRL0.B.LBISTRES = 1;

            IfxScuWdt_setSafetyEndinitInline(password);

            uint8 timeout = 0xFF;

            while (MODULE_SCU.LBISTCTRL0.B.LBISTDONE == 1U && timeout > 0)
            {
                timeout--;
            }

            if (lbistHasPassed)
            {
                g_SafetyKitStatus.sswStatus.lbistStatus = passed;
                McuSm_SswStatusData.lbistAppSwReq = 0u;
            }
            else
            {
                g_SafetyKitStatus.sswStatus.lbistStatus = failed;

                if (McuSm_SswStatusData.lbistAppSwReq < SAFETKIT_LBIST_MAX_RUNS)
                {
                    /* SM:LBIST_CFG */
                    safetyKitTriggerLbist();
                }
                else
                {
                    while(1)
                    {
                        __debug();
                    }
                }
            }

            McuSm_SswStatusData.lbistStatus = (uint8)g_SafetyKitStatus.sswStatus.lbistStatus;
        }
        else
        {
#if SAFETYKIT_CFG_SSW_ENABLE_LBIST_APPSW
            if (McuSm_SswStatusData.lbistAppSwReq < SAFETKIT_LBIST_MAX_RUNS)
            {
                /* SM:LBIST_CFG */
                safetyKitTriggerLbist();
            }
            else
            {
                g_SafetyKitStatus.sswStatus.lbistStatus = failed;
                McuSm_SswStatusData.lbistStatus = (uint8)failed;
            }
#endif
        }
    }
    else
    {
#if SAFETYKIT_CFG_SSW_ENABLE_LBIST_APPSW
        if (McuSm_SswStatusData.lbistAppSwReq < SAFETKIT_LBIST_MAX_RUNS)
        {
            /* Retry LBIST when the previous LBIST reset was interrupted by PORST. */
            safetyKitTriggerLbist();
        }
        else
        {
            g_SafetyKitStatus.sswStatus.lbistStatus = failed;
            McuSm_SswStatusData.lbistStatus = (uint8)failed;
        }
#else
        g_SafetyKitStatus.sswStatus.lbistStatus = failed;
        McuSm_SswStatusData.lbistStatus = (uint8)failed;
#endif
    }
}

/*
 * The RSTSTAT.LBPORST status bit indicates if LBIST execution was terminated earlier due to a PORST assertion
 * */
boolean IfxScuLbist_isTerminatedPORST(void)
{
    return (boolean)MODULE_SCU.RSTSTAT.B.LBPORST;
}

/*
 * The RSTSTAT.LBTERM status bit indicates if LBIST execution was properly terminated
 * */
boolean IfxScuLbist_isTerminatedProperly(void)
{
    return (boolean)MODULE_SCU.RSTSTAT.B.LBTERM;
}
/*
 * SM:LBIST_CFG
 * */
void safetyKitTriggerLbist(void)
{
    McuSm_SswStatusData.lbistAppSwReq++;
    McuSm_SswStatusData.rstStat = MODULE_SCU.RSTSTAT.U;

    /* Clear COLD PORST reason to preserve the data on the SCR XRAM */
    IfxScuRcu_clearColdResetStatus();

    McuSm_SaveRetainedStateToScr();

    /* Trigger LBIST with the derivative default configuration for TC375DP/TC37x. */
    IfxScuLbist_triggerInline(&IfxScuLbist_defaultConfig);

    while(1)
    {
        __nop(); /* After triggering LBIST wait for warm reset */
    }
}
