/**********************************************************************************************************************
 * \file SafetyKit_SSW_02_MCU_FW_CHECK.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SafetyKit_SSW.h"
#include "SafetyKit_SSW_02_MCU_FW_CHECK.h"
#include "SafetyKit_SSW_02_MCU_FW_CHECK_tables_TC375DP.h"
#include "SafetyKit_Main.h"
#include "IfxMtu.h"
#include "IfxMtu_cfg.h"
#include "IfxSmu.h"
#include "IfxDmu_Reg.h"
#include "McuSm.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SAFETYKIT_FWCHECK_SSH_ECCD_SINGLE_BIT_ECC_MASK      ((uint32)0x00000003u)
#define SAFETYKIT_FWCHECK_SSH_ERRINFO_SINGLE_BIT_ECC_MASK   ((uint32)0x00000001u)
#define SAFETYKIT_FWCHECK_SMU_AG0_2_SINGLE_BIT_ECC_MASK     ((uint32)0x00001240u)
#define SAFETYKIT_FWCHECK_SMU_AG6_SINGLE_BIT_ECC_MASK       ((uint32)0x00092400u)
#define SAFETYKIT_FWCHECK_SMU_AG7_SINGLE_BIT_ECC_MASK       ((uint32)0x01400001u)
#define SAFETYKIT_FWCHECK_SMU_AG10_CORRECTABLE_MASK         ((uint32)0x00100000u)
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile Ifx_SMU_AG g_SafetyKitSmuAlarmRegStatus[IFXSMU_NUM_ALARM_GROUPS];
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
boolean safetyKitFwCheckSmuStmemLclcon(const FwCheckStruct *fwCheckTablSMU, const int structSize, const SafetyKitResetType resetType, FwCheckVerificationStruct *fwCheckVerification);
SafetyKitResetType safetyKitFwCheckGetStandbyRegisterProfile(const SafetyKitResetType resetType);
boolean safetyKitFwCheckValidateStandbyStmem(FwCheckVerificationStruct *fwCheckVerification);
uint32 safetyKitFwCheckGetSmuSingleBitEccMask(FwChectRegUnderTest regUnderTest);
uint32 safetyKitFwCheckGetSmuEnabledAlarmMask(FwChectRegUnderTest regUnderTest);
IfxMtu_MbistSel safetyKitFwCheckSsh(const SafetyKitResetType resetType);
IfxMtu_MbistSel safetyKitFwCheckCheckSshRegisters(const MemoryTestedStruct* sshTable, int tableSize);
IfxMtu_MbistSel safetyKitFwCheckCheckStandbySshRegisters(const MemoryTestedStruct* sshTable, int tableSize);
IfxMtu_MbistSel safetyKitFwCheckCheckLbistSshRegisters(const MemoryTestedStruct* sshTable, int tableSize);
void safetyKitFwCheckGetExpectedSshValues(const MemoryTestedStruct *sshEntry, uint16 *expectedValueECCD,
        uint16 *expectedValueFAULTSTS, uint16 *expectedValueERRINFO);
boolean safetyKitFwCheckIsInitializedRamSshState(const MemoryTestedStruct *sshEntry, uint32 actualEccd,
        uint32 actualFaultsts, uint32 actualErrinfo);
boolean safetyKitFwCheckIsSingleBitEccOnly(uint32 actualEccd, uint32 actualFaultsts, uint32 actualErrinfo,
        uint32 expectedEccd, uint32 expectedFaultsts, uint32 expectedErrinfo);
boolean safetyKitFwCheckIsStandbyWakeCleanSshState(IfxMtu_MbistSel mbistSel, uint32 actualEccd,
        uint32 actualFaultsts, uint32 actualErrinfo, uint32 expectedEccd, uint32 expectedFaultsts,
        uint32 expectedErrinfo);
void safetyKitFwCheckSetSshDiagnostics(IfxMtu_MbistSel mbistSel, uint32 actualEccd, uint32 actualFaultsts,
        uint32 actualErrinfo, uint32 expectedEccd, uint32 expectedFaultsts, uint32 expectedErrinfo);
void safetyKitFwCheckSetRegisterDiagnostics(uint32 regUnderTest, uint32 actual, uint32 expected,
        uint32 mask, uint32 resetType);
boolean safetyKitFwCheckEvaluateRamInit(uint16 memoryMask);
boolean safetyKitFwCheckEvaluateLmuInit(uint16 memoryMask);
void safetyKitFwCheckClearSSH(const SafetyKitResetType resetType);
void safetyKitFwCheckClearSmuAlarms(const FwCheckStruct *fwCheckTable, const int tableSize);
void clearFaultStatusAndECCDetectionFSIRAM(void);
void safetyKitFwCheckRetriggerCheck(const SafetyKitResetType resetType);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/*
 * SM:MCU_FW_CHECK
 * */
void safetyKitSswMcuFwCheck(void)
{
    boolean smuCheckPassed;
    boolean stmemCheckPassed;
    boolean lclconCheckPassed;
    boolean sshCheckPassed;
    SafetyKitResetType smuResetType;
    SafetyKitResetType resetTypeRegisterProfile;

    McuSm_SswStatusData.mcuFwcheckRuns++;
    McuSm_SafetyKitFwCheckLastSshFail = (uint32)IfxMtu_MbistSel_none;
    McuSm_SafetyKitFwCheckResultMask = 0u;
    McuSm_SafetyKitFwCheckSshActualEccd = 0u;
    McuSm_SafetyKitFwCheckSshActualFaultsts = 0u;
    McuSm_SafetyKitFwCheckSshActualErrinfo = 0u;
    McuSm_SafetyKitFwCheckSshExpectedEccd = 0u;
    McuSm_SafetyKitFwCheckSshExpectedFaultsts = 0u;
    McuSm_SafetyKitFwCheckSshExpectedErrinfo = 0u;
    McuSm_SafetyKitFwCheckLastRegFail = MCUSM_FW_CHECK_REG_FAIL_NONE;
    McuSm_SafetyKitFwCheckRegActual = 0u;
    McuSm_SafetyKitFwCheckRegExpected = 0u;
    McuSm_SafetyKitFwCheckRegMask = 0u;
    /* SMU diagnostic arrays live only in the newer McuSm instrumentation branch. */
    smuResetType = g_SafetyKitStatus.resetCode.resetType;
    resetTypeRegisterProfile = safetyKitFwCheckGetStandbyRegisterProfile(g_SafetyKitStatus.resetCode.resetType);
    McuSm_SafetyKitFwCheckRegResetType = (uint32)resetTypeRegisterProfile;

    /* Enable MTU module if not yet enabled */
    boolean mtuWasEnabled = IfxMtu_isModuleEnabled();
    if (mtuWasEnabled == FALSE)
    {
        /* Enable MTU module */
        IfxMtu_enableModule();
    }
    else
    {
        /* Do nothing. */
    }
    /* Take a snapshot of the SMU alarm registers before executing the FW check */
    for(uint8 alarmReg = 0; alarmReg < IFXSMU_NUM_ALARM_GROUPS; alarmReg++)
    {
        g_SafetyKitSmuAlarmRegStatus[alarmReg].U = MODULE_SMU.AG[alarmReg].U;
    }

    /* Read SMU alarm register values and compare with expected ones(listed in Appendix A of the Safety Manual).
     * Note: depending on the device and reset type different register values are expected. */
    smuCheckPassed = safetyKitFwCheckSmuStmemLclcon(fwCheckSMUTC375DP, fwCheckSMUTC375DPSize,
            smuResetType, fwCheckVerificationSMU);
    /* Read SCU_STMEM register values and compare with expected ones(listed in Appendix A of the Safety Manual). */
    stmemCheckPassed = safetyKitFwCheckSmuStmemLclcon(fwCheckSTMEMTC375DP, fwCheckSTMEMTC375DPSize,
            resetTypeRegisterProfile, fwCheckVerificationSTMEM);
    if ((stmemCheckPassed == FALSE) && (g_SafetyKitStatus.wakeupFromStandby != FALSE))
    {
        stmemCheckPassed = safetyKitFwCheckValidateStandbyStmem(fwCheckVerificationSTMEM);
    }
    /* LCLCON keeps the raw reset type; observed standby wake leaves it in the PORST-class profile. */
    lclconCheckPassed = safetyKitFwCheckSmuStmemLclcon(fwCheckLCLCONTC375DP, fwCheckLCLCONTC375DPSize,
            g_SafetyKitStatus.resetCode.resetType, fwCheckVerificationLCLCON);
    /* Read SSH register values of all RAM and compare with expected ones(listed in Appendix A of the Safety Manual). */
    sshCheckPassed = (IfxMtu_MbistSel_none == safetyKitFwCheckSsh(g_SafetyKitStatus.resetCode.resetType)) ? TRUE : FALSE;

    if (smuCheckPassed == FALSE)
    {
        McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_SMU_FAILED;
    }
    if (stmemCheckPassed == FALSE)
    {
        McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_STMEM_FAILED;
    }
    if (lclconCheckPassed == FALSE)
    {
        McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_LCLCON_FAILED;
    }
    if (sshCheckPassed == FALSE)
    {
        McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_SSH_FAILED;
    }

    if ((smuCheckPassed != FALSE) &&
            (stmemCheckPassed != FALSE) &&
            (lclconCheckPassed != FALSE) &&
            (sshCheckPassed != FALSE))
    {
        /* If all four checks have passed set FW check status variable to "passed" */
        g_SafetyKitStatus.sswStatus.mcuFwcheckStatus = passed;
        McuSm_SswStatusData.mcuFwcheckStatus = (uint8)passed;
        /* If all registers and SMU alarm registers have reported the expected values .. */
        /* .. clear the content of the registers mentioned in the Appendix table */
        safetyKitFwCheckClearSSH(g_SafetyKitStatus.resetCode.resetType);
        /* .. clear the SMU alarms SMU_AG0..11 */
        safetyKitFwCheckClearSmuAlarms(fwCheckSMUTC375DP, fwCheckSMUTC375DPSize);
        /* .. clear the corresponding reset status bits in RSTSTAT register */
        IfxScuRcu_clearColdResetStatus();
    }
    else
    {
        g_SafetyKitStatus.sswStatus.mcuFwcheckStatus = failed;
        McuSm_SswStatusData.mcuFwcheckStatus = (uint8)failed;
        /* Preserve the verification arrays, but normalize expected FW-check artifacts before the reset reaction. */
        safetyKitFwCheckClearSSH(g_SafetyKitStatus.resetCode.resetType);
        safetyKitFwCheckClearSmuAlarms(fwCheckSMUTC375DP, fwCheckSMUTC375DPSize);
        /* Clear COLD PORST reason to preserve the data on the SCR XRAM */
        IfxScuRcu_clearColdResetStatus();
    }

    /* Disable MTU module if it was disabled */
    if(mtuWasEnabled == FALSE)
    {
        /* Disable again */
        IfxScuWdt_clearCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());
        MTU_CLC.B.DISR = 1;
        IfxScuWdt_setCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());
    }
}

SafetyKitResetType safetyKitFwCheckGetStandbyRegisterProfile(const SafetyKitResetType resetType)
{
    SafetyKitResetType registerProfile = resetType;

    if ((g_SafetyKitStatus.wakeupFromStandby != FALSE) &&
            ((resetType == safetyKitResetTypeWarmpoweron) || (resetType == safetyKitResetTypeColdpoweron)))
    {
        /* Standby wake reports PORST-class reset, but SMU/STMEM match the application-reset profile. */
        registerProfile = safetyKitResetTypeApplication;
    }
    else
    {
        /* Do nothing. */
    }

    return (registerProfile);
}

boolean safetyKitFwCheckValidateStandbyStmem(FwCheckVerificationStruct *fwCheckVerification)
{
    uint8 i;

    for (i = 0u; i < (uint8)fwCheckSTMEMTC375DPSize; i++)
    {
        switch (fwCheckVerification[i].regUnderTest)
        {
            case fwCheckSCUSTMEM3:
            case fwCheckSCUSTMEM5:
            case fwCheckSCUSTMEM6:
                if (fwCheckVerification[i].regVal != 0x2020088Fu)
                {
                    return (FALSE);
                }
                break;
            case fwCheckSCUSTMEM4:
                if (fwCheckVerification[i].regVal != 0x00000001u)
                {
                    return (FALSE);
                }
                break;
            default:
                return (FALSE);
        }
    }

    McuSm_SafetyKitFwCheckLastRegFail = MCUSM_FW_CHECK_REG_FAIL_NONE;
    McuSm_SafetyKitFwCheckRegActual = 0u;
    McuSm_SafetyKitFwCheckRegExpected = 0u;
    McuSm_SafetyKitFwCheckRegMask = 0u;

    return (TRUE);
}

/* This function is comparing the actual register values of the registers listed in Safety Manual Appendix A with
 * the expected ones. The expected values are depending on the device type and also the reset type.
 * const FwCheckStruct *FW_CHECK_table => pointer to a structure of type FwCheckStruct. The table consists of a
 * pointer to the address of the register which should be verified and accordingly the expected register values for
 * each reset type.
 * const int tableSize => amount of entries in the FW_CHECK_table
 * const SafetyKitResetType resetType => type of the reset
 * FwCheckVerificationStruct *FW_CHECK_verification => pointer to a structure where the test result will be written
 * into. Can be observed via debugger in case the FW check has failed
 * */
boolean safetyKitFwCheckSmuStmemLclcon (const FwCheckStruct *fwCheckTable, const int tableSize,
        const SafetyKitResetType resetType, FwCheckVerificationStruct *fwCheckVerification)
{
    boolean fwcheckHasPassed = TRUE;
    uint32 registerValue;
    uint32 expectedRegisterValue;
    uint32 singleBitEccMask;
    uint32 enabledAlarmMask;

    /* A pointer to the corresponding FwCheckRegisterCheckStruct inside the FW_CHECK_table.
     * The corresponding structure of interest depends on the reset type. */
    const FwCheckRegisterCheckStruct* ptrRegisterCheckStrct;

    /* Iterate through the FW_CHECK_table */
    for(uint8 i = 0; i < tableSize; i++)
    {
        /* Set the pointer to the structure containing the expected register values */
        switch(resetType)
        {
            case safetyKitResetTypeColdpoweron:
                ptrRegisterCheckStrct = &fwCheckTable[i].coldPORST;
                break;
            case safetyKitResetTypeLbist:
                ptrRegisterCheckStrct = &fwCheckTable[i].lbistReset;
                break;
            case safetyKitResetTypeWarmpoweron:
                ptrRegisterCheckStrct = &fwCheckTable[i].warmPORST;
                break;
            case safetyKitResetTypeSystem:
                ptrRegisterCheckStrct = &fwCheckTable[i].systemReset;
                break;
            case safetyKitResetTypeApplication:
                ptrRegisterCheckStrct = &fwCheckTable[i].applicationReset;
                break;
            default:
                ptrRegisterCheckStrct = &fwCheckTable[i].warmPORST;
                break;
        }

        /* Read the value of the register which is checked during this iteration */
        registerValue = *(volatile uint32*) fwCheckTable[i].regUnderTest;
        /* Mask the register value in case there are any exceptions. (Refer to the Appendix A of the Safety Manual) */
        registerValue &= ptrRegisterCheckStrct->mask;
        /* Read the expected register value */
        expectedRegisterValue = ptrRegisterCheckStrct->expectedRegVal;
        singleBitEccMask = safetyKitFwCheckGetSmuSingleBitEccMask(fwCheckVerification[i].regUnderTest);

        if (singleBitEccMask != 0u)
        {
            registerValue &= ~singleBitEccMask;
            expectedRegisterValue &= ~singleBitEccMask;
        }

        if (fwCheckVerification == fwCheckVerificationSMU)
        {
            enabledAlarmMask = safetyKitFwCheckGetSmuEnabledAlarmMask(fwCheckVerification[i].regUnderTest);
            registerValue &= enabledAlarmMask;
            expectedRegisterValue &= enabledAlarmMask;
        }
        else
        {
            enabledAlarmMask = ptrRegisterCheckStrct->mask;
        }

        /* SMU diagnostic arrays intentionally disabled while using the older McuSm variant. */

        /* Compare the register value with the expected value and write both the test result and the actual register
         * value into the verification structure. */
        fwCheckVerification[i].regVal = registerValue;
        fwCheckVerification[i].testHasPassed = (registerValue == expectedRegisterValue) ? TRUE : FALSE;
        /* SMU diagnostic arrays intentionally disabled while using the older McuSm variant. */
        /* Set fwcheckHasPassed to FALSE in case test has failed for any register during the iteration. */
        if(!fwCheckVerification[i].testHasPassed)
        {
            safetyKitFwCheckSetRegisterDiagnostics(
                    (uint32)fwCheckVerification[i].regUnderTest,
                    registerValue,
                    expectedRegisterValue,
                    ptrRegisterCheckStrct->mask,
                    (uint32)resetType);
            fwcheckHasPassed = FALSE;
        }
    }

    /* Return result after iteration and comparison of all registers listed in the FW_CHECK_table */
    return fwcheckHasPassed;
}

uint32 safetyKitFwCheckGetSmuSingleBitEccMask(FwChectRegUnderTest regUnderTest)
{
    uint32 singleBitEccMask;

    switch (regUnderTest)
    {
        case fwCheckSMUAG0:
        case fwCheckSMUAG1:
        case fwCheckSMUAG2:
            singleBitEccMask = SAFETYKIT_FWCHECK_SMU_AG0_2_SINGLE_BIT_ECC_MASK;
            break;
        case fwCheckSMUAG6:
            singleBitEccMask = SAFETYKIT_FWCHECK_SMU_AG6_SINGLE_BIT_ECC_MASK;
            break;
        case fwCheckSMUAG7:
            singleBitEccMask = SAFETYKIT_FWCHECK_SMU_AG7_SINGLE_BIT_ECC_MASK;
            break;
        case fwCheckSMUAG10:
            singleBitEccMask = SAFETYKIT_FWCHECK_SMU_AG10_CORRECTABLE_MASK;
            break;
        default:
            singleBitEccMask = 0u;
            break;
    }

    return (singleBitEccMask);
}

uint32 safetyKitFwCheckGetSmuEnabledAlarmMask(FwChectRegUnderTest regUnderTest)
{
    uint32 alarmGroup = (uint32)regUnderTest;

    if (alarmGroup > 11u)
    {
        return (SAFETYKIT_FWCHECK_DEFAULT_MASK);
    }

    return (MODULE_SMU.AGCF[alarmGroup][0].U |
            MODULE_SMU.AGCF[alarmGroup][1].U |
            MODULE_SMU.AGCF[alarmGroup][2].U);
}

/*
 * Check the SSH registers and compare with the expected values depending on the reset type
 * */
IfxMtu_MbistSel safetyKitFwCheckSsh(const SafetyKitResetType resetType)
{
    IfxMtu_MbistSel fwcheckSshResult = IfxMtu_MbistSel_none;
    switch (resetType)
    {
        case safetyKitResetTypeColdpoweron :
            fwcheckSshResult = (g_SafetyKitStatus.wakeupFromStandby != FALSE) ?
                    safetyKitFwCheckCheckStandbySshRegisters(coldPorstSSHTC375DP, coldPorstSSHTC375DPSize) :
                    safetyKitFwCheckCheckSshRegisters(coldPorstSSHTC375DP, coldPorstSSHTC375DPSize);
            break;
        case safetyKitResetTypeLbist :
            fwcheckSshResult = safetyKitFwCheckCheckLbistSshRegisters(warmPorstSSHTC375DP, warmPorstSSHTC375DPSize);
            break;
        case safetyKitResetTypeWarmpoweron :
            fwcheckSshResult = (g_SafetyKitStatus.wakeupFromStandby != FALSE) ?
                    safetyKitFwCheckCheckStandbySshRegisters(warmPorstSSHTC375DP, warmPorstSSHTC375DPSize) :
                    safetyKitFwCheckCheckSshRegisters(warmPorstSSHTC375DP, warmPorstSSHTC375DPSize);
            break;
        case safetyKitResetTypeSystem :
            fwcheckSshResult = (g_SafetyKitStatus.wakeupFromStandby != FALSE) ?
                    safetyKitFwCheckCheckStandbySshRegisters(systemSSHTC375DP, systemSSHTC375DPSize) :
                    safetyKitFwCheckCheckSshRegisters(systemSSHTC375DP, systemSSHTC375DPSize);
            break;
        case safetyKitResetTypeApplication :
            fwcheckSshResult = (g_SafetyKitStatus.wakeupFromStandby != FALSE) ?
                    safetyKitFwCheckCheckStandbySshRegisters(applicationSSHTC375DP, applicationSSHTC375DPSize) :
                    safetyKitFwCheckCheckSshRegisters(applicationSSHTC375DP, applicationSSHTC375DPSize);
            break;
        default:
            break;
    }
    return fwcheckSshResult;
}

/*
 * clear the SSH registers
 * */
void safetyKitFwCheckClearSSH(const SafetyKitResetType resetType)
{
    /* Get pointer to specific table and set variable about the size of this table */
    const MemoryTestedStruct* sshTable;
    int tableSize;

    switch(resetType)
    {
        case safetyKitResetTypeColdpoweron:
            sshTable    = coldPorstSSHTC375DP;
            tableSize  = coldPorstSSHTC375DPSize;
            break;
        case safetyKitResetTypeLbist:
            sshTable    = warmPorstSSHTC375DP;
            tableSize  = warmPorstSSHTC375DPSize;
            break;
        case safetyKitResetTypeWarmpoweron:
            sshTable    = warmPorstSSHTC375DP;
            tableSize  = warmPorstSSHTC375DPSize;
            break;
        case safetyKitResetTypeSystem:
            sshTable    = systemSSHTC375DP;
            tableSize  = systemSSHTC375DPSize;
            break;
        case safetyKitResetTypeApplication:
            sshTable    = applicationSSHTC375DP;
            tableSize  = applicationSSHTC375DPSize;
            break;
        default:
            break;
    }

    /* Now iterate through the table and clear the ECCD, FAULTSTS and ERRINFO register values */
    IfxMtu_MbistSel mbistSel;
    Ifx_MTU_MC *mc;
    int a;
    uint16 password = IfxScuWdt_getSafetyWatchdogPassword();

    for (a = 0; a < tableSize ; a++ )
    {
        mbistSel = sshTable[a].sshUnderTest;

        mc = &MODULE_MTU.MC[mbistSel];
        mc->ECCD.U = 0x0;

        IfxScuWdt_clearSafetyEndinit(password);

        mc->FAULTSTS.U = 0x0;
        mc->ECCD.B.TRC = 1;  /* This will clear ERRINFO */

        IfxScuWdt_setSafetyEndinit(password);
    }
}

/*
 * This is the implementation of Erratum from Errata sheet
 * Erratum: [SMU_TC.H012]
 * The SMU alarms ALM7[1] and ALM7[0] are set intentionally after PORST and system reset and shall be
 * cleared by the application SW (cf. SM:MCU_FW_CHECK in Safety Manual) Also, in order to
 * clear the SMU alarms ALM7[1] and ALM7[0], it is necessary to clear the alarms within this MC40.
 * */
void clearFaultStatusAndECCDetectionFSIRAM(void)
{
    uint16 password = IfxScuWdt_getSafetyWatchdogPassword();
    uint16 *ptrEccd = (uint16 *)(0xF0063810);      /* MCi_ECCD and i = 40 */
    *ptrEccd = 0;

    IfxScuWdt_clearSafetyEndinit(password);
    uint16 *ptrFaultsts = (uint16 *)(0xF00638F0);  /* MCi_FAULTSTS and i = 40*/
    *ptrFaultsts = 0;
    IfxScuWdt_setSafetyEndinit(password);
}

/*
 * clear SMU alarm
 * */
void safetyKitFwCheckClearSmuAlarms(const FwCheckStruct *FW_CHECK_table, const int tableSize)
{
    uint16 passwd = IfxScuWdt_getSafetyWatchdogPassword();

    /* erratum SMU_TC.H012*/
    clearFaultStatusAndECCDetectionFSIRAM();

    IfxScuWdt_clearSafetyEndinit(passwd);

    /* Iterate through all SMU alarm status registers listed in the FW_CHECK_table and clear them */
    for(uint8 i = 0; i < tableSize; i++)
    {
        MODULE_SMU.CMD.U = IfxSmu_Command_alarmStatusClear;
        *(volatile uint32 *)FW_CHECK_table[i].regUnderTest = (uint32) 0xFFFFFFFF;
    }

    IfxScuWdt_setSafetyEndinit(passwd);

}
/*
 * retrigger firmware check
 * */
void safetyKitFwCheckRetriggerCheck(const SafetyKitResetType resetType)
{
    /* Initiate the specific reset to trigger an FW check. Note: the reset should be the same type as it was before
     * this FW check execution */
    switch (resetType)
    {
        case safetyKitResetTypeColdpoweron :
        case safetyKitResetTypeLbist :
            break;
        case safetyKitResetTypeWarmpoweron :
            safetyKitFwCheckClearSSH(resetType);
            break;
        case safetyKitResetTypeSystem :
            safetyKitFwCheckClearSSH(resetType);
            break;
        case safetyKitResetTypeApplication :
            safetyKitFwCheckClearSSH(resetType);
            break;
        default:
            __debug();
            break;
    }
}
/*
 * This function is comparing the SSH registers of all RAMs with their expected values
 * */
IfxMtu_MbistSel safetyKitFwCheckCheckSshRegisters (const MemoryTestedStruct* sshTable, int tableSize)
{
    IfxMtu_MbistSel mbistSel;
    Ifx_MTU_MC *mc;
    int a;
    uint16 expectedValueFAULTSTS, expectedValueECCD, expectedValueERRINFO;
    uint32 actualEccd;
    uint32 actualFaultsts;
    uint32 actualErrinfo;

    /* Iterate through all entries in the SSH_table */
    for (a = 0; a < tableSize; a++)
    {
        /* Get SSH which is tested during this iteration */
        mbistSel = sshTable[a].sshUnderTest;
        /* Get pointer to MC object of tested SSH */
        mc = &MODULE_MTU.MC[mbistSel];

        safetyKitFwCheckGetExpectedSshValues(&sshTable[a], &expectedValueECCD, &expectedValueFAULTSTS,
                &expectedValueERRINFO);

        actualEccd = mc->ECCD.U;
        actualFaultsts = mc->FAULTSTS.U;
        actualErrinfo = mc->ERRINFO[0].U;

        /* Finally compare register values of selected memory with the expected ones, if any mismatch is detected
         * return the name of the selected memory and stop the function execution. */
        if (actualEccd != expectedValueECCD || actualFaultsts != expectedValueFAULTSTS
                || actualErrinfo != expectedValueERRINFO)
        {
            if ((FALSE == safetyKitFwCheckIsSingleBitEccOnly(actualEccd, actualFaultsts, actualErrinfo,
                    expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO)) &&
                    (FALSE == safetyKitFwCheckIsStandbyWakeCleanSshState(mbistSel, actualEccd, actualFaultsts,
                            actualErrinfo, expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO)))
            {
                safetyKitFwCheckSetSshDiagnostics(mbistSel, actualEccd, actualFaultsts, actualErrinfo,
                        expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO);
                return (mbistSel);
            }
        }
        else
        {
            /* Do nothing. */
        }
    }

    McuSm_SafetyKitFwCheckLastSshFail = (uint32)IfxMtu_MbistSel_none;
    return (IfxMtu_MbistSel_none);
}

IfxMtu_MbistSel safetyKitFwCheckCheckStandbySshRegisters (const MemoryTestedStruct* sshTable, int tableSize)
{
    IfxMtu_MbistSel mbistSel;
    Ifx_MTU_MC *mc;
    int a;
    uint16 expectedValueFAULTSTS, expectedValueECCD, expectedValueERRINFO;
    uint32 actualEccd;
    uint32 actualFaultsts;
    uint32 actualErrinfo;

    for (a = 0; a < tableSize; a++)
    {
        mbistSel = sshTable[a].sshUnderTest;
        mc = &MODULE_MTU.MC[mbistSel];

        safetyKitFwCheckGetExpectedSshValues(&sshTable[a], &expectedValueECCD, &expectedValueFAULTSTS,
                &expectedValueERRINFO);

        actualEccd = mc->ECCD.U;
        actualFaultsts = mc->FAULTSTS.U;
        actualErrinfo = mc->ERRINFO[0].U;

        if ((actualEccd == 0u) && (actualFaultsts == 0u) && (actualErrinfo == 0u))
        {
            /* Standby wake can leave SSH status in the already-cleared no-fault state. */
        }
        else if ((actualEccd == expectedValueECCD) && (actualFaultsts == expectedValueFAULTSTS)
                && (actualErrinfo == expectedValueERRINFO))
        {
            /* Do nothing. */
        }
        else if (FALSE != safetyKitFwCheckIsSingleBitEccOnly(actualEccd, actualFaultsts, actualErrinfo,
                expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO))
        {
            /* Per errata, correctable single-bit ECC indications are not FW-check startup failures. */
        }
        else if (FALSE != safetyKitFwCheckIsStandbyWakeCleanSshState(mbistSel, actualEccd, actualFaultsts,
                actualErrinfo, expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO))
        {
            /* Standby wake can leave the expected SSH state with ECCD tracking bits already cleared. */
        }
        else
        {
            safetyKitFwCheckSetSshDiagnostics(mbistSel, actualEccd, actualFaultsts, actualErrinfo,
                    expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO);
            return (mbistSel);
        }
    }

    McuSm_SafetyKitFwCheckLastSshFail = (uint32)IfxMtu_MbistSel_none;
    return (IfxMtu_MbistSel_none);
}

/*
 * After an LBIST reset on this TC375DP target, SSH status registers can be observed in the no-fault zero state, in
 * the table-derived state, in the default not-initialized state, or in an initialized RAM state derived from the
 * DMU RAM initialization configuration. Treat these as valid and report any other state.
 */
IfxMtu_MbistSel safetyKitFwCheckCheckLbistSshRegisters (const MemoryTestedStruct* sshTable, int tableSize)
{
    IfxMtu_MbistSel mbistSel;
    Ifx_MTU_MC *mc;
    int a;
    uint16 expectedValueECCD;
    uint16 expectedValueFAULTSTS;
    uint16 expectedValueERRINFO;
    uint32 actualEccd;
    uint32 actualFaultsts;
    uint32 actualErrinfo;

    for (a = 0; a < tableSize; a++)
    {
        mbistSel = sshTable[a].sshUnderTest;
        mc = &MODULE_MTU.MC[mbistSel];
        safetyKitFwCheckGetExpectedSshValues(&sshTable[a], &expectedValueECCD, &expectedValueFAULTSTS,
                &expectedValueERRINFO);

        actualEccd = mc->ECCD.U;
        actualFaultsts = mc->FAULTSTS.U;
        actualErrinfo = mc->ERRINFO[0].U;

        if ((actualEccd == 0u) && (actualFaultsts == 0u) && (actualErrinfo == 0u))
        {
            McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_LBIST_SSH_ZERO_ACCEPTED;
        }
        else if ((actualEccd == expectedValueECCD) && (actualFaultsts == expectedValueFAULTSTS)
                && (actualErrinfo == expectedValueERRINFO))
        {
            McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_LBIST_SSH_TABLE_ACCEPTED;
        }
        else if (FALSE != safetyKitFwCheckIsInitializedRamSshState(&sshTable[a], actualEccd, actualFaultsts,
                actualErrinfo))
        {
            McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_LBIST_SSH_INIT_ACCEPTED;
        }
        else if ((actualEccd == 0x5u) && (actualFaultsts == 0x1u) && (actualErrinfo == 0x0u))
        {
            McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_LBIST_SSH_NOINIT_ACCEPTED;
        }
        else if (((actualEccd == 0x5u) || (actualEccd == 0x0u))
                && (actualFaultsts == 0x9u) && (actualErrinfo == 0x0u))
        {
            /* DMU RAM/LMU auto-init at the LBIST PORST-class exit leaves the SSH in the
             * initialized state (FAULTSTS=0x9, init-done) for memories the hardware
             * re-initializes regardless of the SW-visible PROCONRAM.RAMINSEL/LMUINSEL config.
             * The post-init ECCD is observed in two benign variants: 0x5 (error-detection
             * tracking bits set) and 0x0 (no ECC flags, the cleaner state); ERRINFO is 0 in
             * both. safetyKitFwCheckIsInitializedRamSshState() gates the same state behind the
             * PROCONRAM evaluation, which does not reflect the unconditional auto-init and so
             * rejects it here. Accept the initialized signature as a valid LBIST side effect
             * (see FW_CHECK_DEVIATIONS deviation #9). This is the single-occurrence, power-on
             * only FW-check failure (FAULTSTS=0x9, e.g. SSH instance 0x4E). */
            McuSm_SafetyKitFwCheckResultMask |= MCUSM_FW_CHECK_RESULT_LBIST_SSH_INIT_ACCEPTED;
        }
        else if (FALSE != safetyKitFwCheckIsSingleBitEccOnly(actualEccd, actualFaultsts, actualErrinfo,
                expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO))
        {
            /* Per errata, correctable single-bit ECC indications are not FW-check startup failures. */
        }
        else
        {
            safetyKitFwCheckSetSshDiagnostics(mbistSel, actualEccd, actualFaultsts, actualErrinfo,
                    expectedValueECCD, expectedValueFAULTSTS, expectedValueERRINFO);
            return (mbistSel);
        }
    }

    McuSm_SafetyKitFwCheckLastSshFail = (uint32)IfxMtu_MbistSel_none;
    return (IfxMtu_MbistSel_none);
}

boolean safetyKitFwCheckIsInitializedRamSshState(const MemoryTestedStruct *sshEntry, uint32 actualEccd,
        uint32 actualFaultsts, uint32 actualErrinfo)
{
    boolean memoryInitialized;

    if ((actualEccd != 0x5u) || (actualFaultsts != 0x9u) || (actualErrinfo != 0x0u))
    {
        return (FALSE);
    }

    if (CPU_MEM_TYPE == sshEntry->memoryType)
    {
        memoryInitialized = safetyKitFwCheckEvaluateRamInit(sshEntry->InSelMask);
    }
    else if (LMU_MEM_TYPE == sshEntry->memoryType)
    {
        memoryInitialized = safetyKitFwCheckEvaluateLmuInit(sshEntry->InSelMask);
    }
    else
    {
        memoryInitialized = FALSE;
    }

    return (memoryInitialized);
}

boolean safetyKitFwCheckIsSingleBitEccOnly(uint32 actualEccd, uint32 actualFaultsts, uint32 actualErrinfo,
        uint32 expectedEccd, uint32 expectedFaultsts, uint32 expectedErrinfo)
{
    uint32 unexpectedEccd;
    uint32 unexpectedErrinfo;

    if (actualFaultsts != expectedFaultsts)
    {
        return (FALSE);
    }

    unexpectedEccd = actualEccd ^ expectedEccd;
    unexpectedErrinfo = actualErrinfo ^ expectedErrinfo;

    if ((unexpectedEccd == 0u) && (unexpectedErrinfo == 0u))
    {
        return (TRUE);
    }

    if ((unexpectedEccd & ~SAFETYKIT_FWCHECK_SSH_ECCD_SINGLE_BIT_ECC_MASK) != 0u)
    {
        return (FALSE);
    }

    if ((unexpectedErrinfo & ~SAFETYKIT_FWCHECK_SSH_ERRINFO_SINGLE_BIT_ECC_MASK) != 0u)
    {
        return (FALSE);
    }

    if (((actualEccd & SAFETYKIT_FWCHECK_SSH_ECCD_SINGLE_BIT_ECC_MASK) == 0u) ||
            ((actualErrinfo & SAFETYKIT_FWCHECK_SSH_ERRINFO_SINGLE_BIT_ECC_MASK) == 0u))
    {
        return (FALSE);
    }

    return (TRUE);
}

boolean safetyKitFwCheckIsStandbyWakeCleanSshState(IfxMtu_MbistSel mbistSel, uint32 actualEccd,
        uint32 actualFaultsts, uint32 actualErrinfo, uint32 expectedEccd, uint32 expectedFaultsts,
        uint32 expectedErrinfo)
{
    if (FALSE == g_SafetyKitStatus.wakeupFromStandby)
    {
        return (FALSE);
    }

    if ((expectedEccd != 0x5u) || (expectedErrinfo != 0x0u))
    {
        return (FALSE);
    }

    if ((expectedFaultsts != 0x1u) && (expectedFaultsts != 0x9u))
    {
        return (FALSE);
    }

    if ((actualEccd == 0x0u) && (actualFaultsts == expectedFaultsts) &&
            (actualErrinfo == expectedErrinfo))
    {
        return (TRUE);
    }

    if ((actualEccd == 0x0u) && (actualFaultsts == 0x9u) && (actualErrinfo == expectedErrinfo) &&
            (expectedFaultsts == 0x1u))
    {
        switch (mbistSel)
        {
            case IfxMtu_MbistSel_cpu2Dlmu:
            case IfxMtu_MbistSel_dam0:
                return (TRUE);
            default:
                break;
        }
    }

    return (FALSE);
}

void safetyKitFwCheckGetExpectedSshValues(const MemoryTestedStruct *sshEntry, uint16 *expectedValueECCD,
        uint16 *expectedValueFAULTSTS, uint16 *expectedValueERRINFO)
{
    if ( CPU_MEM_TYPE == sshEntry->memoryType)
    {
        if (TRUE == safetyKitFwCheckEvaluateRamInit(sshEntry->InSelMask))
        {
            *expectedValueFAULTSTS = 0x9;
        }
        else
        {
            *expectedValueFAULTSTS = 0x1;
        }
    }
    else if ( LMU_MEM_TYPE == sshEntry->memoryType)
    {
        if (TRUE == safetyKitFwCheckEvaluateLmuInit(sshEntry->InSelMask))
        {
            *expectedValueFAULTSTS = 0x9;
        }
        else
        {
            *expectedValueFAULTSTS = 0x1;
        }
    }
    else
    {
        *expectedValueFAULTSTS = sshEntry->sshRegistersDef.faultstsVal;
    }

    *expectedValueECCD = sshEntry->sshRegistersDef.eccdVal;
    *expectedValueERRINFO = sshEntry->sshRegistersDef.errinfoVal;

    if (g_SafetyKitStatus.wakeupFromStandby)
    {
        *expectedValueFAULTSTS = sshEntry->sshRegistersStb.faultstsVal;
        *expectedValueECCD = sshEntry->sshRegistersStb.eccdVal;
        *expectedValueERRINFO = sshEntry->sshRegistersStb.errinfoVal;
    }
}

void safetyKitFwCheckSetSshDiagnostics(IfxMtu_MbistSel mbistSel, uint32 actualEccd, uint32 actualFaultsts,
        uint32 actualErrinfo, uint32 expectedEccd, uint32 expectedFaultsts, uint32 expectedErrinfo)
{
    McuSm_SafetyKitFwCheckLastSshFail = (uint32)mbistSel;
    McuSm_SafetyKitFwCheckSshActualEccd = actualEccd;
    McuSm_SafetyKitFwCheckSshActualFaultsts = actualFaultsts;
    McuSm_SafetyKitFwCheckSshActualErrinfo = actualErrinfo;
    McuSm_SafetyKitFwCheckSshExpectedEccd = expectedEccd;
    McuSm_SafetyKitFwCheckSshExpectedFaultsts = expectedFaultsts;
    McuSm_SafetyKitFwCheckSshExpectedErrinfo = expectedErrinfo;
}

void safetyKitFwCheckSetRegisterDiagnostics(uint32 regUnderTest, uint32 actual, uint32 expected,
        uint32 mask, uint32 resetType)
{
    if (McuSm_SafetyKitFwCheckLastRegFail != MCUSM_FW_CHECK_REG_FAIL_NONE)
    {
        return;
    }

    McuSm_SafetyKitFwCheckLastRegFail = regUnderTest;
    McuSm_SafetyKitFwCheckRegActual = actual;
    McuSm_SafetyKitFwCheckRegExpected = expected;
    McuSm_SafetyKitFwCheckRegMask = mask;
    McuSm_SafetyKitFwCheckRegResetType = resetType;
}
/*
 * Verify if CPU memory is initialized
 * */
boolean safetyKitFwCheckEvaluateRamInit(uint16 memoryMask)
{
    if (( RAM_INIT_AT_COLD_WARM == DMU_HF_PROCONRAM.B.RAMIN) ||
            ( RAM_INIT_AT_COLD_ONLY == DMU_HF_PROCONRAM.B.RAMIN))
    {
        if (((DMU_HF_PROCONRAM.B.RAMINSEL) & (uint16) (memoryMask)) == 0)
        {
            return (TRUE);
        }
        else
        {
            return (FALSE);
        }
    }
    else
    {
        return (FALSE);
    }
}
/*
 * Verify if LMU memory is initialized
 * */
boolean safetyKitFwCheckEvaluateLmuInit(uint16 memoryMask)
{
    if ((RAM_INIT_AT_COLD_WARM == DMU_HF_PROCONRAM.B.RAMIN) ||
            (RAM_INIT_AT_COLD_ONLY == DMU_HF_PROCONRAM.B.RAMIN))
    {
        if (((DMU_HF_PROCONRAM.B.LMUINSEL) & (uint16) (memoryMask)) == 0)
        {
            return (TRUE);
        }
        else
        {
            return (FALSE);
        }
    }
    else
    {
        return (FALSE);
    }
}

/*
 * clear all SMU alarm
 * */
void safetyKitClearAllSmuAlarms(void)
{
    safetyKitFwCheckClearSmuAlarms(fwCheckSMUTC375DP, fwCheckSMUTC375DPSize);
}
