/**********************************************************************************************************************
 * \file SafetyKit_SSW.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SafetyKit_SSW.h"
#include "SafetyKit_SSW_00_LBIST.h"
#include "SafetyKit_SSW_02_MCU_FW_CHECK.h"
#include "SafetyKit_SSW_03_MCU_STARTUP.h"
#include "SafetyKit_SSW_04_ALIVE_ALARM_TEST.h"
#include "SafetyKit_SSW_05_SMU_REG_MONITOR_TEST.h"
#include "SafetyKit_SSW_06_MBIST.h"
#include "SafetyKit_Main.h"
#include "IfxScuRcu.h"
#include "Ifx_Cfg_Ssw.h"
#include "IfxMtu.h"
#include "IfxStm.h"
#include "Bsp.h"
#include "IfxPort.h"
#include "IfxScuLbist.h"
#include "Ifx_Ssw_Infra.h"
#include "IfxPmsPm.h"
#include "IfxSmu.h"
#include "SMU.h"
#include "McuSm.h"
#include "SafetyKit_SSW_00_LBIST.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SAFETYKIT_STANDBY_WAKE_SOURCE_LBIST_RETAINED \
        (1u << 8u)
#define SAFETYKIT_STANDBY_WAKE_SOURCE_SCR_LATCH      \
        (1u << 9u)
#define SAFETYKIT_STANDBY_WAKE_LATCH_SOURCE_MASK     \
        (SCR_STANDBY_WAKE_SOURCE_PMS | \
         SCR_STANDBY_WAKE_SOURCE_SCR_XRAM | \
         SCR_STANDBY_WAKE_SOURCE_APP_ARMED)
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile uint32 SafetyKit_StandbyWakeRawPmsWstat2;
volatile uint8 SafetyKit_StandbyWakeScrReason;
volatile uint8 SafetyKit_StandbyWakeRetained;
volatile uint32 SafetyKit_StandbyWakeSourceMask;
volatile uint8 SafetyKit_StandbyWakeLatchValid;
volatile uint8 SafetyKit_StandbyWakeLatchSourceMask;
volatile uint8 SafetyKit_StandbyWakeLatchPmsWstat2;
volatile uint8 SafetyKit_StandbyWakeLatchScrReason;
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
SafetyKitResetCode safetyKitEvaluateReset(void);
boolean safetyKitEvaluateStandby(void);
static void safetyKitClearStandbyWakeFlags(uint32 wakeFlags);
static boolean safetyKitReadStandbyWakeLatch(uint8 *sourceMask, uint8 *pmsWakeFlags, uint8 *scrWakeReason);
static uint32 safetyKitGetStartupFailureMask(boolean includeSmuStatus);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static uint32 safetyKitGetStartupFailureMask(boolean includeSmuStatus)
{
    uint32 failureMask = 0u;

    if (g_SafetyKitStatus.sswStatus.lbistStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_LBIST;
    }
    if (g_SafetyKitStatus.sswStatus.monbistStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_MONBIST;
    }
    if (g_SafetyKitStatus.sswStatus.mcuFwcheckStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_MCU_FW_CHECK;
    }
    if (g_SafetyKitStatus.sswStatus.mcuStartupStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_MCU_STARTUP;
    }
    if (g_SafetyKitStatus.sswStatus.aliveAlarmTestStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_ALIVE_ALARM;
    }
    if (g_SafetyKitStatus.sswStatus.regMonitorTestStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_REG_MONITOR;
    }
    if (g_SafetyKitStatus.sswStatus.mbistStatus == failed)
    {
        failureMask |= MCUSM_SAFETYKIT_FAIL_MBIST;
    }
    if (includeSmuStatus != FALSE)
    {
        if (g_SafetyKitStatus.smuStatus.smuCoreKeysTestSts == fail)
        {
            failureMask |= MCUSM_SAFETYKIT_FAIL_SMU_KEYS;
        }
        if (g_SafetyKitStatus.smuStatus.smuCoreKeysTestClearSts == fail)
        {
            failureMask |= MCUSM_SAFETYKIT_FAIL_SMU_KEYS_CLEAR;
        }
        if (g_SafetyKitStatus.smuStatus.smuCoreInitSts == fail)
        {
            failureMask |= MCUSM_SAFETYKIT_FAIL_SMU_INIT;
        }
    }

    return failureMask;
}

void safetyKitUpdateMcuSmStatusAndResetReaction(boolean includeSmuStatus)
{
    uint32 failureMask;

    McuSm_SswStatusData.lbistStatus = (uint8)g_SafetyKitStatus.sswStatus.lbistStatus;
    McuSm_SswStatusData.monbistStatus = (uint8)g_SafetyKitStatus.sswStatus.monbistStatus;
    McuSm_SswStatusData.mcuFwcheckStatus = (uint8)g_SafetyKitStatus.sswStatus.mcuFwcheckStatus;
    McuSm_SswStatusData.mcuStartupStatus = (uint8)g_SafetyKitStatus.sswStatus.mcuStartupStatus;
    McuSm_SswStatusData.aliveAlarmTestStatus = (uint8)g_SafetyKitStatus.sswStatus.aliveAlarmTestStatus;
    McuSm_SswStatusData.regMonitorTestStatus = (uint8)g_SafetyKitStatus.sswStatus.regMonitorTestStatus;
    McuSm_SswStatusData.mbistStatus = (uint8)g_SafetyKitStatus.sswStatus.mbistStatus;
    McuSm_SswStatusData.smuCoreKeysTestSts = (uint8)g_SafetyKitStatus.smuStatus.smuCoreKeysTestSts;
    McuSm_SswStatusData.smuCoreKeysTestClearSts = (uint8)g_SafetyKitStatus.smuStatus.smuCoreKeysTestClearSts;
    McuSm_SswStatusData.smuCoreInitSts = (uint8)g_SafetyKitStatus.smuStatus.smuCoreInitSts;
    McuSm_SswStatusData.wakeupFromStandby = (uint8)g_SafetyKitStatus.wakeupFromStandby;
    McuSm_SswStatusData.resetReason = g_SafetyKitStatus.resetCode.resetReason;
    McuSm_SswStatusData.resetType = (uint32)g_SafetyKitStatus.resetCode.resetType;
    McuSm_SswStatusData.resetTrigger = (uint32)g_SafetyKitStatus.resetCode.resetTrigger;

    failureMask = safetyKitGetStartupFailureMask(includeSmuStatus);
    McuSm_SafetyKitFailureMask = failureMask;

    if (failureMask == 0u)
    {
        if (McuSm_LastResetReason != MCUSM_RESET_REASON_SAFETYKIT_TEST)
        {
            McuSm_SafetyKitResetInhibit = 0u;
        }
        else
        {
            /* Dem has not yet processed the retained safety reset reason. */
        }
    }
    else if (McuSm_SafetyKitResetInhibit == 0u)
    {
        if (McuSm_LastResetReason == MCUSM_RESET_REASON_SAFETYKIT_TEST)
        {
            McuSm_SafetyKitResetInhibit = 1u;
        }
        else
        {
            McuSm_SafetyKitResetInhibit = 1u;
            McuSm_SafetyKitResetReactionCounter++;
            McuSm_PerformResetHook(
                    MCUSM_RESET_REASON_SAFETYKIT_TEST,
                    failureMask |
                            ((McuSm_SafetyKitFwCheckResultMask &
                                    (MCUSM_FW_CHECK_RESULT_SMU_FAILED |
                                            MCUSM_FW_CHECK_RESULT_STMEM_FAILED |
                                            MCUSM_FW_CHECK_RESULT_LCLCON_FAILED |
                                            MCUSM_FW_CHECK_RESULT_SSH_FAILED)) <<
                                    MCUSM_SAFETYKIT_INFO_FW_CHECK_SHIFT));
        }
    }
    else
    {
        /* Allow Dem to store the previous SafetyKit reset reaction. */
    }
}

/*
 * Execute the sequence of safety mechanisms when coming from an un-powered state.
 * Refer to Figure 7 in AURIX TC3xx Safety Manual
 * */
void runSafeAppSwStartup(void)
{
    McuSm_SswStartupCounter++;

    g_SafetyKitStatus.wakeupFromStandby = safetyKitEvaluateStandby();
    if (g_SafetyKitStatus.wakeupFromStandby != FALSE)
    {
        McuSm_SaveRetainedStateToScr();
    }
    else
    {
        /* Do nothing. */
    }

    safetyKitSswLbist();

    g_SafetyKitStatus.resetCode = safetyKitEvaluateReset();

    g_SafetyKitStatus.wakeupFromStandby = safetyKitEvaluateStandby();

    g_SafetyKitStatus.sswStatus.monbistStatus = failed;

    Ifx_Ssw_Monbist();

    g_SafetyKitStatus.sswStatus.monbistStatus = passed;

    safetyKitSswMcuFwCheck();

    safetyKitSswMcuStartup();

    safetyKitSswAliveAlarmTest();

    safetyKitSswSmuRegMonitorTest();

    McuSm_SaveRetainedStateToScr();
    safetyKitSswMbist();
    /* MBIST can include SCR XRAM; rewrite the handoff after the non-destructive test. */
    McuSm_SaveRetainedStateToScr();
    (void)McuSm_RestoreRetainedStateFromScr();
    g_SafetyKitStatus.wakeupFromStandby =
            (McuSm_SswStatusData.wakeupFromStandby != 0u) ? TRUE : FALSE;

    initPmsErrataWorkarounds();

    safetyKitEnableAllSMUAlarms();

    safetyKitUpdateMcuSmStatusAndResetReaction(FALSE);
    /* Standby wake latch support is disabled while using the older McuSm variant. */
}
/*
 * This function Evaluate the Reset and returns reset code which contains Reset type, trigger and reason details.
 */
SafetyKitResetCode safetyKitEvaluateReset(void)
{
    static boolean resetEvaluated = FALSE;
    static SafetyKitResetCode resetCode;
    /* This function guarantees that reset type will be evaluated only once
     * and that its value will not change during runtime.
     * The first time this function is called, it evaluate the reset type and
     *  clears RSTSTAT register.
     */
    if (resetEvaluated == FALSE)
    {
        Ifx_SCU_RSTCON rstCon;
        Ifx_SCU_RSTSTAT rstStat;
        boolean pmsStandbyWake;

        resetCode.cpuSafeState = (((MODULE_SCU.RSTCON2.U >> IFX_SCU_RSTCON2_CSSX_OFF) & IFX_SCU_RSTCON2_CSSX_MSK) == IFX_SCU_RSTCON2_CSSX_MSK);
        resetCode.resetType = safetyKitResetTypeUndefined;
        resetCode.resetTrigger = IfxScuRcu_Trigger_undefined;
        resetCode.resetReason = 0;
        rstStat.U = MODULE_SCU.RSTSTAT.U;
        rstCon.U = MODULE_SCU.RSTCON.U;
        McuSm_SswStatusData.rstStat = rstStat.U;
        pmsStandbyWake = (((PMS_PMSWSTAT2.U & SCR_STANDBY_WAKE_PMSWSTAT2_WAKE_FLAGS_MASK) > 0u) ||
                (McuSm_SswStatusData.wakeupFromStandby != 0u)) ? TRUE : FALSE;

        /* Evaluate the warm reset conditions first */
        if (rstStat.B.ESR0)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.ESR0;
            resetCode.resetTrigger = IfxScuRcu_Trigger_esr0;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.ESR1)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.ESR1;
            resetCode.resetTrigger = IfxScuRcu_Trigger_esr1;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.SMU)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.SMU;
            resetCode.resetTrigger = IfxScuRcu_Trigger_smu;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.SW)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.SW;
            resetCode.resetTrigger = IfxScuRcu_Trigger_sw;
            resetCode.resetReason = MODULE_SCU.RSTCON2.B.USRINFO;
        }
        else if (rstStat.B.STM0)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.STM0;
            resetCode.resetTrigger = IfxScuRcu_Trigger_stm0;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.STM1)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.STM1;
            resetCode.resetTrigger = IfxScuRcu_Trigger_stm1;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.STM2)
        {
            resetCode.resetType = (SafetyKitResetType) rstCon.B.STM2;
            resetCode.resetTrigger = IfxScuRcu_Trigger_stm2;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.CB0)
        {
            resetCode.resetType = safetyKitResetTypeSystem;
            resetCode.resetTrigger = IfxScuRcu_Trigger_cb0;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.CB1)
        {
            resetCode.resetType = safetyKitResetTypeDebug;
            resetCode.resetTrigger = IfxScuRcu_Trigger_cb1;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.CB3)
        {
            resetCode.resetType = safetyKitResetTypeApplication;
            resetCode.resetTrigger = IfxScuRcu_Trigger_cb3;
            resetCode.resetReason = 0;
        }
        else if (rstStat.B.LBTERM)
        {
            resetCode.resetType = safetyKitResetTypeLbist;
            resetCode.resetTrigger = IfxScuRcu_Trigger_swd;
            resetCode.resetReason = 0;
        }
        else
        {
            /* Now evaluate for Cold reset conditions */
            if (rstStat.B.EVRC)
            {
                resetCode.resetType = safetyKitResetTypeColdpoweron;
                resetCode.resetTrigger = IfxScuRcu_Trigger_evrc;
                resetCode.resetReason = 0;
            }
            else if (rstStat.B.EVR33)
            {
                resetCode.resetType = safetyKitResetTypeColdpoweron;
                resetCode.resetTrigger = IfxScuRcu_Trigger_evr33;
                resetCode.resetReason = 0;
            }
            else if (rstStat.B.SWD)
            {
                resetCode.resetType = safetyKitResetTypeColdpoweron;
                resetCode.resetTrigger = IfxScuRcu_Trigger_swd;
                resetCode.resetReason = 0;
            }
            else if ((rstStat.B.STBYR) || (pmsStandbyWake != FALSE))
            {
                resetCode.resetType = safetyKitResetTypeColdpoweron;
                resetCode.resetTrigger = IfxScuRcu_Trigger_stbyr;
                resetCode.resetReason = 0;
            }
            else
            {
                /* Do nothing. */
            }
        }
        /* Finally - Evaluate selectively for PORST */
        if (rstStat.B.PORST)
        {
            if (resetCode.resetType != safetyKitResetTypeColdpoweron
                    && resetCode.resetType != safetyKitResetTypeLbist )
            {
                resetCode.resetType = safetyKitResetTypeWarmpoweron;
                resetCode.resetTrigger = IfxScuRcu_Trigger_portst;
            }
            else
            {
                /* Do nothing. */
            }

            resetCode.resetReason = 0;
        }
        else
        {
            /* Do nothing. */
        }

        resetEvaluated = TRUE;
        /* Clear COLD PORST reason */
        IfxScuRcu_clearColdResetStatus();
    }
    else
    {
        /* Do nothing. */
    }

    return resetCode;
}
/*
 * This function evaluates if software execution is continuing after being in Standby mode
 * */
static void safetyKitClearStandbyWakeFlags(uint32 wakeFlags)
{
    if (wakeFlags != 0u)
    {
        uint16 endinitSfty_pw = IfxScuWdt_getSafetyWatchdogPassword();

        IfxScuWdt_clearSafetyEndinit(endinitSfty_pw);
        PMS_PMSWSTATCLR.U = wakeFlags;
        IfxScuWdt_setSafetyEndinit(endinitSfty_pw);
    }
    else
    {
        /* Do nothing. */
    }
}

static boolean safetyKitReadStandbyWakeLatch(uint8 *sourceMask, uint8 *pmsWakeFlags, uint8 *scrWakeReason)
{
    *sourceMask = 0u;
    *pmsWakeFlags = 0u;
    *scrWakeReason = 0u;
    SafetyKit_StandbyWakeLatchValid = 0u;
    SafetyKit_StandbyWakeLatchSourceMask = 0u;
    SafetyKit_StandbyWakeLatchPmsWstat2 = 0u;
    SafetyKit_StandbyWakeLatchScrReason = 0u;
    return FALSE;
}

boolean safetyKitEvaluateStandby(void)
{
    static boolean standbyEvaluated = FALSE;
    static boolean comingFromStandby = FALSE;

    if(standbyEvaluated == FALSE)
    {
        uint32 pmsWstat2 = PMS_PMSWSTAT2.U;
        uint32 wakeFlags;
        uint8 scrWakeReason = 0u;
        uint8 retainedStandbyWake = McuSm_SswStatusData.wakeupFromStandby;
        uint8 latchSourceMask = 0u;
        uint8 latchPmsWakeFlags = 0u;
        uint8 latchScrWakeReason = 0u;
        boolean latchValid;
        uint32 sourceMask = 0u;

        /* Standby wake capture extension is disabled while using the older McuSm variant. */
        wakeFlags = pmsWstat2 & SCR_STANDBY_WAKE_PMSWSTAT2_WAKE_FLAGS_MASK;

        if ((McuSm_Trap4ScrRtcRecordValid != FALSE) &&
                ((McuSm_Trap4ScrRtcRecord[SCR_TIME_OFFSET_FLAGS] & SCR_TIME_FLAG_ARMED) != 0u) &&
                ((McuSm_Trap4ScrRtcRecord[SCR_TIME_OFFSET_FLAGS] & SCR_TIME_FLAG_CONSUMED) == 0u))
        {
            scrWakeReason = McuSm_Trap4ScrRtcRecord[SCR_TIME_OFFSET_WAKE_REASON];
        }
        else
        {
            /* Do nothing. */
        }

        if (wakeFlags != 0u)
        {
            sourceMask |= SCR_STANDBY_WAKE_SOURCE_PMS;
        }
        else
        {
            /* Do nothing. */
        }

        if (scrWakeReason != 0u)
        {
            sourceMask |= SCR_STANDBY_WAKE_SOURCE_SCR_XRAM;
        }
        else
        {
            /* Do nothing. */
        }

        if ((retainedStandbyWake != 0u) &&
                (MODULE_SCU.RSTSTAT.B.LBTERM != 0u) &&
                (McuSm_SswStatusData.lbistAppSwReq != 0u))
        {
            sourceMask |= SAFETYKIT_STANDBY_WAKE_SOURCE_LBIST_RETAINED;
        }
        else
        {
            /* Do nothing. */
        }

        latchValid = safetyKitReadStandbyWakeLatch(
                &latchSourceMask,
                &latchPmsWakeFlags,
                &latchScrWakeReason);
        if (latchValid != FALSE)
        {
            sourceMask |= (uint32)latchSourceMask;
            sourceMask |= SAFETYKIT_STANDBY_WAKE_SOURCE_SCR_LATCH;
        }
        else
        {
            /* Do nothing. */
        }

        comingFromStandby = (sourceMask != 0u) ? TRUE : FALSE;
        McuSm_SswStatusData.wakeupFromStandby = (comingFromStandby != FALSE) ? 1u : 0u;

        SafetyKit_StandbyWakeRawPmsWstat2 = pmsWstat2;
        SafetyKit_StandbyWakeScrReason = scrWakeReason;
        SafetyKit_StandbyWakeRetained = retainedStandbyWake;
        SafetyKit_StandbyWakeSourceMask = sourceMask;

        safetyKitClearStandbyWakeFlags(wakeFlags);
        standbyEvaluated = TRUE;
    }
    else
    {
        /* Do nothing. */
    }

    return comingFromStandby;
}
/*
 * Triggering a Warm PORST via the LBIST.
 * Note: As stated in Errata BROM_TC.H017 : "In AURIX™ TC3xx devices, LBIST execution terminates [..]
 * with a warm reset." but
 * "The Startup Software executed afterwards follows the flow as after cold power-on [..]"
 * */
void safetyKitTriggerWarmPorst(void)
{
    safetyKitTriggerLbist();
    /* Note: MCU_FW_CHECK (safetyKitSswMcuFwCheck()) will fail, as FW_CHECK compares expected register
     * values as if no LBIST was executed before. */
}
