/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC37XPD
 * - package : LQFP176
 */

#include "aurix_pin_mappings.h"


/* ASCLIN1 pin configuration */

static const IfxPort_Io_ConfigPin asclin1_pin_table[] = 
{
    IFXCFG_P15_0_IO_CONFIG,
    IFXCFG_P15_1_IO_CONFIG
};

static const IfxPort_Io_Config asclin1_io_config_table = 
{
    sizeof(asclin1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin1_pin_table
};

extern void asclin1_init_pins(void)
{
    IfxPort_Io_initModule(&asclin1_io_config_table);
}


/* CAN0_NODE0 pin configuration */

static const IfxPort_Io_ConfigPin can0_node0_pin_table[] = 
{
    IFXCFG_P20_7_IO_CONFIG,
    IFXCFG_P20_8_IO_CONFIG
};

static const IfxPort_Io_Config can0_node0_io_config_table = 
{
    sizeof(can0_node0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node0_pin_table
};

extern void can0_node0_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node0_io_config_table);
}


/* CAN0_NODE1 pin configuration */

static const IfxPort_Io_ConfigPin can0_node1_pin_table[] = 
{
    IFXCFG_P33_9_IO_CONFIG,
    IFXCFG_P33_10_IO_CONFIG
};

static const IfxPort_Io_Config can0_node1_io_config_table = 
{
    sizeof(can0_node1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node1_pin_table
};

extern void can0_node1_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node1_io_config_table);
}

