/*********************************************************************************************************************
* ACS APP Name : LWIP_GETH       APP Version: 4.0.4
*
* NOTE:
* This file is generated by ACS. Any manual modification done to this file will be lost when the code is regenerated.
*********************************************************************************************************************/

/**
 * @file lwipopts.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 *
 */
#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

#ifdef __cplusplus
extern "C" {
#endif

#define NO_SYS                              1
#define LWIP_SOCKET                         0
#define LWIP_NETCONN                        0
#define SYS_LIGHTWEIGHT_PROT                0
#define SO_REUSE                            0

#define LWIP_NETIF_HOSTNAME                 0
#define LWIP_NETIF_STATUS_CALLBACK          0
#define LWIP_NETIF_LINK_CALLBACK            1
#define ETH_PAD_SIZE                        2
#define TCP_LISTEN_BACKLOG                  1
#define LWIP_SO_RCVTIMEO                    1
#define MEM_SIZE                            1600
#define PBUF_POOL_SIZE                      16
#define PBUF_POOL_BUFSIZE                   256
#define MEMP_NUM_PBUF                       16
#define MEMP_NUM_RAW_PCB                    4
#define MEM_ALIGNMENT                       8

#define LWIP_UDP                            1
#define MEMP_NUM_UDP_PCB                    4

#define LWIP_TCP                            1
#define MEMP_NUM_TCP_PCB                    5
#define MEMP_NUM_TCP_PCB_LISTEN             5
#define MEMP_NUM_TCP_SEG                    8
#define TCP_MSS                             536
#define TCP_WND                             2144
#define TCP_SND_BUF                         1072
#define TCP_SND_QUEUELEN                    8

#define LWIP_DHCP                           0

#define LWIP_ARP                            1
#define ARP_TABLE_SIZE                      10
#define MEMP_NUM_ARP_QUEUE                  30

#define LWIP_AUTOIP                         0

#define LWIP_ICMP                           1

#define LWIP_IGMP                           0

#define LWIP_DNS                            0

#define LWIP_SNMP                           0

#define IP_OPTIONS_ALLOWED                  0

#define IP_FRAG                             0

#define IP_REASSEMBLY                       0

#define LWIP_GETH_DEBUG_ENABLED             0

#define IP_DEFAULT_TTL                      255

#define CHECKSUM_GEN_IP                     0
#define CHECKSUM_GEN_UDP                    0
#define CHECKSUM_GEN_TCP                    0
#define CHECKSUM_GEN_ICMP                   0
#define CHECKSUM_CHECK_IP                   0
#define CHECKSUM_CHECK_UDP                  0
#define CHECKSUM_CHECK_TCP                  0

#define LWIP_RAW                            1

#define MEMP_NUM_SYS_TIMEOUT                (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 8)

#ifdef __cplusplus
}
#endif

#endif /* __LWIPOPTS_H__ */

/* CODE_BLOCK_END */

