################################################################################
# User build hooks.
################################################################################

UCB_FILTER_SCRIPT := ../../../Scripts/Build/filter_ihex_ranges.ps1
UCB_FILTER_RANGE := 0xAF400000-0xAF405FFF

ifeq ($(BUILD_ARTIFACT_NAME),ZGW_FBL)

main-build: ZGW_FBL_edited.hex

ZGW_FBL_edited.hex: ZGW_FBL.elf $(UCB_FILTER_SCRIPT)
	@echo 'Filtering UCB range from ZGW_FBL.hex -> ZGW_FBL_edited.hex'
	powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(UCB_FILTER_SCRIPT)" -InputPath "ZGW_FBL.hex" -OutputPath "ZGW_FBL_edited.hex" -ExcludeRange "$(UCB_FILTER_RANGE)"
	@echo ' '

clean: clean-edited-hex

clean-edited-hex:
	-$(RM) ZGW_FBL_edited.hex
	-@echo ' '

.PHONY: clean-edited-hex

endif
