/**********************************************************************************************************************
 * \file SCR.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SCR.h"
#include "IfxCpu_Intrinsics.h"
#include "IfxPms_reg.h"
#include "IfxScuWdt.h"
#include "SCR_AURIX_TC3x.h"

#define IFXSCR_PMSWSTATCLR_SCRSTCLR_MASK 0x00010000u
#define IFXSCR_PMSWCR4_SCR_DISABLE_MASK  0x01000000u
#define IFXSCR_PMSWCR4_SCR_ENABLE_MASK   0x03000000u
#define IFXSCR_PMSWCR0_SCRWKEN_MASK      0x20000000u

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static uint8 IfxScr_clearSafetyEndinitIfSet(uint16 safetyWdtPw)
{
    uint8 safetyEndinitWasSet = (IfxScuWdt_getSafetyWatchdogEndInit() != 0u) ? 1u : 0u;

    if(safetyEndinitWasSet != 0u)
    {
        IfxScuWdt_clearSafetyEndinit(safetyWdtPw);
    }

    return safetyEndinitWasSet;
}

static void IfxScr_restoreSafetyEndinitIfNeeded(uint16 safetyWdtPw, uint8 safetyEndinitWasSet)
{
    if(safetyEndinitWasSet != 0u)
    {
        IfxScuWdt_setSafetyEndinit(safetyWdtPw);
    }
}

static void IfxScr_writePmsWcr4(uint32 value)
{
    uint16 safetyWdtPw = IfxScuWdt_getSafetyWatchdogPassword();
    uint8 safetyEndinitWasSet = IfxScr_clearSafetyEndinitIfSet(safetyWdtPw);

    PMS_PMSWCR4.U = value;
    __dsync();
    IfxScr_restoreSafetyEndinitIfNeeded(safetyWdtPw, safetyEndinitWasSet);
}

static void IfxScr_setPmsWcr4Bits(uint32 mask)
{
    uint16 safetyWdtPw = IfxScuWdt_getSafetyWatchdogPassword();
    uint8 safetyEndinitWasSet = IfxScr_clearSafetyEndinitIfSet(safetyWdtPw);

    PMS_PMSWCR4.U |= mask;
    __dsync();
    IfxScr_restoreSafetyEndinitIfNeeded(safetyWdtPw, safetyEndinitWasSet);
}

static void IfxScr_setPmsWcr0Bits(uint32 mask)
{
    uint16 safetyWdtPw = IfxScuWdt_getSafetyWatchdogPassword();
    uint8 safetyEndinitWasSet = IfxScr_clearSafetyEndinitIfSet(safetyWdtPw);

    PMS_PMSWCR0.U |= mask;
    __dsync();
    IfxScr_restoreSafetyEndinitIfNeeded(safetyWdtPw, safetyEndinitWasSet);
}

static uint8 IfxScr_clearResetStatusIfSet(void)
{
    if(PMS_PMSWSTAT.B.SCRST != 0u)
    {
        uint16 safetyWdtPw = IfxScuWdt_getSafetyWatchdogPassword();
        uint8 safetyEndinitWasSet = IfxScr_clearSafetyEndinitIfSet(safetyWdtPw);

        PMS_PMSWSTATCLR.U = IFXSCR_PMSWSTATCLR_SCRSTCLR_MASK;
        __dsync();
        IfxScr_restoreSafetyEndinitIfNeeded(safetyWdtPw, safetyEndinitWasSet);
        return 1u;
    }

    return 0u;
}

void IfxScr_copyProgram(void)
{
    do
    {
        volatile uint8* addr = ((volatile uint8*)PMS_XRAM);
        volatile uint16* addr16 = ((volatile uint16*)(0xF0241FF8));

        (void)IfxScr_clearResetStatusIfSet();

        /* TC37x Erratum SCR_TC.019: retry SCR XRAM program copy if SCR reset overlaps it. */
        for (uint16 addrOffset = 0; addrOffset < SIZE_scr_xram; addrOffset++)
        {
            *addr = scr_xram[addrOffset];
            addr++;
        }

        for(uint8 i = 0; i < 4; i++){
            *(addr16 + i) = 0xAA55;
        }
    } while(IfxScr_clearResetStatusIfSet() != 0u);
}

void IfxScr_disableSCR(void)
{
    /* Disable SCR and disable 100MHz clock */
    IfxScr_writePmsWcr4(IFXSCR_PMSWCR4_SCR_DISABLE_MASK);
    /* Confirm SCR is disabled */
    while(PMS_PMSWSTAT.B.SCR)
    {
    }
}

void IfxScr_enableSCR(void)
{
    IfxScr_setPmsWcr4Bits(IFXSCR_PMSWCR4_SCR_ENABLE_MASK);

    /* SCR wake-up enable */
    IfxScr_setPmsWcr0Bits(IFXSCR_PMSWCR0_SCRWKEN_MASK);
    /* Confirm that SCR is enabled */
    while(!PMS_PMSWSTAT.B.SCR)
    {
    }
}

void IfxScr_init(uint8 boot_mode)
{
    IfxScr_setPmsWcr4Bits(0x3u | ((uint32)boot_mode << 16u));
    /* Wait for SCR to be reset */
    while(!PMS_PMSWSTAT.B.SCRST)
    {
    }
    /* TC37x Erratum SCR_TC.019: clear SCR reset status with a 32-bit status write. */
    (void)IfxScr_clearResetStatusIfSet();

    /* The SCR should have booted up by and have status 0x80 */
    while(PMS_PMSWCR2.B.SCRINT != 0x80)
    {
    }
}

