#include "Fee_Cfg.h"
#include "NvM_Cfg.h"

const Fee_BlockConfigType Fee_BlockConfig[FEE_CONFIGURED_BLOCKS] =
{
    {
        NVM_BLOCK_ID_DEM_PRIMARY,
        NVM_BLOCK_DEM_PRIMARY_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_APP_DATA,
        NVM_BLOCK_APP_DATA_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_TIMEBASE,
        NVM_BLOCK_TIMEBASE_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_ETH_STARTUP_TIMING,
        NVM_BLOCK_ETH_STARTUP_TIMING_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_NVM_TIMING,
        NVM_BLOCK_NVM_TIMING_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_MCU_STATUS,
        NVM_BLOCK_MCU_STATUS_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_AIMODEL,
        NVM_BLOCK_AIMODEL_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    },
    {
        NVM_BLOCK_ID_NVM_STATS,
        NVM_BLOCK_NVM_STATS_LENGTH,
        FEE_BLOCK_NATIVE,
        FALSE
    }
};
