/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/* Use dedicated register files dependent on the used compiler */
#include "Scr_Io_sdcc.h"
#include "scr_scu_sdcc.h"
#include "scr_wcan_sdcc.h"
#include "scr_irq_sdcc.h"
#include "scr_rtc_sdcc.h"
#include "scr_wdt_sdcc.h"
#include "scr_common.h"
#include "scr_time_shared.h"

#define MaskWCANRXDIS   (0x0Fu)
#define SetWCANRXDA     (0x00u)
#define SetWCANRXDD     (0x03u)

#define CANFD_RXD_PIN_MASK             (0x20u)

#define WCAN_INT_ENABLE_WUF_ONLY       (0x04u)
#define WCAN_STATUS0_SWACK_MASK        (0x01u)
#define WCAN_STATUS1_WUF_MASK          (0x01u)
#define WCAN_STATUS1_SYNC_MASK         (0x02u)
#define WCAN_STATUS1_FDF_MASK          (0x10u)
#define WCAN_STATUS0_CLEAR_MASK        (0xFCu)
#define WCAN_STATUS1_CLEAR_MASK        (0x0Bu)

#define WCAN_CFG_WCAN_EN               (0x01u)
#define WCAN_CFG_SELWK_EN              (0x04u)
#define WCAN_CFG_CCE                   (0x08u)

/* Standard ID 0x90 is stored shifted by 18; mask bits 3:2 to accept 0x90..0x93. */
#define WCAN_WAKE_ID2_VALUE            (0x40u)
#define WCAN_WAKE_ID3_VALUE            (0x08u)
#define WCAN_WAKE_ID2_MASK             (0xF3u)
#define WCAN_WAKE_ID3_MASK             (0x7Du)
#define WCAN_WAKE_DLC_VALUE            (0x08u)

/*
 * The 0x90..0x93 messages in the CANFD DBC are StandardCAN_FD frames. WCAN does not expose the FD frame ID to
 * SCR software, so valid-frame detection is used as the CAN FD fallback while WUF remains the ID-filtered classic CAN
 * path. SYNC requires a CAN frame without a decode error and avoids waking on raw RXD disturbances/error frames.
 */
#define WCAN_WAKE_ON_FD_FRAME          (1u)
#define WCAN_WAKE_ON_SYNC_FRAME        (1u)

#define WCAN_WAKE_REASON_WUF           SCR_TIME_WAKE_REASON_WCAN_WUF
#define WCAN_WAKE_REASON_SYNC          SCR_TIME_WAKE_REASON_WCAN_SYNC
#define WCAN_WAKE_REASON_FDF           SCR_TIME_WAKE_REASON_WCAN_FDF
#define WCAN_INIT_SWACK_CLEAR_TIMEOUT  (0x01u)
#define WCAN_INIT_SWACK_SET_TIMEOUT    (0x02u)
#define WCAN_SWACK_WAIT_LIMIT          (0xFFFFu)

#define SCR_FAULT_REASON_ECC_DBE       SCR_TIME_WAKE_REASON_ECC_DBE
#define SCR_FAULT_REASON_WDT           SCR_TIME_WAKE_REASON_WDT
#define SCR_FAULT_STATUS_ECC_DBE       SCR_TIME_FAULT_STATUS_ECC_DBE
#define SCR_FAULT_STATUS_WDT           SCR_TIME_FAULT_STATUS_WDT
#define SCR_FAULT_NMISR_MASK           (0x03u)
#define SCR_FAULT_RSTST_MASK           (ECCRST_MASK | WDTRST_MASK)
#define SCR_NMICON_WDT_MASK            (0x01u)
#define SCR_NMICON_RAMECC_MASK         (0x02u)
#define SCR_NMICON_WAKE_MASK           (0x40u)

/*
 * With DIV5 the SCR PCLK is 20 MHz. WDTIN selects the divided watchdog input
 * clock; 0xC3 gives approximately 100 ms for the 16-bit WDT reload path.
 */
#define SCR_WDT_RELOAD_100MS           (0xC3u)

#define G_COUNTER_ADDR    ((volatile __xdata uint8 *)0x1760u)
#define G_WCAN_STAT0_ADDR ((volatile __xdata uint8 *)0x1761u)
#define G_WCAN_STAT1_ADDR ((volatile __xdata uint8 *)0x1762u)
#define G_P00_IN_ADDR     ((volatile __xdata uint8 *)0x1763u)
#define G_RX_LOW_COUNT_ADDR ((volatile __xdata uint8 *)0x1764u)
#define G_WAKE_REASON_ADDR  ((volatile __xdata uint8 *)0x1765u)
#define G_WCAN_INIT_ADDR    ((volatile __xdata uint8 *)0x1766u)
#define G_STDBYWKP_ADDR     ((volatile __xdata uint8 *)0x1767u)
#define G_FDF_BASELINE_ADDR ((volatile __xdata uint8 *)0x1768u)
#define G_BOOT_STAGE_ADDR   ((volatile __xdata uint8 *)0x1769u)

#define d1   ((volatile __xdata uint8 *)0x1800u)
#define d2   ((volatile __xdata uint8 *)0x1801u)

#define BOOT_STAGE_MAIN_ENTRY          (0x11u)
#define BOOT_STAGE_CLOCK_SET           (0x12u)
#define BOOT_STAGE_WCAN_INIT_ENTRY     (0x21u)
#define BOOT_STAGE_WCAN_PIN_CFG        (0x22u)
#define BOOT_STAGE_WCAN_WAKE_CFG       (0x23u)
#define BOOT_STAGE_WCAN_CLOCK_ENABLED  (0x24u)
#define BOOT_STAGE_WCAN_PIN_SELECTED   (0x25u)
#define BOOT_STAGE_WCAN_CFG_WRITTEN    (0x26u)
#define BOOT_STAGE_WCAN_BITTIMING      (0x27u)
#define BOOT_STAGE_SWACK_CLEAR_DONE    (0x28u)
#define BOOT_STAGE_WUF_CFG_DONE        (0x29u)
#define BOOT_STAGE_SWACK_SET_DONE      (0x2Au)
#define BOOT_STAGE_WCAN_INIT_DONE      (0x2Bu)
#define BOOT_STAGE_LOOP_RUNNING        (0x40u)
#define BOOT_STAGE_LOOP_TIME_DONE      (0x41u)
#define BOOT_STAGE_LOOP_FAULT_DONE     (0x42u)
#define BOOT_STAGE_LOOP_WDT_DONE       (0x43u)
#define BOOT_STAGE_LOOP_WCAN_DONE      (0x44u)
#define BOOT_STAGE_TIME_UPDATE_ENTRY   (0x50u)
#define BOOT_STAGE_TIME_COUNTER_READ   (0x51u)
#define BOOT_STAGE_TIME_TICKS_STORED   (0x52u)
#define BOOT_STAGE_TIME_FLAGS_READ     (0x53u)
#define BOOT_STAGE_TIME_ELAPSED_STORED (0x54u)
#define BOOT_STAGE_TIME_CURRENT_STORED (0x55u)
#define BOOT_STAGE_TIME_UPDATE_DONE    (0x56u)

#define SCR_TIME_INIT_STATUS_ENTERED       (0x10u)
#define SCR_TIME_INIT_STATUS_MAGIC_FAIL    (0xE1u)
#define SCR_TIME_INIT_STATUS_VERSION_FAIL  (0xE2u)
#define SCR_TIME_INIT_STATUS_VALID_FAIL    (0xE3u)
#define SCR_TIME_INIT_STATUS_ARMED_FAIL    (0xE4u)
#define SCR_TIME_INIT_STATUS_ACTIVE        (0xA5u)

static __xdata uint32 SCR_TimeBaseUtcHigh;
static __xdata uint32 SCR_TimeBaseUtcLow;
static __xdata uint32 SCR_TimeBaseVehicleHigh;
static __xdata uint32 SCR_TimeBaseVehicleLow;
static __xdata uint32 SCR_TimeProductLow;
static __xdata uint32 SCR_TimeProductHigh;
static __xdata uint32 SCR_TimeElapsedLow;
static __xdata uint32 SCR_TimeElapsedHigh;
static __xdata uint32 SCR_TimeCurrentLow;
static __xdata uint32 SCR_TimeCurrentHigh;
static uint8 SCR_TimeBaseActive = 0u;

#if (SCR_TIME_USE_RTC_INTERRUPT != 0u)
static __xdata uint32 SCR_TotalElapsedTicks;
#endif

#if (SCR_TIME_USE_WDT_FALLBACK != 0u)
static __xdata uint32 SCR_WdtAccumTicks;
static __xdata uint16 SCR_WdtPrevCount;
#endif

static volatile __xdata uint8 *SCR_TimeAddr(uint8 offset)
{
    return (volatile __xdata uint8 *)(SCR_TIME_XRAM_BASE + offset);
}

static uint8 SCR_TimeLoadU8(uint8 offset)
{
    return *SCR_TimeAddr(offset);
}

static void SCR_TimeStoreU8(uint8 offset, uint8 value)
{
    *SCR_TimeAddr(offset) = value;
}

static uint32 SCR_TimeLoadU32(uint8 offset)
{
    uint32 value;

    value = ((uint32)SCR_TimeLoadU8(offset) << 24);
    value |= ((uint32)SCR_TimeLoadU8((uint8)(offset + 1u)) << 16);
    value |= ((uint32)SCR_TimeLoadU8((uint8)(offset + 2u)) << 8);
    value |= (uint32)SCR_TimeLoadU8((uint8)(offset + 3u));

    return value;
}

static void SCR_TimeStoreU32(uint8 offset, uint32 value)
{
    SCR_TimeStoreU8(offset, (uint8)(value >> 24));
    SCR_TimeStoreU8((uint8)(offset + 1u), (uint8)(value >> 16));
    SCR_TimeStoreU8((uint8)(offset + 2u), (uint8)(value >> 8));
    SCR_TimeStoreU8((uint8)(offset + 3u), (uint8)value);
}

static void SCR_TimeStoreBasePlusElapsedNs(
        uint8 offset,
        uint32 baseHigh,
        uint32 baseLow,
        uint32 elapsedTicks)
{
    SCR_TimeProductLow = (elapsedTicks & 0xFFFFu) * (uint32)SCR_TIME_RTC_TICK_NS;
    SCR_TimeProductHigh = (elapsedTicks >> 16u) * (uint32)SCR_TIME_RTC_TICK_NS;
    SCR_TimeElapsedLow = SCR_TimeProductLow + (SCR_TimeProductHigh << 16u);
    SCR_TimeElapsedHigh = (SCR_TimeProductHigh >> 16u);
    if (SCR_TimeElapsedLow < SCR_TimeProductLow)
    {
        SCR_TimeElapsedHigh++;
    }

    SCR_TimeCurrentLow = baseLow + SCR_TimeElapsedLow;
    SCR_TimeCurrentHigh = baseHigh + SCR_TimeElapsedHigh;
    if (SCR_TimeCurrentLow < baseLow)
    {
        SCR_TimeCurrentHigh++;
    }

    SCR_TimeStoreU32(offset, SCR_TimeCurrentHigh);
    SCR_TimeStoreU32((uint8)(offset + 4u), SCR_TimeCurrentLow);
}

#if (SCR_TIME_USE_WDT_FALLBACK != 0u)
static void SCR_WdtAccumUpdate(void)
{
    uint16 current = ((uint16)SCR_WDT_H << 8) | (uint16)SCR_WDT_L;
    if (current >= SCR_WdtPrevCount)
    {
        SCR_WdtAccumTicks += (uint32)(current - SCR_WdtPrevCount);
    }
    SCR_WdtPrevCount = current;
}
#endif

static uint32 SCR_RtcReadCounter(void)
{
    uint8 cnt3Before;
    uint8 cnt3After;
    uint8 cnt2Before;
    uint8 cnt2After;
    uint8 cnt1Before;
    uint8 cnt1After;
    uint8 cnt2;
    uint8 cnt1;
    uint8 cnt0;

    do
    {
        cnt3Before = SCR_RTC_CNT3;
        cnt2Before = SCR_RTC_CNT2;
        cnt1Before = SCR_RTC_CNT1;
        cnt0 = SCR_RTC_CNT0;
        cnt3After = SCR_RTC_CNT3;
        cnt2After = SCR_RTC_CNT2;
        cnt1After = SCR_RTC_CNT1;
    } while((cnt3Before != cnt3After) ||
            (cnt2Before != cnt2After) ||
            (cnt1Before != cnt1After));

    cnt2 = cnt2After;
    cnt1 = cnt1After;

    return (((uint32)cnt3After << 24) |
            ((uint32)cnt2 << 16) |
            ((uint32)cnt1 << 8) |
            (uint32)cnt0);
}

/*
 * XINTR13 — RTC compare-match ISR (vector 0x6B).
 * Fires every SCR_TIME_RTC_COMPARE_TICKS ticks (≈100 ms at 39,062.5 Hz PCLK/512).
 *
 * Owns all shared-XRAM timestamp writes; SCR_TimeUpdate() in the main loop is
 * reduced to debug-register reads and must not write ELAPSED/UTC/VEHICLE_NS.
 */
#if (SCR_TIME_USE_RTC_INTERRUPT != 0u)
void SCR_RtcCompareIsr(void) __interrupt(XINTR13)
{
    uint8 flags;

    /*
     * Within one protection window: clear CFRTC (write 0 to bit 6), stop the
     * RTC (clear RTCC), reset the 32-bit counter to zero by writing each CNT
     * byte directly (counter is safely stopped), then restart (set RTCC).
     */
    SCR_UNLOCK_PROTECTED_BITS();
    SCR_RTC_CON &= (uint8)(~CFRTC_MASK);
    SCR_RTC_CON &= (uint8)(~RTCC_MASK);
    SCR_RTC_CNT3 = 0u;
    SCR_RTC_CNT2 = 0u;
    SCR_RTC_CNT1 = 0u;
    SCR_RTC_CNT0 = 0u;
    SCR_RTC_CON |= RTCC_MASK;
    SCR_LOCK_PROTECTED_BITS();

    SCR_TotalElapsedTicks += (uint32)SCR_TIME_RTC_COMPARE_TICKS;

    SCR_TimeStoreU32(SCR_TIME_OFFSET_RTC_LAST_TICKS, SCR_TotalElapsedTicks);
    SCR_TimeStoreU32(SCR_TIME_OFFSET_ELAPSED_TICKS,  SCR_TotalElapsedTicks);

    flags = SCR_TimeLoadU8(SCR_TIME_OFFSET_FLAGS);
    if (((flags & SCR_TIME_FLAG_ARMED) != 0u) && (SCR_TimeBaseActive != 0u))
    {
        SCR_TimeStoreBasePlusElapsedNs(
                SCR_TIME_OFFSET_UTC_NS,
                SCR_TimeBaseUtcHigh,
                SCR_TimeBaseUtcLow,
                SCR_TotalElapsedTicks);
        SCR_TimeStoreBasePlusElapsedNs(
                SCR_TIME_OFFSET_VEHICLE_NS,
                SCR_TimeBaseVehicleHigh,
                SCR_TimeBaseVehicleLow,
                SCR_TotalElapsedTicks);
    }
}
#endif

static void SCR_TimeInit(void)
{
    uint8 flags;

    SCR_TimeBaseActive = 0u;

    flags = SCR_TimeLoadU8(SCR_TIME_OFFSET_FLAGS);

    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_INIT_STATUS, SCR_TIME_INIT_STATUS_ENTERED);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_FLAGS_READ, flags);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_MAGIC0_READ, SCR_TimeLoadU8(SCR_TIME_OFFSET_MAGIC));
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_MAGIC1_READ, SCR_TimeLoadU8((uint8)(SCR_TIME_OFFSET_MAGIC + 1u)));
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_MAGIC2_READ, SCR_TimeLoadU8((uint8)(SCR_TIME_OFFSET_MAGIC + 2u)));
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_MAGIC3_READ, SCR_TimeLoadU8((uint8)(SCR_TIME_OFFSET_MAGIC + 3u)));
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_VERSION_READ, SCR_TimeLoadU8(SCR_TIME_OFFSET_VERSION));
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_VALID_READ, SCR_TimeLoadU8(SCR_TIME_OFFSET_VALID));

    /*
     * Enable RTC module and keep RTC running during debug suspend.
     */
    SCR_UNLOCK_PROTECTED_BITS();
    SCR_SCU_PAGE = MOD_PAGE_1;
    SCR_SCU_PMCON1 &= (uint8)(~RTC_DIS_MASK);
    SCR_SCU_DBG_MODSUSP &= (uint8)(~RTCSUSP_MASK);
    SCR_LOCK_PROTECTED_BITS();

    /*
     * Configure RTC while stopped.
     *
     * Required final running mode:
     *   SCR fSYS = 20 MHz from Scr_set_fsys(DIV5)
     *   RTCCLKSEL = 1
     *   RTPBYP    = 1
     *   ECRTC     = 1
     *   RTCC      = 1 only after Scr_start_rtc()
     *
     * Therefore:
     *   RTC tick = 50 ns
     *   100 ms = 2,000,000 ticks
     */
    SCR_UNLOCK_PROTECTED_BITS();

    Scr_stop_rtc();

    SCR_RTC_CON = 0u;
    SCR_RTC_CON = (uint8)(RTCCLKSEL_MASK | RTPBYP_MASK | ECRTC_MASK);

    SCR_RTC_CNT3 = 0u;
    SCR_RTC_CNT2 = 0u;
    SCR_RTC_CNT1 = 0u;
    SCR_RTC_CNT0 = 0u;

    SCR_RTC_CR3 = (uint8)((uint32)SCR_TIME_RTC_COMPARE_TICKS >> 24);
    SCR_RTC_CR2 = (uint8)((uint32)SCR_TIME_RTC_COMPARE_TICKS >> 16);
    SCR_RTC_CR1 = (uint8)((uint32)SCR_TIME_RTC_COMPARE_TICKS >> 8);
    SCR_RTC_CR0 = (uint8)(SCR_TIME_RTC_COMPARE_TICKS);

    SCR_RTC_CON &= (uint8)(~CFRTC_MASK);

    SCR_LOCK_PROTECTED_BITS();

    if (SCR_TimeLoadU32(SCR_TIME_OFFSET_MAGIC) != SCR_TIME_MAGIC)
    {
        SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_INIT_STATUS, SCR_TIME_INIT_STATUS_MAGIC_FAIL);
    }
    else if (SCR_TimeLoadU8(SCR_TIME_OFFSET_VERSION) != SCR_TIME_VERSION)
    {
        SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_INIT_STATUS, SCR_TIME_INIT_STATUS_VERSION_FAIL);
    }
    else if (SCR_TimeLoadU8(SCR_TIME_OFFSET_VALID) != SCR_TIME_VALID)
    {
        SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_INIT_STATUS, SCR_TIME_INIT_STATUS_VALID_FAIL);
    }
    else if ((flags & SCR_TIME_FLAG_ARMED) == 0u)
    {
        SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_INIT_STATUS, SCR_TIME_INIT_STATUS_ARMED_FAIL);
    }
    else
    {
        SCR_TimeBaseUtcHigh = SCR_TimeLoadU32(SCR_TIME_OFFSET_UTC_NS);
        SCR_TimeBaseUtcLow = SCR_TimeLoadU32((uint8)(SCR_TIME_OFFSET_UTC_NS + 4u));
        SCR_TimeBaseVehicleHigh = SCR_TimeLoadU32(SCR_TIME_OFFSET_VEHICLE_NS);
        SCR_TimeBaseVehicleLow = SCR_TimeLoadU32((uint8)(SCR_TIME_OFFSET_VEHICLE_NS + 4u));

        SCR_TimeBaseActive = 1u;

#if (SCR_TIME_USE_RTC_INTERRUPT != 0u)
        SCR_TotalElapsedTicks = 0u;
#elif (SCR_TIME_USE_WDT_FALLBACK != 0u)
        SCR_WdtAccumTicks = 0u;
        SCR_WdtPrevCount = ((uint16)SCR_WDT_H << 8) | (uint16)SCR_WDT_L;
#endif

        SCR_TimeStoreU32(SCR_TIME_OFFSET_RTC_START_TICKS, 0u);
        SCR_TimeStoreU32(SCR_TIME_OFFSET_RTC_LAST_TICKS, 0u);
        SCR_TimeStoreU32(SCR_TIME_OFFSET_ELAPSED_TICKS, 0u);
        SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_INIT_STATUS, SCR_TIME_INIT_STATUS_ACTIVE);
    }

    /*
     * Start RTC only after counter and compare registers are valid.
     * Running SCR_RTC_CON shall become 0x17.
     */
    SCR_UNLOCK_PROTECTED_BITS();
    Scr_start_rtc();
    SCR_LOCK_PROTECTED_BITS();

#if (SCR_TIME_USE_RTC_INTERRUPT != 0u)
    if (SCR_TimeBaseActive != 0u)
    {
        SCR_IEN1 |= (uint8)(1u << 7u);  /* IEN1.ECCIP3: enable XINTR13 RTC */
        SCR_IEN0_EA = 1u;               /* global interrupt enable */
    }
#endif

    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_RTC_CON, SCR_RTC_CON);

    SCR_SCU_PAGE = MOD_PAGE_1;
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_PMCON1, SCR_SCU_PMCON1);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_TIME_ACTIVE, SCR_TimeBaseActive);
}

static void SCR_TimeUpdate(void)
{
#if (SCR_TIME_USE_RTC_INTERRUPT == 0u)
    uint32 counter;
    uint32 startCounter;
    uint32 elapsedTicks;
#endif
    uint8 flags;

    *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_UPDATE_ENTRY;

#if (SCR_TIME_USE_RTC_INTERRUPT != 0u)
    /* SCR_RtcCompareIsr() owns all timestamp writes; nothing to do here. */
#elif (SCR_TIME_USE_WDT_FALLBACK != 0u)
    SCR_WdtAccumUpdate();
    counter = SCR_WdtAccumTicks;
#else
    counter = SCR_RtcReadCounter();
#endif

    *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_COUNTER_READ;
#if (SCR_TIME_USE_RTC_INTERRUPT == 0u)
    SCR_TimeStoreU32(SCR_TIME_OFFSET_RTC_LAST_TICKS, counter);
#endif
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_TICKS_STORED;

    /* Debug register snapshots — always written, safe: offsets 44-58 are ISR-free. */
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_RTC_CON,   SCR_RTC_CON);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_RTC_CNT0,  SCR_RTC_CNT0);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_RTC_CNT1,  SCR_RTC_CNT1);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_RTC_CNT2,  SCR_RTC_CNT2);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_RTC_CNT3,  SCR_RTC_CNT3);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_TIME_ACTIVE, SCR_TimeBaseActive);

    flags = SCR_TimeLoadU8(SCR_TIME_OFFSET_FLAGS);
    SCR_TimeStoreU8(SCR_TIME_OFFSET_DEBUG_FLAGS_READ, flags);
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_FLAGS_READ;
    if ((flags & SCR_TIME_FLAG_ARMED) != 0u)
    {
        (*d1)++;
#if (SCR_TIME_USE_RTC_INTERRUPT == 0u)
        startCounter = SCR_TimeLoadU32(SCR_TIME_OFFSET_RTC_START_TICKS);
        elapsedTicks  = counter - startCounter;
        SCR_TimeStoreU32(SCR_TIME_OFFSET_ELAPSED_TICKS, elapsedTicks);
        *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_ELAPSED_STORED;
#endif
        if (SCR_TimeBaseActive != 0u)
        {
            (*d2)++;
#if (SCR_TIME_USE_RTC_INTERRUPT == 0u)
            SCR_TimeStoreBasePlusElapsedNs(
                    SCR_TIME_OFFSET_UTC_NS,
                    SCR_TimeBaseUtcHigh,
                    SCR_TimeBaseUtcLow,
                    elapsedTicks);
            SCR_TimeStoreBasePlusElapsedNs(
                    SCR_TIME_OFFSET_VEHICLE_NS,
                    SCR_TimeBaseVehicleHigh,
                    SCR_TimeBaseVehicleLow,
                    elapsedTicks);
            *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_CURRENT_STORED;
#endif
        }
    }
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_TIME_UPDATE_DONE;
}

static uint8 WCAN_WaitForSelectiveWakeAck(uint8 expected)
{
    uint16 timeout = WCAN_SWACK_WAIT_LIMIT;

    SCR_WCAN_PAGE = MOD_PAGE_1;

    while(((SCR_WCAN_INTESTAT0 & WCAN_STATUS0_SWACK_MASK) != expected) && (timeout > 0u))
    {
        timeout--;
    }

    return (timeout > 0u) ? 1u : 0u;
}

static void WCAN_ClearEvents(void)
{
    SCR_WCAN_PAGE = MOD_PAGE_1;
    SCR_WCAN_INTESCLR0 = WCAN_STATUS0_CLEAR_MASK;
    SCR_WCAN_INTESCLR1 = WCAN_STATUS1_CLEAR_MASK;
}

static void SCR_RequestStandbyWake(uint8 wakeReason)
{
    uint8 combinedWakeReason;

    combinedWakeReason = (uint8)(*G_WAKE_REASON_ADDR | wakeReason);
    *G_WAKE_REASON_ADDR = combinedWakeReason;
    SCR_TimeStoreU8(
            SCR_TIME_OFFSET_WAKE_REASON,
            (uint8)(SCR_TimeLoadU8(SCR_TIME_OFFSET_WAKE_REASON) | wakeReason));

    SCR_SCU_PAGE = MOD_PAGE_1;
    SCR_SCU_STDBYWKP = (uint8)(SCR_SCU_STDBYWKP |
            WCANWKSEL_MASK | WDTWKSEL_MASK | ECCWKSEL_MASK | SCRWKP_MASK);
}

static void SCR_ConfigureFaultWake(void)
{
    SCR_SCU_PAGE = MOD_PAGE_1;
    SCR_SCU_PMCON1 &= (uint8)(~WDT_DIS_MASK);
    SCR_SCU_RSTCON &= (uint8)(~(ECCRSTEN_MASK | WDTRSTEN_MASK));
    SCR_SCU_NMISR = SCR_FAULT_NMISR_MASK;
    SCR_SCU_NMICON = (uint8)(SCR_SCU_NMICON |
            SCR_NMICON_WDT_MASK | SCR_NMICON_RAMECC_MASK | SCR_NMICON_WAKE_MASK);
    SCR_SCU_STDBYWKP = (uint8)(SCR_SCU_STDBYWKP |
            WCANWKSEL_MASK | WDTWKSEL_MASK | ECCWKSEL_MASK);

    SCR_WDT_REL = SCR_WDT_RELOAD_100MS;
    SCR_WDT_WINB = 0u;
    SCR_WDT_CON = (uint8)(WDTIN_MASK | WDTRS_MASK | WDTEN_MASK);
}

static void SCR_WatchdogService(void)
{
#if (SCR_TIME_USE_WDT_FALLBACK != 0u)
    SCR_WdtAccumUpdate();
#endif
    SCR_WDT_CON = (uint8)(SCR_WDT_CON | WDTRS_MASK);
#if (SCR_TIME_USE_WDT_FALLBACK != 0u)
    SCR_WdtPrevCount = ((uint16)SCR_WDT_H << 8) | (uint16)SCR_WDT_L;
#endif
}

static void SCR_CheckFaultWake(void)
{
    uint8 nmiStatus;
    uint8 rstStatus;
    uint8 faultStatus = 0u;
    uint8 wakeReason = 0u;

    SCR_SCU_PAGE = MOD_PAGE_1;
    nmiStatus = SCR_SCU_NMISR;
    rstStatus = SCR_SCU_RSTST;

    if (((nmiStatus & 0x02u) != 0u) || ((rstStatus & ECCRST_MASK) != 0u))
    {
        faultStatus |= SCR_FAULT_STATUS_ECC_DBE;
        wakeReason |= SCR_FAULT_REASON_ECC_DBE;
    }

    if (((nmiStatus & 0x01u) != 0u) || ((rstStatus & WDTRST_MASK) != 0u))
    {
        faultStatus |= SCR_FAULT_STATUS_WDT;
        wakeReason |= SCR_FAULT_REASON_WDT;
    }

    if (faultStatus != 0u)
    {
        SCR_TimeStoreU8(
                SCR_TIME_OFFSET_SCR_FAULT_STATUS,
                (uint8)(SCR_TimeLoadU8(SCR_TIME_OFFSET_SCR_FAULT_STATUS) | faultStatus));
        SCR_TimeStoreU8(SCR_TIME_OFFSET_SCR_NMI_STATUS, nmiStatus);
        SCR_TimeStoreU8(SCR_TIME_OFFSET_SCR_RST_STATUS, rstStatus);
        SCR_RequestStandbyWake(wakeReason);

        SCR_SCU_PAGE = MOD_PAGE_1;
        SCR_SCU_NMISR = (uint8)(nmiStatus & SCR_FAULT_NMISR_MASK);
        SCR_SCU_RSTST = (uint8)(rstStatus & SCR_FAULT_RSTST_MASK);
    }
}

static void WCAN_ConfigureWakeFrame(void)
{
    SCR_WCAN_PAGE = MOD_PAGE_2;
    SCR_WCAN_ID0_CTRL = 0x00u;
    SCR_WCAN_ID1_CTRL = 0x00u;
    SCR_WCAN_ID2_CTRL = WCAN_WAKE_ID2_VALUE;
    SCR_WCAN_ID3_CTRL = WCAN_WAKE_ID3_VALUE;
    SCR_WCAN_MASK_ID0_CTRL = 0xFFu;
    SCR_WCAN_MASK_ID1_CTRL = 0xFFu;
    SCR_WCAN_MASK_ID2_CTRL = WCAN_WAKE_ID2_MASK;
    SCR_WCAN_MASK_ID3_CTRL = WCAN_WAKE_ID3_MASK;

    SCR_WCAN_PAGE = MOD_PAGE_3;
    SCR_WCAN_DATA0_CTRL = 0xFFu;
    SCR_WCAN_DATA1_CTRL = 0xFFu;
    SCR_WCAN_DATA2_CTRL = 0xFFu;
    SCR_WCAN_DATA3_CTRL = 0xFFu;
    SCR_WCAN_DATA4_CTRL = 0xFFu;
    SCR_WCAN_DATA5_CTRL = 0xFFu;
    SCR_WCAN_DATA6_CTRL = 0xFFu;
    SCR_WCAN_DATA7_CTRL = 0xFFu;
}

static void WCAN_CheckWake(void)
{
    uint8 wcanStatus0;
    uint8 wcanStatus1;
    uint8 p00In;
    uint8 wakeReason = 0u;

    SCR_WCAN_PAGE = MOD_PAGE_1;
    wcanStatus0 = SCR_WCAN_INTESTAT0;
    wcanStatus1 = SCR_WCAN_INTESTAT1;

    SCR_IO_PAGE = MOD_PAGE_0;
    p00In = SCR_IO_P00_IN;

    *G_WCAN_STAT0_ADDR = wcanStatus0;
    *G_WCAN_STAT1_ADDR = wcanStatus1;
    *G_P00_IN_ADDR = p00In;

    SCR_SCU_PAGE = MOD_PAGE_1;
    *G_STDBYWKP_ADDR = SCR_SCU_STDBYWKP;

    if((p00In & CANFD_RXD_PIN_MASK) == 0u)
    {
        (*G_RX_LOW_COUNT_ADDR)++;
    }

    if((wcanStatus1 & WCAN_STATUS1_WUF_MASK) != 0u)
    {
        wakeReason = WCAN_WAKE_REASON_WUF;
    }
    else if((WCAN_WAKE_ON_FD_FRAME != 0u) &&
            ((wcanStatus1 & WCAN_STATUS1_FDF_MASK) != 0u) &&
            ((*G_FDF_BASELINE_ADDR & WCAN_STATUS1_FDF_MASK) == 0u))
    {
        wakeReason = WCAN_WAKE_REASON_FDF;
    }
    else if((WCAN_WAKE_ON_SYNC_FRAME != 0u) && ((wcanStatus1 & WCAN_STATUS1_SYNC_MASK) != 0u))
    {
        wakeReason = WCAN_WAKE_REASON_SYNC;
    }

    if(wakeReason != 0u)
    {
        SCR_RequestStandbyWake(wakeReason);
    }
}

char WCAN_Init(void)
{
    char result = 0;
    unsigned char volatile TempVar = 0;

    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_INIT_ENTRY;

    /////////////////////////////////////////////////////////////////////////////
    // Setup WCAN as wakeup source
    /////////////////////////////////////////////////////////////////////////////

    // Program SCU for CAN wakeup
    // Set pads to input mode, pull-up enable
    SCR_IO_PAGE = 0x1;
    // Pull-up control before enable
    SCR_IO_P00_IOCR5 = ScrPortMode_inputPullUp; // WCANRXDD(P33.5 / SCR_P00.5)

    SCR_IO_PAGE = 0x2;
    SCR_IO_P00_PDISC = 0xDF ; // WCANRXDD(P33.5 / SCR_P00.5)
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_PIN_CFG;

    SCR_SCU_PAGE = 0x1;
    SCR_SCU_RSTCON = 0x0 ; // Disable WDT and ECC reset
    SCR_SCU_STDBYWKP = (uint8)(WCANWKSEL_MASK | WDTWKSEL_MASK | ECCWKSEL_MASK);
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_WAKE_CFG;

    /* From SCR ITS
     * 17.2.5 WCAN Initialization Sequence
     * 1. Set CFG.SCR_WCAN_EN = 1
     * 2. Set CFG.CCE = 1
     * 3. Configure CDR,CAN FD and Baud Rate Configuration registers
     * 4. Reset CFG.CCE = 0
     * 5. Reset CFG.SELWK_EN = 0
     * 6. Configure WUF Configuration registers
     * 7. Set CFG.SELWK_EN = 1
     * 8. Wait until INTESTAT0.SWACK = 1
     */

    /**************************
     * 1. Set CFG.SCR_WCAN_EN = 1
     * 2. Set CFG.CCE = 1
     **************************/
    SCR_SCU_PAGE = 1;
    SCR_SCU_PMCON1 &= ~(1<< 3); // enable WCAN clock (bit_3), default: WCAN is disabled
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_CLOCK_ENABLED;

    SCR_SCU_PAGE = 0x2;
    TempVar = SCR_SCU_MODPISEL0 & MaskWCANRXDIS; // Mask WCAN bits
    SCR_SCU_MODPISEL0 = TempVar | (SetWCANRXDD<<4); // Enable CAN on P33.5
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_PIN_SELECTED;

    SCR_WCAN_PAGE = 0x0 ;
    SCR_WCAN_CFG = WCAN_CFG_CCE | WCAN_CFG_WCAN_EN; // CCE=1, SELWK_EN=0, WCAN_EN=1 --> according to UM
    SCR_WCAN_INTMRSLT = WCAN_INT_ENABLE_WUF_ONLY;
    SCR_WCAN_FD_CTRL = 0x01 ; // Enable CAN FD tolerant mode
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_CFG_WRITTEN;

    /*****************************************************************
     * 3. Configure CDR,CAN FD and Baud Rate Configuration registers
     *****************************************************************/
    SCR_WCAN_PAGE = 0x1;
    SCR_WCAN_FRMERRCNT = (1<<6); // Do not count CAN FD frames as wake-up frame errors
    SCR_WCAN_DLC_CTRL = WCAN_WAKE_DLC_VALUE ; // 8 bytes of wake data
    SCR_WCAN_BTL1_CTRL = 0x64 ; // Configure nominal Baud Rate of 500 kbit/s
    SCR_WCAN_BTL2_CTRL = (1<<6) | (0x33<<0) ; // BRP=01(Divide by 2) and SP=0x33 represents ~80%SP
    WCAN_ClearEvents();
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_BITTIMING;

    /*****************************
     * 4. Reset CFG.CCE = 0
     * 5. Reset CFG.SELWK_EN = 0
     *****************************/
    SCR_WCAN_PAGE = 0x0 ;
    SCR_WCAN_INTMRSLT = WCAN_INT_ENABLE_WUF_ONLY;
    SCR_WCAN_CFG &= ~(WCAN_CFG_CCE | WCAN_CFG_SELWK_EN); // CCE=0, SELWK_EN=0, WCAN_EN remains enabled

    if(WCAN_WaitForSelectiveWakeAck(0u) == 0u)
    {
        result |= WCAN_INIT_SWACK_CLEAR_TIMEOUT;
    }
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_SWACK_CLEAR_DONE;

    WCAN_ConfigureWakeFrame();
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WUF_CFG_DONE;

    WCAN_ClearEvents();

    SCR_WCAN_PAGE = MOD_PAGE_0;
    SCR_WCAN_CFG |= WCAN_CFG_SELWK_EN;

    if(WCAN_WaitForSelectiveWakeAck(WCAN_STATUS0_SWACK_MASK) == 0u)
    {
        result |= WCAN_INIT_SWACK_SET_TIMEOUT;
    }
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_SWACK_SET_DONE;

    WCAN_ClearEvents();
    SCR_WCAN_PAGE = MOD_PAGE_1;
    *G_FDF_BASELINE_ADDR = (SCR_WCAN_INTESTAT1 & WCAN_STATUS1_FDF_MASK);
    *G_WCAN_INIT_ADDR = (uint8)result;
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_WCAN_INIT_DONE;

    return result;
}

void main(void)
{
    *G_COUNTER_ADDR = 0u;
    *G_WCAN_STAT0_ADDR = 0u;
    *G_WCAN_STAT1_ADDR = 0u;
    *G_P00_IN_ADDR = 0u;
    *G_RX_LOW_COUNT_ADDR = 0u;
    *G_WAKE_REASON_ADDR = 0u;
    *G_WCAN_INIT_ADDR = 0u;
    *G_STDBYWKP_ADDR = 0u;
    *G_FDF_BASELINE_ADDR = 0u;
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_MAIN_ENTRY;
    Scr_set_fsys(DIV5);
    *G_BOOT_STAGE_ADDR = BOOT_STAGE_CLOCK_SET;
    SCR_TimeInit();
    WCAN_Init();
    SCR_ConfigureFaultWake();

    while(1)
    {
        *G_BOOT_STAGE_ADDR = BOOT_STAGE_LOOP_RUNNING;
        SCR_TimeUpdate();
        *G_BOOT_STAGE_ADDR = BOOT_STAGE_LOOP_TIME_DONE;
        SCR_CheckFaultWake();
        *G_BOOT_STAGE_ADDR = BOOT_STAGE_LOOP_FAULT_DONE;
        SCR_WatchdogService();
        *G_BOOT_STAGE_ADDR = BOOT_STAGE_LOOP_WDT_DONE;
        WCAN_CheckWake();
        *G_BOOT_STAGE_ADDR = BOOT_STAGE_LOOP_WCAN_DONE;
        (*G_COUNTER_ADDR)++;
    }
}
