/**********************************************************************************************************************
 * \file SMU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*----------------------------------Includes-------------------------------------------------------------------------*/
/*********************************************************************************************************************/
#include "01_Smu/SMU/SMU.h"
#include "01_Smu/SMU_Test/Keys.h"
#include "SafetyKit_SSW_02_MCU_FW_CHECK.h"
#include "SafetyKit_Cfg.h"
#include "SafetyKit_Main.h"
#include "Cpu/Irq/IfxCpu_Irq.h"
#include "Keys.h"
#pragma section code    "text_cpu0"
#pragma section farbss  "bss_cpu0"
#pragma section fardata "data_cpu0"
#pragma section farrom  "rodata_cpu0"
/*********************************************************************************************************************/
/*------------------------------Global variables---------------------------------------------------------------------*/
/*********************************************************************************************************************/
/*-------------------------------------------------------------------------------------------------------------------*/
/*                           CONFIGURABLE BY USER                                                                    */
/*-------------------------------------------------------------------------------------------------------------------*/
/*
 * The array globalAlarmConfig[] holds the configuration of every alarm configured by the user
 * For each alarm, you can:
 *  - configure the internal reaction (trigger interrupts, issue NMI, individual CPU reset or MCU reset)
 *  */
const AlarmConfigStruct globalAlarmConfig[USER_ALARM_NUMBER] =
{
        /*---------------------------------------------------------------------------------------------------------------*/
        /* IfxSmu_Alarm alarm                       IfxSmu_InternalAlarmAction */
        /*------------------------------------------------------------- IGCS0 -------------------------------------------*/
        {DEFAULT_ALARM,                              DEFAULT_ALARM_ACTION},
        {SOFT_SMU_ALM_SMU,                           IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_ADC,                           IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_GTM_TOM_TIM,                   IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_GTM_CCU6_GPT12,                IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_GTM_TIM_TIM,                   IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_GTM_TIM_CCU6,                  IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_GTM_ECKL,                      IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_DMA,                           IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_QSPI_SAFE,                     IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_PFLASH,                        IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_PORT_SMs,                      IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_CLOCK_PLAUS,                   IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_DMA_DMASRI_EccError,           IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_IOM_Pin_MismatchIndication,    IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_EVR_Undervoltage_Alarm,        IfxSmu_InternalAlarmAction_disabled},
        {IfxSmu_Alarm_XBAR_EDC_WritePhaseError,      IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_LMU_EDC_WritePhaseError,       IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_CPU0_Lockstep_ComparatorError, IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_CPU1_Lockstep_ComparatorError, IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_CPU2_Lockstep_ComparatorError, IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_CPU3_Lockstep_ComparatorError, IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_SMU_Error_PinFaultStateActivation, IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_SCU_External_EmergencyStopSignalEvent, IfxSmu_InternalAlarmAction_nmi},
        {SOFT_SMU_ALM_ADC_BND,                        IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_HSM_Undervoltage_Alarm,         IfxSmu_InternalAlarmAction_disabled},
        {IfxSmu_Alarm_FSI_PFlash_SingleBitError,      IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_FSI_PFlash_DoubleBitError,      IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_FSI_Multiple_BitErrorDetectionTrackingBufferFull, IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_SMU_Access_EnableErrorDetected, IfxSmu_InternalAlarmAction_nmi},
        {SMU_ALARM_WHICH_TRIGGERS_NMI,                IfxSmu_InternalAlarmAction_nmi},
        {IfxSmu_Alarm_SMU_Timer0_TimeOut,             IfxSmu_InternalAlarmAction_disabled},
        {IfxSmu_Alarm_SMU_Timer1_TimeOut,             IfxSmu_InternalAlarmAction_disabled},
        {SOFT_SMU_ALM_CFG_CHECK,                      IfxSmu_InternalAlarmAction_disabled},
        {IfxSmu_Alarm_SCU_External_RequestUnitAlarm1, IfxSmu_InternalAlarmAction_disabled},
        /* Lab-only deviation: debugger-injected SRI/SPB bus alarms are random on this setup. */
        {IfxSmu_Alarm_XBAR0_SRI_BusErrorEvent,        IfxSmu_InternalAlarmAction_disabled},
        {IfxSmu_Alarm_SPB_BusErrorEvent,              IfxSmu_InternalAlarmAction_disabled}
        /*---------------------------------------------------------------------------------------------------------------*/
};
/* The array configArrayIGCS[3] holds the configuration of each Interrupt Generation Configuration Set (IGCS)
 * Each IGCS can be configured to trigger up to 3 ISR.
 */
static const uint8 configArrayIGCS[3] = {
        SmuSR0,
        SmuSR1,
        SmuSR2
};
#ifndef SMU_DEBUG_INSTRUMENTATION
#define SMU_DEBUG_INSTRUMENTATION       0
#endif

#if SMU_DEBUG_INSTRUMENTATION
volatile uint32 Smu_DebugWatchdogAlarmActionConfigured;
volatile uint32 Smu_DebugWatchdogAlarmGroup;
volatile uint32 Smu_DebugWatchdogAlarmPosition;
volatile uint32 Smu_DebugWatchdogAlarmAgcf0;
volatile uint32 Smu_DebugWatchdogAlarmAgcf1;
volatile uint32 Smu_DebugWatchdogAlarmAgcf2;
volatile uint32 Smu_DebugTrapDis0BeforeEnable;
volatile uint32 Smu_DebugTrapDis0AfterEnable;
volatile uint32 Smu_DebugTrapStatBeforeEnable;
volatile uint32 Smu_DebugTrapStatAfterEnable;
#endif

#if SMU_DEBUG_INSTRUMENTATION
#define SMU_DEBUG_ASSIGN(lhs, rhs) do { (lhs) = (rhs); } while (0)
#else
#define SMU_DEBUG_ASSIGN(lhs, rhs) do { (void)0; } while (0)
#endif
/*********************************************************************************************************************/
/*-------------------------Function Prototypes-----------------------------------------------------------------------*/
/*********************************************************************************************************************/
void initFunctionExecutionStatusSMU(SmuExecutionStatusType *SmuExecutionStatusType);
SmuStatusType initSMUAlarmsSMU(void);
SmuStatusType activateSMU(void);
static void safetyKitClearExpectedStartupAlarmsSMU(void);
/*********************************************************************************************************************/
/*-------------------------Function Implementations------------------------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * activate the  SMU, enable transition from run to fault state and enable configuration of KEYS locked
 * registers and checks if the SMU has really been started
 * */
SmuStatusType activateSMU(void)
{
    boolean configApplied = FALSE;

    IfxSmu_unlockConfigRegisters();
    /* Mandatory check! currently not done by the iLLD function IfxSmu_activateRunState */
    if(MODULE_SMU.DBG.B.SSM == IfxSmu_SmuState_run)
    {
        return pass;
    }
    else if(MODULE_SMU.DBG.B.SSM == IfxSmu_SmuState_start)
    {
        IfxSmu_activateRunState();
        configApplied = (SMU_STS.B.CMD == IfxSmu_Command_start);
        configApplied &= (!SMU_STS.B.RES)&(IfxSmu_getSmuState() == IfxSmu_SmuState_run);
    }
    else if(MODULE_SMU.DBG.B.SSM == IfxSmu_SmuState_fault)
    {
        configApplied = FALSE;
    }
    else
    {
        /* Do nothing. */
    }

    IfxSmu_temporaryLockConfigRegisters();

    if(configApplied)
    {
        return pass;
    }
    else
    {
        return fail;
    }
}
/*
 * configure the SMU and registers related to alarm setup according to the globalAlarmConfig array
 * */
SmuStatusType initSMUAlarmsSMU(void)
{
    uint8 smuInterruptsToEnable = configArrayIGCS[0] | configArrayIGCS[1] | configArrayIGCS[2];

    /* Configure alarm internal reaction according to globalAlarmConfig set by user */
    for(uint8 i = 0u; i < USER_ALARM_NUMBER; i++)
    {
        IfxSmu_setAlarmAction(globalAlarmConfig[i].alarm, globalAlarmConfig[i].alarmReaction);
#if SMU_DEBUG_INSTRUMENTATION
        if(globalAlarmConfig[i].alarm == SMU_ALARM_WHICH_TRIGGERS_NMI)
        {
            uint16 alarmGroup = (uint16)SMU_ALARM_WHICH_TRIGGERS_NMI / 32u;
            uint8 alarmPosition = (uint16)SMU_ALARM_WHICH_TRIGGERS_NMI % 32u;

            SMU_DEBUG_ASSIGN(Smu_DebugWatchdogAlarmActionConfigured, globalAlarmConfig[i].alarmReaction);
            SMU_DEBUG_ASSIGN(Smu_DebugWatchdogAlarmGroup, alarmGroup);
            SMU_DEBUG_ASSIGN(Smu_DebugWatchdogAlarmPosition, alarmPosition);
            SMU_DEBUG_ASSIGN(Smu_DebugWatchdogAlarmAgcf0, (MODULE_SMU.AGCF[alarmGroup][0].U >> alarmPosition) & 0x1u);
            SMU_DEBUG_ASSIGN(Smu_DebugWatchdogAlarmAgcf1, (MODULE_SMU.AGCF[alarmGroup][1].U >> alarmPosition) & 0x1u);
            SMU_DEBUG_ASSIGN(Smu_DebugWatchdogAlarmAgcf2, (MODULE_SMU.AGCF[alarmGroup][2].U >> alarmPosition) & 0x1u);
        }
        else
        {
            /* Do nothing. */
        }
#endif
    }
    /* Unlocks the SMU configuration registers for modification */
    g_SafetyKitStatus.unlockConfig &= IfxSmu_unlockConfigRegisters();
    if (g_SafetyKitStatus.unlockConfig == TRUE)
    {
        g_SafetyKitStatus.smuStatus.unlockConfigRegisterSMU = pass;
    }
    else
    {
        g_SafetyKitStatus.smuStatus.unlockConfigRegisterSMU = fail;
    }
    /* Configure each Interrupt Generation Configuration Set according to user config */
    IfxScuWdt_clearSafetyEndinitInline (IfxScuWdt_getSafetyWatchdogPasswordInline ());
    IfxScuWdt_setSafetyEndinitInline (IfxScuWdt_getSafetyWatchdogPasswordInline ());
    /* Enable required interrupts */
    if (smuInterruptsToEnable & 0x1)
    {
        IfxSrc_init(&SRC_SMU_SMU0_SR0, IfxCpu_Irq_getTos(0), ISR_PRORITY_SMU_ISR_0);
        IfxSrc_enable(&SRC_SMU_SMU0_SR0);
    }
    else
    {
        /* Do nothing. */
    }

    if (smuInterruptsToEnable & 0x2)
    {

        IfxSrc_init(&SRC_SMU_SMU0_SR1, IfxCpu_Irq_getTos(1), ISR_PRORITY_SMU_ISR_1);
        IfxSrc_enable(&SRC_SMU_SMU0_SR1);
    }
    else
    {
        /* Do nothing. */
    }

    if (smuInterruptsToEnable & 0x4)
    {

        IfxSrc_init(&SRC_SMU_SMU0_SR2, IfxCpu_Irq_getTos(2), ISR_PRORITY_SMU_ISR_2);
        IfxSrc_enable(&SRC_SMU_SMU0_SR2);
    }
    else
    {
        /* Do nothing. */
    }
    /* Non Maskable Interrupt config/enabling on CPUs */
    IfxScuWdt_clearCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());
    /* Enable trap requests for the CPU, which takes care of the SMU software */
    SMU_DEBUG_ASSIGN(Smu_DebugTrapDis0BeforeEnable, SCU_TRAPDIS0.U);
    SMU_DEBUG_ASSIGN(Smu_DebugTrapStatBeforeEnable, SCU_TRAPSTAT.U);
    SCU_TRAPDIS0.B.CPU0SMUT = 0u;
    SCU_TRAPDIS0.B.CPU1SMUT = 0u;
    SCU_TRAPDIS0.B.CPU2SMUT = 0u;
    SMU_DEBUG_ASSIGN(Smu_DebugTrapDis0AfterEnable, SCU_TRAPDIS0.U);
    SMU_DEBUG_ASSIGN(Smu_DebugTrapStatAfterEnable, SCU_TRAPSTAT.U);
    IfxScuWdt_setCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());

    return pass;
}

/*
 * This function enable the structure where we save the config
 * */
void initFunctionExecutionStatusSMU(SmuExecutionStatusType *functionExecutionStatus)
{
    functionExecutionStatus->structInitSts                      = NA;
    functionExecutionStatus->smuCoreAlarmConfigSts              = NA;
    functionExecutionStatus->smuCoreKeysTestSts                 = NA;
    functionExecutionStatus->smuCoreKeysTestClearSts            = NA;
    functionExecutionStatus->smuCoreInitSts                     = NA;
    functionExecutionStatus->smuCoreSWAlarmTriggerSts           = NA;
}
/*
 * Initial SMU module
 * */
void initSMUModule(void)
{
    /* Prevention of double SMU reset */
    IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());

    SCU_WDTSCON1.B.CLRIRF = 1;

    IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());
    /* Initialize the structure containing the execution state of SMU sensitive functions */
    initFunctionExecutionStatusSMU(&g_SafetyKitStatus.smuStatus);
    /* Enable the security Key test */
    enableKeysTestSMU();
    /* Set result to fail */
    SmuStatusType result = fail;
    /* Configure SMU alarms. */
    result = initSMUAlarmsSMU();

    g_SafetyKitStatus.smuStatus.smuCoreAlarmConfigSts = result;
    /* Enable the SMU */
    result = activateSMU();

    g_SafetyKitStatus.smuStatus.smuCoreInitSts = result;
}

static void safetyKitClearExpectedStartupAlarmsSMU(void)
{
    (void)IfxSmu_clearAlarmStatus((IfxSmu_Alarm)((9u * 32u) + 5u));
    (void)IfxSmu_clearAlarmStatus((IfxSmu_Alarm)((9u * 32u) + 17u));
    (void)IfxSmu_clearAlarmStatus((IfxSmu_Alarm)((6u * 32u) + 20u));
    (void)IfxSmu_clearAlarmStatus((IfxSmu_Alarm)((7u * 32u) + 1u));
}
/*
 * This function configures the alarm action for every alarm which has no default alarm configuration set
 * Note: This function is only configuring every alarm with with default alarm group configuration but
 * SMU configuration and interrupt handling is still required and implemented in the function initMMU_Module.
 * Every alarm which is not explicitly reconfigured in the function initSMUModule will keep the default
 * configuration as configured in this function.
 * */
void safetyKitEnableAllSMUAlarms(void)
{
    /* Enable SMU Module */
    IfxScuWdt_clearCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());
    MODULE_SMU.CLC.B.DISS = 0;
    IfxScuWdt_setCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());

    safetyKitClearExpectedStartupAlarmsSMU();

    /* First determine the target configuration */
    uint32 alarmGroupCF0[IFXSMU_NUM_ALARM_GROUPS] = {0};
    uint32 alarmGroupCF1[IFXSMU_NUM_ALARM_GROUPS] = {0};
    uint32 alarmGroupCF2[IFXSMU_NUM_ALARM_GROUPS] = {0};

    /* Iterate through all groups */
    for(uint8 alarmGroup = 0; alarmGroup < IFXSMU_NUM_ALARM_GROUPS ; alarmGroup++)
    {
        /* Iterate through all alarms of every group */
        for(uint8 alarmPos = 0 ; alarmPos < 32 ; alarmPos++)
        {
            if(9u == alarmGroup && (5u == alarmPos || 17u == alarmPos))
            {
                continue;
            }
            else
            {
                /* Do nothing. */
            }

            if(6u == alarmGroup && 20u == alarmPos)
            {
                continue;
            }
            else
            {
                /* Do nothing. */
            }

            if(7u == alarmGroup && (1u == alarmPos || 17u == alarmPos || 20u == alarmPos))
            {
                continue;
            }
            else
            {
                /* Do nothing. */
            }

            if(10u == alarmGroup && 16u == alarmPos)
            {
                continue;
            }
            else
            {
                // do nothing.
            }

            /* Determine if there is already an alarm action configured for the alarm at position alarmPos
             * of group alarmGroup */
            IfxSmu_InternalAlarmAction alarmAction =
                    (IfxSmu_InternalAlarmAction)(((MODULE_SMU.AGCF[alarmGroup][0].U >> alarmPos) & 0x1)      |
                            ((MODULE_SMU.AGCF[alarmGroup][1].U >> alarmPos) & 0x1) << 1 |
                            ((MODULE_SMU.AGCF[alarmGroup][2].U >> alarmPos) & 0x1) << 2 );

            /* If the alarm is still disabled enable it with the alarm action defined by the macro
             * DEFAULT_ALARM_ACTION */
            if(alarmAction == IfxSmu_InternalAlarmAction_disabled)
            {
                alarmGroupCF0[alarmGroup] |= ( DEFAULT_ALARM_ACTION         & 0x01) << alarmPos;
                alarmGroupCF1[alarmGroup] |= ((DEFAULT_ALARM_ACTION >> 1)   & 0x01) << alarmPos;
                alarmGroupCF2[alarmGroup] |= ((DEFAULT_ALARM_ACTION >> 2)   & 0x01) << alarmPos;
            }
            /* Else don't modify the alarm action. (Write the previously determined alarmAction to the
             * registers alarmGroupCF0,
             * alarmGroupCF1 and alarmGroupCF2 */
            else
            {
                alarmGroupCF0[alarmGroup] |= ( alarmAction         & 0x01) << alarmPos;
                alarmGroupCF1[alarmGroup] |= ((alarmAction >> 1)   & 0x01) << alarmPos;
                alarmGroupCF2[alarmGroup] |= ((alarmAction >> 2)   & 0x01) << alarmPos;
            }
        }
    }
    /* Unlocks the SMU configuration registers for modification */
    g_SafetyKitStatus.unlockConfig = TRUE;
    g_SafetyKitStatus.unlockConfig &= IfxSmu_unlockConfigRegisters();
    if (g_SafetyKitStatus.unlockConfig == TRUE)
    {
        g_SafetyKitStatus.smuStatus.unlockConfigRegisterSMU = pass;
    }
    else
    {
        g_SafetyKitStatus.smuStatus.unlockConfigRegisterSMU = fail;
    }

    for(uint8 alarmGroup = 0; alarmGroup < IFXSMU_NUM_ALARM_GROUPS ; alarmGroup++)
    {
        /* Disable the write-protection for registers */
        IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());

        MODULE_SMU.AGCF[alarmGroup][0].U = alarmGroupCF0[alarmGroup];
        MODULE_SMU.AGCF[alarmGroup][1].U = alarmGroupCF1[alarmGroup];
        MODULE_SMU.AGCF[alarmGroup][2].U = alarmGroupCF2[alarmGroup];

        /* Restore back the write-protection for registers */
        IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());
    }
    /* After configuration set temporary lock of SMU configuration */
    IfxSmu_temporaryLockConfigRegisters();
}
/*
 * test if the alarm is really a software alarm, then if so triggers it
 * SM:SMU:APPLICATION_SW_ALARM
 * */
SmuStatusType softwareCoreAlarmTriggerSMU(IfxSmu_Alarm alarm)
{
    boolean configApplied = FALSE;
    /* Check that the alarm is of the good group (10) and that the index is strictly lower
     * than 16 to be sure that the alarm given in parameter is a software alarm
     */
    if( ((alarm/32) == 10) & ((alarm%32) < 16) )
    {
        IfxSmu_setAlarmStatus(alarm);
    }
    else
    {
        /* Do nothing. */
    }

    configApplied = ~IfxSmu_getAlarmStatus(alarm);
    configApplied &= ~(SMU_STS.B.RES);

    if(configApplied)
    {
        return pass;
    }
    else
    {
        return fail;
    }
}
#pragma section code restore
#pragma section fardata restore
#pragma section farbss restore
#pragma section farrom restore
