/**
 * @file lwip_geth_netif.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * Copyright (c) 2015-2025, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/*
 * Copyright (c) 2001-2004 Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * This file is part of the lwIP TCP/IP stack.
 *
 * Author: Adam Dunkels <adam@sics.se>
 *
 */

/**
 * This file is a skeleton for developing Ethernet network interface
 * drivers for lwIP. Add code to the low_level functions and do a
 * search-and-replace for the word "ethernetif" to replace it with
 * something that better describes your network interface.
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip/opt.h"

#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include <lwip/stats.h>
#include <lwip/snmp.h>
#include "netif/etharp.h"
#include "netif/ppp/pppoe.h"
#include "Cpu/Std/IfxCpu_Intrinsics.h"
#include "Ifx_Cfg.h"
#include "IfxGeth_Eth.h"
#include "FblBlu.h"
#include "lwip_geth_lwip.h"
#include "lwip_geth_netif.h"
#include "lwip_geth_conf.h"
#include <string.h>
#if (PHY_DEVICE_NAME == PHY_DP83825I)
#include "lwip_geth_private_phy_dp83825i.h"
#endif
#if (PHY_DEVICE_NAME == PHY_RTL8211F)
#include "lwip_geth_private_phy_rtl8211f.h"
#endif

#ifndef __cacheai
#define __cacheai(p)  __asm__ volatile("cachea.i [%0]0"::"a"(p))
#endif

#ifndef __cacheawi
#define __cacheawi(p) __asm__ volatile("cachea.wi [%0]0"::"a"(p))
#endif

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
/* Define those to better describe your network interface. */
#define IFNAME0 'e'
#define IFNAME1 'n'
#define LWIP_GETH_MDIO_WAIT_POLLS      100000u
#define LWIP_GETH_PHY_RESET_POLLS      100000u
#define LWIP_GETH_DMA_INIT_ATTEMPTS    2u
#define LWIP_GETH_TX_WAIT_POLLS        100000u
#define LWIP_GETH_RX_TASK_BUDGET       64u
#define LWIP_GETH_RX_FRAME_INVALID     0xFFFFu
#define LWIP_GETH_CACHE_LINE_SIZE      32u
#define LWIP_GETH_RX_DESCRIPTOR_INVALID_INDEX 0xFFFFFFFFu
#define LWIP_GETH_RX_STAGE_IDLE              0u
#define LWIP_GETH_RX_STAGE_ENTER             1u
#define LWIP_GETH_RX_STAGE_DESCRIPTOR        2u
#define LWIP_GETH_RX_STAGE_LENGTH            3u
#define LWIP_GETH_RX_STAGE_ALLOC             4u
#define LWIP_GETH_RX_STAGE_BUFFER            5u
#define LWIP_GETH_RX_STAGE_COPY              6u
#define LWIP_GETH_RX_STAGE_RELEASE           7u
#define LWIP_GETH_RX_STAGE_NETIF             8u
#define LWIP_GETH_RX_STAGE_HANDLE            9u

volatile uint32 lwip_geth_DebugMdioWaitTimeoutCnt;
volatile uint32 lwip_geth_DebugPhyResetTimeoutCnt;
volatile uint32 lwip_geth_DebugDmaResetTimeoutCnt;
volatile uint32 lwip_geth_DebugDmaInitRetryCnt;
volatile uint32 lwip_geth_DebugDmaModeAfterInit;
volatile uint32 lwip_geth_DebugDmaDescriptorClearCnt;
volatile uint32 lwip_geth_DebugLowLevelInitState;
volatile uint32 lwip_geth_DebugLowLevelInitResult;
volatile uint32 lwip_geth_DebugRxInvalidFrameCnt;
volatile uint32 lwip_geth_DebugRxAllocFailCnt;
volatile uint32 lwip_geth_DebugRxNullBufferCnt;
volatile uint32 lwip_geth_DebugRxNullPayloadCnt;
volatile uint32 lwip_geth_DebugTxNoBufferCnt;
volatile uint32 lwip_geth_DebugLowLevelOutputCount;
volatile uint32 lwip_geth_DebugLowLevelOutputOkCount;
volatile uint32 lwip_geth_DebugLowLevelOutputErrCnt;
volatile uint32 lwip_geth_DebugLowLevelInputCallCount;
volatile uint32 lwip_geth_DebugLowLevelInputPacketCount;
volatile uint32 lwip_geth_DebugNetifInputLoopCount;
volatile uint32 lwip_geth_DebugNetifInputOnceCount;
volatile uint32 lwip_geth_DebugNetifInputOkCount;
volatile uint32 lwip_geth_DebugNetifInputFailCount;
volatile uint32 lwip_geth_DebugNetifInputUnknownTypeCount;
volatile uint32 lwip_geth_DebugRxWaitCount;
volatile uint32 lwip_geth_DebugRxBudgetHitCount;
volatile uint32 lwip_geth_DebugLastRxLen;
volatile uint32 lwip_geth_DebugLastTxLen;
volatile uint32 lwip_geth_DebugLastEthType;
volatile uint32 lwip_geth_DebugLastTxDescrAddr;
volatile uint32 lwip_geth_DebugLastTxBufferAddr;
volatile uint32 lwip_geth_DebugLastTxDescOwnBefore;
volatile uint32 lwip_geth_DebugLastTxDescOwnAfterKick;
volatile uint32 lwip_geth_DebugLastTxDmaStatusAfterKick;
volatile uint32 lwip_geth_DebugLastTxDmaTailAfterKick;
volatile uint32 lwip_geth_DebugLastTxDmaCurrentDescAfterKick;
volatile uint32 lwip_geth_DebugDmaCh0TxControlAfterStart;
volatile uint32 lwip_geth_DebugDmaCh0RxControlAfterStart;
volatile uint32 lwip_geth_DebugMacConfigurationAfterStart;
volatile uint32 lwip_geth_DebugLastRxDescrAddr;
volatile uint32 lwip_geth_DebugLastRxBufferAddr;
volatile uint32 lwip_geth_DebugRxBadDescriptorCnt;
volatile uint32 lwip_geth_DebugRxInvalidBufferCnt;
volatile uint32 lwip_geth_DebugRxDescriptorRestoreCnt;
volatile uint32 lwip_geth_DebugRxPbufChainInvalidCnt;
volatile uint32 lwip_geth_DebugRxBadNetifCnt;
volatile uint32 lwip_geth_DebugRxBadStateCnt;
volatile uint32 lwip_geth_DebugRxHandleRepairCnt;
volatile uint32 lwip_geth_DebugRxDescrPtrRepairCnt;
volatile uint32 lwip_geth_DebugRxCacheInvalidateCnt;
volatile uint32 lwip_geth_DebugTxCacheWritebackCnt;
volatile uint32 lwip_geth_DebugDmaCacheMaintSkippedCnt;
volatile uint32 lwip_geth_LowLevelInputPacketCount;

volatile uint32 g_LwipRxStage;
volatile uint32 g_LwipRxCurrentNetifPtr;
volatile uint32 g_LwipRxCurrentNetifStatePtr;
volatile uint32 g_LwipRxExpectedNetifPtr;
volatile uint32 g_LwipRxExpectedStatePtr;
volatile uint32 g_LwipRxCurrentDescrListPtr;
volatile uint32 g_LwipRxExpectedDescrListPtr;
volatile uint32 g_LwipRxHandleDescrPtr;
volatile uint32 g_LwipRxHardwareCurrentDescPtr;
volatile uint32 g_LwipRxCurrentDescIndex = LWIP_GETH_RX_DESCRIPTOR_INVALID_INDEX;
volatile uint32 g_LwipRxCurrentDescAddr;
volatile uint32 g_LwipRxCurrentBufferAddr;
volatile uint32 g_LwipRxCurrentPbufPtr;
volatile uint32 g_LwipRxCurrentPbufPayloadPtr;
volatile uint32 g_LwipRxCurrentPbufLen;
volatile uint32 g_LwipRxCurrentPbufTotLen;
volatile uint32 g_LwipRxCurrentPbufRef;

volatile uint32 lwip_geth_AssertCount;
volatile uint32 lwip_geth_AssertLine;

/***********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/
/**
 * Helper struct to hold private data used to operate your ethernet interface.
 * Keeping the ethernet address of the MAC in this struct is not necessary
 * as it is already kept in the struct netif.
 * But this is only an example, anyway...
 */
struct ethernetif
{
  eth_addr_t *ethaddr;
  /* Add whatever per-interface state that is needed here. */
};

static uint8 lwip_geth_low_level_init(netif_t *netif);

FBL_RAM_ETH_CODE
void lwip_geth_AssertFail(uint32 line)
{
  lwip_geth_AssertLine = line;
  lwip_geth_AssertCount++;

  /* Continuing after an lwIP invariant failure can corrupt the active download.
   * This handler and its state are part of the RAM-resident runtime. */
  __disable();
  for (;;)
  {
    __debug();
  }
}

FBL_RAM_ETH_CODE
static void lwip_geth_CopyBytes(void *destination, const void *source, uint32 length)
{
  volatile uint8 *dst = (volatile uint8 *)destination;
  const volatile uint8 *src = (const volatile uint8 *)source;
  uint32 index;

  for (index = 0u; index < length; index++)
  {
    dst[index] = src[index];
  }
}

FBL_RAM_ETH_CODE
static uint8 lwip_geth_IsExpectedRxDescriptorAddress(uint32 descrAddr)
{
  uint32 base = (uint32)&IfxGeth_Eth_rxDescrList[0][0].descr[0];
  uint32 ringEnd = base + ((uint32)IFXGETH_MAX_RX_DESCRIPTORS * (uint32)sizeof(IfxGeth_RxDescr));
  uint32 offset;

  if ((descrAddr < base) || (descrAddr >= ringEnd))
  {
    return 0u;
  }

  offset = descrAddr - base;

  if ((offset % (uint32)sizeof(IfxGeth_RxDescr)) != 0u)
  {
    return 0u;
  }

  return 1u;
}

FBL_RAM_ETH_CODE
static uint32 lwip_geth_GetRxDescriptorIndex(const IfxGeth_RxDescr *rxDescr)
{
  uint32 base = (uint32)&IfxGeth_Eth_rxDescrList[0][0].descr[0];
  uint32 descrAddr = (uint32)rxDescr;

  if ((rxDescr == NULL_PTR) || (lwip_geth_IsExpectedRxDescriptorAddress(descrAddr) == 0u))
  {
    return LWIP_GETH_RX_DESCRIPTOR_INVALID_INDEX;
  }

  return (descrAddr - base) / (uint32)sizeof(IfxGeth_RxDescr);
}

FBL_RAM_ETH_CODE
static IfxGeth_RxDescr *lwip_geth_GetValidatedRxDescriptor(IfxGeth_Eth *ethernetif)
{
  uint32 descrAddr;
  uint32 hwDescrAddr = 0u;
  IfxGeth_RxDescr *rxDescr;

  if (ethernetif == NULL_PTR)
  {
    return NULL_PTR;
  }

  rxDescr = (IfxGeth_RxDescr *)ethernetif->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrPtr;
  descrAddr = (uint32)rxDescr;
  g_LwipRxHandleDescrPtr = descrAddr;

  if (ethernetif->gethSFR != NULL_PTR)
  {
    hwDescrAddr = ethernetif->gethSFR->DMA_CH[IfxGeth_RxDmaChannel_0].CURRENT_APP_RXDESC.U;
  }
  g_LwipRxHardwareCurrentDescPtr = hwDescrAddr;

  if (lwip_geth_IsExpectedRxDescriptorAddress(descrAddr) != 0u)
  {
    return rxDescr;
  }

  if (lwip_geth_IsExpectedRxDescriptorAddress(hwDescrAddr) != 0u)
  {
    ethernetif->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrPtr = (IfxGeth_RxDescr *)hwDescrAddr;
    lwip_geth_DebugRxDescrPtrRepairCnt++;
    return (IfxGeth_RxDescr *)hwDescrAddr;
  }

  ethernetif->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrPtr = &IfxGeth_Eth_rxDescrList[0][0].descr[0];
  lwip_geth_DebugRxDescrPtrRepairCnt++;
  return (IfxGeth_RxDescr *)&IfxGeth_Eth_rxDescrList[0][0].descr[0];
}

FBL_RAM_ETH_CODE
static uint8 lwip_geth_PrepareRxHandle(netif_t *netif, IfxGeth_Eth **ethernetif)
{
  IfxGeth_Eth *expectedState = lwip_geth_IfxGeth_get();
  IfxGeth_RxDescrList *expectedRxList = (IfxGeth_RxDescrList *)&IfxGeth_Eth_rxDescrList[0][0];

  g_LwipRxCurrentNetifPtr = (uint32)netif;
  g_LwipRxExpectedNetifPtr = (uint32)&g_Lwip.netif;
  g_LwipRxExpectedStatePtr = (uint32)expectedState;
  g_LwipRxExpectedDescrListPtr = (uint32)expectedRxList;

  if ((netif == NULL_PTR) || (netif != &g_Lwip.netif) || (ethernetif == NULL_PTR))
  {
    lwip_geth_DebugRxBadNetifCnt++;
    return 0u;
  }

  g_LwipRxStage = LWIP_GETH_RX_STAGE_NETIF;
  g_LwipRxCurrentNetifStatePtr = (uint32)netif->state;

  if (netif->state != expectedState)
  {
    lwip_geth_DebugRxBadStateCnt++;
    netif->state = expectedState;
    g_LwipRxCurrentNetifStatePtr = (uint32)netif->state;
  }

  g_LwipRxStage = LWIP_GETH_RX_STAGE_HANDLE;

  if (expectedState->gethSFR != &MODULE_GETH)
  {
    expectedState->gethSFR = &MODULE_GETH;
    lwip_geth_DebugRxHandleRepairCnt++;
  }

  g_LwipRxCurrentDescrListPtr = (uint32)expectedState->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrList;
  if (expectedState->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrList != expectedRxList)
  {
    expectedState->rxChannel[IfxGeth_RxDmaChannel_0].channelId = IfxGeth_RxDmaChannel_0;
    expectedState->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrList = expectedRxList;
    g_LwipRxCurrentDescrListPtr = (uint32)expectedState->rxChannel[IfxGeth_RxDmaChannel_0].rxDescrList;
    lwip_geth_DebugRxHandleRepairCnt++;
  }

  *ethernetif = expectedState;
  return 1u;
}

FBL_RAM_ETH_CODE
static uint8 lwip_geth_IsDmaNonCachedRange(uint32 address, uint32 length)
{
  uint32 end;

  if (length == 0u)
  {
    return 0u;
  }

  end = address + length;

  if ((end < address) || (address < AURIX_ETH_DMA_BASE) || (end > AURIX_ETH_DMA_END))
  {
    return 0u;
  }

  return 1u;
}

FBL_RAM_ETH_CODE
static uint8 lwip_geth_IsRxBufferValid(uint32 descriptorIndex, const uint8 *buffer, uint32 length)
{
  uint32 bufferAddr = (uint32)buffer;
  uint32 ringStart = (uint32)&channel0RxBuffer1[0][0];
  uint32 ringBytes = (uint32)sizeof(channel0RxBuffer1);
  uint32 ringEnd = ringStart + ringBytes;
  uint32 offset;

  if ((descriptorIndex >= IFXGETH_MAX_RX_DESCRIPTORS) ||
      (buffer == NULL_PTR) ||
      (length == 0u) ||
      (length > IFXGETH_MAX_RX_BUFFER_SIZE) ||
      ((bufferAddr & 0x3u) != 0u) ||
      (bufferAddr < ringStart) ||
      (bufferAddr >= ringEnd) ||
      ((bufferAddr + length) < bufferAddr) ||
      ((bufferAddr + length) > ringEnd) ||
      (lwip_geth_IsDmaNonCachedRange(bufferAddr, length) == 0u))
  {
    return 0u;
  }

  offset = bufferAddr - ringStart;

  if ((offset % IFXGETH_MAX_RX_BUFFER_SIZE) != 0u)
  {
    return 0u;
  }

  if ((offset / IFXGETH_MAX_RX_BUFFER_SIZE) != descriptorIndex)
  {
    return 0u;
  }

  return 1u;
}

FBL_RAM_ETH_CODE
static void lwip_geth_RestoreRxDescriptorBuffer(IfxGeth_Eth *ethernetif, IfxGeth_RxDescr *rxDescr)
{
  uint32 descriptorIndex = lwip_geth_GetRxDescriptorIndex(rxDescr);

  if (descriptorIndex >= IFXGETH_MAX_RX_DESCRIPTORS)
  {
    return;
  }

  rxDescr->RDES0.U = (uint32)&channel0RxBuffer1[descriptorIndex][0];
  lwip_geth_DebugRxDescriptorRestoreCnt++;
}

//FBL_RAM_ETH_CODE
//static void lwip_geth_CacheInvalidateRange(const void *address, uint32 length)
//{
////  uint32 line;
////  uint32 end;
////
////  if ((address == NULL_PTR) || (length == 0u))
////  {
////    return;
////  }
////
////  line = ((uint32)address) & ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);
////  end = (((uint32)address) + length + (LWIP_GETH_CACHE_LINE_SIZE - 1u)) &
////      ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);
////
////  while (line < end)
////  {
////    __cacheai((uint8 *)line);
////    line += LWIP_GETH_CACHE_LINE_SIZE;
////  }
////
////  __dsync();
////  lwip_geth_DebugRxCacheInvalidateCnt++;
//}

FBL_RAM_ETH_CODE
static void lwip_geth_CacheWritebackInvalidateRange(const volatile void *address, uint32 length)
{
  uint32 line;
  uint32 end;

  if ((address == NULL_PTR) || (length == 0u))
  {
    return;
  }

  if (lwip_geth_IsDmaNonCachedRange((uint32)address, length) != 0u)
  {
    lwip_geth_DebugDmaCacheMaintSkippedCnt++;
    return;
  }

  line = ((uint32)address) & ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);
  end = (((uint32)address) + length + (LWIP_GETH_CACHE_LINE_SIZE - 1u)) &
      ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);

  while (line < end)
  {
    __cacheawi((uint8 *)line);
    line += LWIP_GETH_CACHE_LINE_SIZE;
  }

  __dsync();
  lwip_geth_DebugTxCacheWritebackCnt++;
}

FBL_RAM_ETH_CODE
void FblRamGeth_ShuffleRxDescriptor(IfxGeth_Eth *geth, IfxGeth_RxDmaChannel channelId)
{
  volatile IfxGeth_RxDescr *currentDescr;
  volatile IfxGeth_RxDescr *lastDescr;

  if ((geth == NULL_PTR) || (geth->rxChannel[channelId].rxDescrList == NULL_PTR))
  {
    return;
  }

  currentDescr = geth->rxChannel[channelId].rxDescrPtr;
  lastDescr = &geth->rxChannel[channelId].rxDescrList->descr[IFXGETH_MAX_RX_DESCRIPTORS - 1u];

  if (currentDescr == lastDescr)
  {
    geth->rxChannel[channelId].rxDescrPtr = &geth->rxChannel[channelId].rxDescrList->descr[0];
  }
  else
  {
    geth->rxChannel[channelId].rxDescrPtr = &geth->rxChannel[channelId].rxDescrPtr[1];
  }
}

FBL_RAM_ETH_CODE
void FblRamGeth_FreeReceiveBuffer(IfxGeth_Eth *geth, IfxGeth_RxDmaChannel channelId)
{
  volatile IfxGeth_RxDescr *descr;
  IfxGeth_RxDescr3 rdes3;

  if (geth == NULL_PTR)
  {
    return;
  }

  descr = geth->rxChannel[channelId].rxDescrPtr;

  if (descr == NULL_PTR)
  {
    return;
  }

  rdes3.U = 0u;
  rdes3.R.BUF1V = 1u;
  rdes3.R.BUF2V = 0u;
  rdes3.R.IOC = 0u;
  rdes3.R.OWN = 1u;
  descr->RDES3.U = rdes3.U;

  FblRamGeth_ShuffleRxDescriptor(geth, channelId);
}

FBL_RAM_ETH_CODE
void *FblRamGeth_GetTransmitBuffer(IfxGeth_Eth *geth, IfxGeth_TxDmaChannel channelId)
{
  volatile IfxGeth_TxDescr *descr;

  if (geth == NULL_PTR)
  {
    return NULL_PTR;
  }

  descr = geth->txChannel[channelId].txDescrPtr;

  if ((descr != NULL_PTR) && (descr->TDES3.R.OWN == 0u))
  {
    return (void *)descr->TDES0.U;
  }

  return NULL_PTR;
}

FBL_RAM_ETH_CODE
void FblRamGeth_WakeupReceiver(IfxGeth_Eth *geth, IfxGeth_RxDmaChannel channelId)
{
  Ifx_GETH *gethSFR;

  if ((geth == NULL_PTR) || (geth->gethSFR == NULL_PTR))
  {
    return;
  }

  gethSFR = geth->gethSFR;

  if ((gethSFR->DMA_CH[channelId].STATUS.U & (1u << IfxGeth_DmaInterruptFlag_receiveStopped)) != 0u)
  {
    if ((gethSFR->DMA_CH[channelId].STATUS.U & (1u << IfxGeth_DmaInterruptFlag_receiveBufferUnavailable)) != 0u)
    {
      gethSFR->DMA_CH[channelId].STATUS.U = (1u << IfxGeth_DmaInterruptFlag_receiveBufferUnavailable);
    }

    gethSFR->MAC_CONFIGURATION.B.RE = 1u;
    gethSFR->DMA_CH[channelId].RX_CONTROL.B.SR = 1u;
  }
}

FBL_RAM_ETH_CODE
void FblRamGeth_WakeupTransmitter(IfxGeth_Eth *geth, IfxGeth_TxDmaChannel channelId)
{
  Ifx_GETH *gethSFR;
  uint32 mtlMask = ((1u << IfxGeth_MtlInterruptFlag_txQueueUnderflow) |
                    (1u << IfxGeth_MtlInterruptFlag_averageBitsPerSlot) |
                    (1u << IfxGeth_MtlInterruptFlag_rxQueueOverflow)) << 8u;

  if ((geth == NULL_PTR) || (geth->gethSFR == NULL_PTR))
  {
    return;
  }

  gethSFR = geth->gethSFR;

  if ((gethSFR->DMA_CH[channelId].STATUS.U & (1u << IfxGeth_DmaInterruptFlag_transmitStopped)) != 0u)
  {
    if ((gethSFR->DMA_CH[channelId].STATUS.U & (1u << IfxGeth_DmaInterruptFlag_transmitBufferUnavailable)) != 0u)
    {
      gethSFR->DMA_CH[channelId].STATUS.U = (1u << IfxGeth_DmaInterruptFlag_transmitBufferUnavailable);
    }

    if ((gethSFR->MTL_Q0.INTERRUPT_CONTROL_STATUS.U & (1u << IfxGeth_MtlInterruptFlag_txQueueUnderflow)) != 0u)
    {
      gethSFR->MTL_Q0.INTERRUPT_CONTROL_STATUS.U =
          (gethSFR->MTL_Q0.INTERRUPT_CONTROL_STATUS.U & mtlMask) |
          (1u << IfxGeth_MtlInterruptFlag_txQueueUnderflow);
    }

    gethSFR->MAC_CONFIGURATION.B.TE = 1u;
    gethSFR->DMA_CH[channelId].TX_CONTROL.B.ST = 1u;
  }
}

FBL_RAM_ETH_CODE
void FblRamGeth_SetLineSpeed(Ifx_GETH *gethSFR, IfxGeth_LineSpeed speed)
{
  if (gethSFR == NULL_PTR)
  {
    return;
  }

  switch (speed)
  {
  case IfxGeth_LineSpeed_10Mbps:
    gethSFR->MAC_CONFIGURATION.B.PS = 1u;
    gethSFR->MAC_CONFIGURATION.B.FES = 0u;
    break;
  case IfxGeth_LineSpeed_100Mbps:
    gethSFR->MAC_CONFIGURATION.B.PS = 1u;
    gethSFR->MAC_CONFIGURATION.B.FES = 1u;
    break;
  case IfxGeth_LineSpeed_1000Mbps:
    gethSFR->MAC_CONFIGURATION.B.PS = 0u;
    gethSFR->MAC_CONFIGURATION.B.FES = 0u;
    break;
  case IfxGeth_LineSpeed_2500Mbps:
    gethSFR->MAC_CONFIGURATION.B.PS = 0u;
    gethSFR->MAC_CONFIGURATION.B.FES = 1u;
    break;
  default:
    break;
  }
}

FBL_RAM_ETH_CODE
static void lwip_geth_FreeReceiveDescriptor(IfxGeth_Eth *ethernetif, IfxGeth_RxDescr *rxDescr)
{
  if ((ethernetif == NULL_PTR) || (rxDescr == NULL_PTR))
  {
    return;
  }

  lwip_geth_RestoreRxDescriptorBuffer(ethernetif, rxDescr);
  FblRamGeth_FreeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
  lwip_geth_CacheWritebackInvalidateRange(rxDescr, sizeof(*rxDescr));
  FblRamGeth_WakeupReceiver(ethernetif, IfxGeth_RxDmaChannel_0);
}

static void lwip_geth_PrepareDmaMemory(const IfxGeth_Eth_Config *config)
{
  const IfxGeth_Eth_TxChannelConfig *txConfig;
  const IfxGeth_Eth_RxChannelConfig *rxConfig;
  uint32 i;

  if ((config == NULL_PTR) || (config->dma.numOfTxChannels == 0u) || (config->dma.numOfRxChannels == 0u))
  {
    return;
  }

  for (i = 0u; i < config->dma.numOfTxChannels; i++)
  {
    txConfig = &config->dma.txChannel[i];

    if ((txConfig->channelEnable != FALSE) && (txConfig->txDescrList != NULL_PTR))
    {
      lwip_geth_CacheWritebackInvalidateRange(txConfig->txDescrList->descr,
          (uint32)(IFXGETH_MAX_TX_DESCRIPTORS * sizeof(IfxGeth_TxDescr)));
    }

    if ((txConfig->channelEnable != FALSE) &&
        (txConfig->txBuffer1StartAddress != NULL_PTR) &&
        (txConfig->txBuffer1Size > 0u))
    {
      lwip_geth_CacheWritebackInvalidateRange(txConfig->txBuffer1StartAddress,
          (uint32)(IFXGETH_MAX_TX_DESCRIPTORS * txConfig->txBuffer1Size));
    }
  }

  for (i = 0u; i < config->dma.numOfRxChannels; i++)
  {
    rxConfig = &config->dma.rxChannel[i];

    if ((rxConfig->channelEnable != FALSE) && (rxConfig->rxDescrList != NULL_PTR))
    {
      lwip_geth_CacheWritebackInvalidateRange(rxConfig->rxDescrList->descr,
          (uint32)(IFXGETH_MAX_RX_DESCRIPTORS * sizeof(IfxGeth_RxDescr)));
    }

    if ((rxConfig->channelEnable != FALSE) &&
        (rxConfig->rxBuffer1StartAddress != NULL_PTR) &&
        (rxConfig->rxBuffer1Size > 0u))
    {
      lwip_geth_CacheWritebackInvalidateRange(rxConfig->rxBuffer1StartAddress,
          (uint32)(IFXGETH_MAX_RX_DESCRIPTORS * rxConfig->rxBuffer1Size));
    }
  }
}

static void lwip_geth_ClearDmaDescriptorMemory(const IfxGeth_Eth_Config *config)
{
  const IfxGeth_Eth_TxChannelConfig *txConfig;
  const IfxGeth_Eth_RxChannelConfig *rxConfig;
  uint32 i;

  if (config == NULL_PTR)
  {
    return;
  }

  for (i = 0u; i < config->dma.numOfTxChannels; i++)
  {
    txConfig = &config->dma.txChannel[i];

    if ((txConfig->channelEnable != FALSE) && (txConfig->txDescrList != NULL_PTR))
    {
      MEMSET((void *)txConfig->txDescrList->descr, 0,
          (uint32)(IFXGETH_MAX_TX_DESCRIPTORS * sizeof(IfxGeth_TxDescr)));
    }
  }

  for (i = 0u; i < config->dma.numOfRxChannels; i++)
  {
    rxConfig = &config->dma.rxChannel[i];

    if ((rxConfig->channelEnable != FALSE) && (rxConfig->rxDescrList != NULL_PTR))
    {
      MEMSET((void *)rxConfig->rxDescrList->descr, 0,
          (uint32)(IFXGETH_MAX_RX_DESCRIPTORS * sizeof(IfxGeth_RxDescr)));
    }
  }

  __dsync();
  lwip_geth_DebugDmaDescriptorClearCnt++;
}

static void lwip_geth_StopMacDma(Ifx_GETH *gethSFR)
{
  if (gethSFR == NULL_PTR)
  {
    return;
  }

  IfxGeth_mac_disableTransmitter(gethSFR);
  IfxGeth_mac_disableReceiver(gethSFR);
  IfxGeth_dma_stopTransmitter(gethSFR, IfxGeth_TxDmaChannel_0);
  gethSFR->DMA_CH[IfxGeth_RxDmaChannel_0].RX_CONTROL.B.SR = 0u;
  __dsync();
}

#if (PHY_DEVICE_NAME != PHY_DP83825I)
static uint8 lwip_geth_MdioWaitReadyBounded(void)
{
  uint32 timeout = LWIP_GETH_MDIO_WAIT_POLLS;

  while ((GETH_MAC_MDIO_ADDRESS.B.GB != 0u) && (timeout > 0u))
  {
    timeout--;
  }

  if (timeout == 0u)
  {
    lwip_geth_DebugMdioWaitTimeoutCnt++;
    return 0u;
  }

  return 1u;
}

static uint8 lwip_geth_MdioReadBounded(uint32 layerAddr, uint32 regAddr, uint32 *data)
{
  if ((data == NULL_PTR) || (lwip_geth_MdioWaitReadyBounded() == 0u))
  {
    return 0u;
  }

  GETH_MAC_MDIO_ADDRESS.U =
      ((layerAddr & 0x1Fu) << 21) |
      ((regAddr & 0x1Fu) << 16) |
      (0u << 8) |
      (3u << 2) |
      (1u << 0);

  if (lwip_geth_MdioWaitReadyBounded() == 0u)
  {
    return 0u;
  }

  *data = GETH_MAC_MDIO_DATA.U & 0xFFFFu;
  return 1u;
}

static uint8 lwip_geth_MdioWriteBounded(uint32 layerAddr, uint32 regAddr, uint32 data)
{
  if (lwip_geth_MdioWaitReadyBounded() == 0u)
  {
    return 0u;
  }

  GETH_MAC_MDIO_DATA.U = data & 0xFFFFu;
  GETH_MAC_MDIO_ADDRESS.U =
      ((layerAddr & 0x1Fu) << 21) |
      ((regAddr & 0x1Fu) << 16) |
      (0u << 8) |
      (1u << 2) |
      (1u << 0);

  return lwip_geth_MdioWaitReadyBounded();
}

static uint8 lwip_geth_PhyWaitResetDoneBounded(void)
{
  uint32 timeout = LWIP_GETH_PHY_RESET_POLLS;
  uint32 bmcr = 0u;

  while (timeout > 0u)
  {
    if (lwip_geth_MdioReadBounded(0u, 0u, &bmcr) == 0u)
    {
      break;
    }

    if ((bmcr & 0x8000u) == 0u)
    {
      return 1u;
    }

    timeout--;
  }

  lwip_geth_DebugPhyResetTimeoutCnt++;
  return 0u;
}
#endif

FBL_RAM_ETH_CODE
static void *lwip_geth_WaitTransmitBufferBounded(IfxGeth_Eth *ethernetif)
{
  uint32 timeout = LWIP_GETH_TX_WAIT_POLLS;
  void *tbuf;

  if (ethernetif == NULL_PTR)
  {
    lwip_geth_DebugTxNoBufferCnt++;
    return NULL_PTR;
  }

  do
  {
    tbuf = FblRamGeth_GetTransmitBuffer(ethernetif, IfxGeth_TxDmaChannel_0);

    if (tbuf != NULL_PTR)
    {
      return tbuf;
    }

    timeout--;
  } while (timeout > 0u);

  lwip_geth_DebugTxNoBufferCnt++;
  return NULL_PTR;
}

static uint8 lwip_geth_InitModuleWithResetCheck(IfxGeth_Eth *ethernetif, IfxGeth_Eth_Config *config)
{
  uint32 attempt;

  if ((ethernetif == NULL_PTR) || (config == NULL_PTR) || (config->gethSFR == NULL_PTR))
  {
    return 0u;
  }

  for (attempt = 0u; attempt < LWIP_GETH_DMA_INIT_ATTEMPTS; attempt++)
  {
    if (attempt > 0u)
    {
      lwip_geth_DebugDmaInitRetryCnt++;
    }

    lwip_geth_StopMacDma(config->gethSFR);
    lwip_geth_ClearDmaDescriptorMemory(config);
    IfxGeth_Eth_initModule(ethernetif, config);
    lwip_geth_DebugDmaModeAfterInit = config->gethSFR->DMA_MODE.U;

    if (IfxGeth_dma_isSoftwareResetDone(config->gethSFR) != 0)
    {
      return 1u;
    }

    lwip_geth_DebugDmaResetTimeoutCnt++;
  }

  return 0u;
}

FBL_RAM_ETH_CODE
static void lwip_geth_SendSingleTransmitBuffer(IfxGeth_Eth *ethernetif, uint16 packetLength)
{
  volatile IfxGeth_TxDescr *firstDescr =
      IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
  volatile IfxGeth_TxDescr *lastDescr =
      &ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrList->descr[IFXGETH_MAX_TX_DESCRIPTORS - 1u];
  volatile IfxGeth_TxDescr *nextDescr;

  if (firstDescr == lastDescr)
  {
    nextDescr = IfxGeth_Eth_getBaseTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
  }
  else
  {
    nextDescr = &firstDescr[1];
  }

  lwip_geth_DebugLastTxDescOwnBefore = firstDescr->TDES3.R.OWN;
  firstDescr->TDES2.U = 0u;
  firstDescr->TDES3.U = 0u;

  firstDescr->TDES3.R.FL_TPL = packetLength;
  firstDescr->TDES3.R.TSE = 0u;
  firstDescr->TDES3.R.CIC_TPL = 3u;
  firstDescr->TDES3.R.SAIC = 0u;
  firstDescr->TDES3.R.CPC = 0u;
  firstDescr->TDES3.R.FD = 1u;
  firstDescr->TDES3.R.LD = 1u;
  firstDescr->TDES2.R.IOC = 0u;
  firstDescr->TDES2.R.B1L = packetLength;
  firstDescr->TDES3.R.OWN = 1u;

  lwip_geth_CacheWritebackInvalidateRange(firstDescr, sizeof(IfxGeth_TxDescr));
  ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrPtr = firstDescr;
  IfxGeth_dma_setTxDescriptorTailPointer(ethernetif->gethSFR, IfxGeth_TxDmaChannel_0, (uint32)nextDescr);
  FblRamGeth_WakeupTransmitter(ethernetif, IfxGeth_TxDmaChannel_0);
  lwip_geth_DebugLastTxDescOwnAfterKick = firstDescr->TDES3.R.OWN;
  lwip_geth_DebugLastTxDmaStatusAfterKick = ethernetif->gethSFR->DMA_CH[IfxGeth_TxDmaChannel_0].STATUS.U;
  lwip_geth_DebugLastTxDmaTailAfterKick = ethernetif->gethSFR->DMA_CH[IfxGeth_TxDmaChannel_0].TXDESC_TAIL_POINTER.U;
  lwip_geth_DebugLastTxDmaCurrentDescAfterKick = ethernetif->gethSFR->DMA_CH[IfxGeth_TxDmaChannel_0].CURRENT_APP_TXDESC.U;
  ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrPtr = nextDescr;
  ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txCount++;
}

/***********************************************************************************************************************
 * FUNCTION IMPLEMENTATIONS
 **********************************************************************************************************************/
/**
 * In this function, the hardware should be initialized.
 * Called from ethernetif_init().
 *
 * @param netif the already initialized lwip network interface structure
 *        for this ethernetif
 */
static uint8 lwip_geth_low_level_init(netif_t *netif)
{
  IfxGeth_Eth *ethernetif = netif->state;
  int         i;

  lwip_geth_DebugLowLevelInitState = 1u;
  lwip_geth_DebugLowLevelInitResult = 0u;

  /* set MAC hardware address length */
  netif->hwaddr_len = ETHARP_HWADDR_LEN;

  /* set MAC hardware address */
  for (i = 0; i < ETHARP_HWADDR_LEN; i++)
  {
    netif->hwaddr[i] = g_Lwip.eth_addr.addr[i];
  }

  /* maximum transfer unit */
  netif->mtu = lwip_geth_handle->app_config->mtu;

  /* device capabilities */
  /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
  /* we don't set the LINK_UP flag because we don't say when it is linked */
  netif->flags = NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP;

  /* Do whatever else is needed to initialize interface. */
  {
    IfxGeth_Eth_Config GethConfig;
    lwip_geth_CopyBytes(&GethConfig,
        lwip_geth_handle->app_config->geth_lld_config,
        (uint32)sizeof(GethConfig));

    /* We get the ID of Ethernet Phy do determine the board version, also needed for SCR */
    if (lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins != NULL)
    {
      IfxPort_setPinModeOutput(lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdc->pin.port,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdc->pin.pinIndex,IfxPort_OutputMode_pushPull,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdc->select);

      GETH_GPCTL.B.ALTI0  = lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdio->inSelect;
    }
    else if (lwip_geth_handle->app_config->geth_lld_config->pins.miiPins != NULL)
    {
      IfxPort_setPinModeOutput(lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdc->pin.port,
                               lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdc->pin.pinIndex,IfxPort_OutputMode_pushPull,
                               lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdc->select);

      GETH_GPCTL.B.ALTI0  = lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdio->inSelect;
    }
    else if (lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins != NULL)
    {
      IfxPort_setPinModeOutput(lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdc->pin.port,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdc->pin.pinIndex,IfxPort_OutputMode_pushPull,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdc->select);

      GETH_GPCTL.B.ALTI0  = lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdio->inSelect;
    }
    else
    {
      /* Pin mappings were not generated; leave MDC/MDIO untouched. */
    }

#if (PHY_DEVICE_NAME != PHY_DP83825I)
    if (lwip_geth_MdioWaitReadyBounded() != 0u)
    {
      (void)lwip_geth_PhyWaitResetDoneBounded();

      /* reset PHY */
      if (lwip_geth_MdioWriteBounded(0u, 0u, 0x8000u) != 0u)
      {
        (void)lwip_geth_PhyWaitResetDoneBounded();
      }
    }
#endif

    /* initialize the module */
    lwip_geth_DebugLowLevelInitState = 2u;
    if (lwip_geth_InitModuleWithResetCheck(ethernetif, &GethConfig) == 0u)
    {
      lwip_geth_DebugLowLevelInitState = 0xE2u;
      return 0u;
    }
    lwip_geth_PrepareDmaMemory(&GethConfig);

    /* Normal operation: keep MAC destination filtering enabled. */
    IfxGeth_mac_setPromiscuousMode(ethernetif->gethSFR, FALSE);
    IfxGeth_mac_setAllMulticastPassing(ethernetif->gethSFR, FALSE);

    /* initialize the PHY */
#if (PHY_DEVICE_NAME == PHY_DP83825I)
    if (lwip_geth_private_Phy_Dp83825i_init() == 0u)
    {
      lwip_geth_DebugLowLevelInitState = 0xE3u;
      return 0u;
    }
#endif

#if (PHY_DEVICE_NAME == PHY_RTL8211F)
    lwip_geth_private_Phy_Rtl8211f_init();
#endif
    /* and enable transmitter/receiver */
    lwip_geth_DebugLowLevelInitState = 3u;
    IfxGeth_Eth_startTransmitters(ethernetif, 1);
    IfxGeth_Eth_startReceivers(ethernetif, 1);
    lwip_geth_DebugDmaCh0TxControlAfterStart = ethernetif->gethSFR->DMA_CH[IfxGeth_TxDmaChannel_0].TX_CONTROL.U;
    lwip_geth_DebugDmaCh0RxControlAfterStart = ethernetif->gethSFR->DMA_CH[IfxGeth_RxDmaChannel_0].RX_CONTROL.U;
    lwip_geth_DebugMacConfigurationAfterStart = ethernetif->gethSFR->MAC_CONFIGURATION.U;

#if (PHY_DEVICE_NAME == PHY_DP83825I)
    {
      Ifx_GETH_MAC_PHYIF_CONTROL_STATUS ctrl_status;
      ctrl_status.U = lwip_geth_private_Phy_Dp83825i_link_status();

#if LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
      netif->flags |= NETIF_FLAG_LINK_UP;
      IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
      FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
#else
      if (ctrl_status.B.LNKSTS == 1u)
      {
        netif->flags |= NETIF_FLAG_LINK_UP;
        if (ctrl_status.B.LNKMOD == 1u)
        {
          IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
        }
        else
        {
          IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
        }

        if (ctrl_status.B.LNKSPEED == 0u)
        {
          FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
        }
        else
        {
          FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
        }
      }
#endif
    }
#else
    if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSTS == 1u)
    {
      netif->flags |= NETIF_FLAG_LINK_UP;
      if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKMOD == 1u)
      {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
      }
      else
      {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
      }

      if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 0u)
      {
        FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
      }
      else if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 1u)
      {
        FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
      }
      else
      {
        FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_1000Mbps);
      }
    }
#endif
  }

  lwip_geth_DebugLowLevelInitState = 4u;
  lwip_geth_DebugLowLevelInitResult = 1u;
  return 1u;
}

/**
 * This function should do the actual transmission of the packet. The packet is
 * contained in the pbuf that is passed to the function. This pbuf
 * might be chained.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
 * @return ERR_OK if the packet could be sent
 *         an err_t value if the packet couldn't be sent
 *
 * @note Returning ERR_MEM here if a DMA queue of your MAC is full can lead to
 *       strange results. You might consider waiting for space in the DMA queue
 *       to become availale since the stack doesn't retry to send a packet
 *       dropped because of memory failure (except for the TCP timers).
 */
FBL_RAM_ETH_CODE
static err_t lwip_geth_low_level_output(netif_t *netif, pbuf_t *p)
{
  IfxGeth_Eth *ethernetif = netif->state;
  struct pbuf *q;
  u8_t *tbuf;
  u16_t l;

  lwip_geth_DebugLowLevelOutputCount++;

#ifdef LWIP_DEBUG
  u16_t       length = p->tot_len;
#endif
  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output (p=%p)\n", p));

#if ETH_PAD_SIZE
  pbuf_header(p, -ETH_PAD_SIZE); /* drop the padding word */
#endif

  if (p->tot_len > IFXGETH_MAX_TX_BUFFER_SIZE)
  {
#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif
    LINK_STATS_INC(link.drop);
    lwip_geth_DebugLowLevelOutputErrCnt++;
    return ERR_BUF;
  }

  tbuf = lwip_geth_WaitTransmitBufferBounded(ethernetif);
  lwip_geth_DebugLastTxBufferAddr = (uint32)tbuf;

  if (tbuf == NULL_PTR)
  {
#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif
    LINK_STATS_INC(link.drop);
    lwip_geth_DebugLowLevelOutputErrCnt++;
    return ERR_MEM;
  }

  l = 0u;

  for (q = p; q != NULL; q = q->next)
  {
    if (((u32_t)l + (u32_t)q->len) > IFXGETH_MAX_TX_BUFFER_SIZE)
    {
#if ETH_PAD_SIZE
      pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif
      LINK_STATS_INC(link.drop);
      lwip_geth_DebugLowLevelOutputErrCnt++;
      return ERR_BUF;
    }

    lwip_geth_CopyBytes((u8_t *)&tbuf[l], q->payload, (uint32)q->len);
    l = l + q->len;
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: data=%p, %d\n", q->payload, q->len));
    LWIP_ASSERT("low_level_output: length overflow the buffer\n", (l <= IFXGETH_MAX_TX_BUFFER_SIZE));
  }

  {
    IfxGeth_TxDescr *pactTxDescriptor;
    pactTxDescriptor = (IfxGeth_TxDescr *)IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
    lwip_geth_DebugLastTxDescrAddr = (uint32)pactTxDescriptor;
    pactTxDescriptor->TDES2.R.B1L = l;
  }

  lwip_geth_CacheWritebackInvalidateRange(tbuf, (uint32)l);
  lwip_geth_DebugLastTxLen = (uint32)l;
  lwip_geth_SendSingleTransmitBuffer(ethernetif, l);
  lwip_geth_DebugLowLevelOutputOkCount++;

  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: signal length: %d\n", length));

#if ETH_PAD_SIZE
  pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

  LINK_STATS_INC(link.xmit);

  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: return OK\n"));

  return ERR_OK;
}

FBL_RAM_ETH_CODE
static uint16 lwip_geth_GetRxFrameSize(IfxGeth_RxDescr *descr)
{
  uint16 len;

  uint32 rdes3 = descr->RDES3.U;
  uint32 rdes1 = descr->RDES1.U;

  if (((rdes3 & (1UL << 15)) != 0U) ||
      ((rdes1 & (1UL << 7)) != 0U) ||
      ((rdes3 & (1UL << 28)) == 0U))
  {
    /* Error, this block is invalid */
    len = 0xFFFFU;
  }
  else
  {
    uint32 frameLength = rdes3 & 0x7FFFu;

    if ((frameLength <= 4u) || (frameLength > IFXGETH_MAX_RX_BUFFER_SIZE))
    {
      len = LWIP_GETH_RX_FRAME_INVALID;
    }
    else
    {
      /* Subtract CRC */
      len = (uint16)(frameLength - 4u);
    }
  }

  return len;
}

/**
 * Should allocate a pbuf and transfer the bytes of the incoming
 * packet from the interface into the pbuf.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return a pbuf filled with the received packet (including MAC header)
 *         NULL on memory error
 */
FBL_RAM_ETH_CODE
static pbuf_t *lwip_geth_low_level_input(netif_t *netif)
{
  IfxGeth_Eth *ethernetif = NULL_PTR;
  IfxGeth_RxDescr *rxDescr = NULL_PTR;
  pbuf_t      *p = NULL_PTR, *q;
  u8_t        *src;
  u16_t       len;
  u16_t       copyLen;
  u16_t       remaining;
  uint32      descriptorIndex;

  g_LwipRxStage = LWIP_GETH_RX_STAGE_ENTER;
  g_LwipRxCurrentNetifPtr = (uint32)netif;
  g_LwipRxCurrentNetifStatePtr = 0u;
  g_LwipRxExpectedNetifPtr = (uint32)&g_Lwip.netif;
  g_LwipRxExpectedStatePtr = (uint32)lwip_geth_IfxGeth_get();
  g_LwipRxCurrentDescrListPtr = 0u;
  g_LwipRxExpectedDescrListPtr = (uint32)&IfxGeth_Eth_rxDescrList[0][0];
  g_LwipRxHandleDescrPtr = 0u;
  g_LwipRxHardwareCurrentDescPtr = 0u;
  g_LwipRxCurrentDescIndex = LWIP_GETH_RX_DESCRIPTOR_INVALID_INDEX;
  g_LwipRxCurrentDescAddr = 0u;
  g_LwipRxCurrentBufferAddr = 0u;
  g_LwipRxCurrentPbufPtr = 0u;
  g_LwipRxCurrentPbufPayloadPtr = 0u;
  g_LwipRxCurrentPbufLen = 0u;
  g_LwipRxCurrentPbufTotLen = 0u;
  g_LwipRxCurrentPbufRef = 0u;
  lwip_geth_DebugLowLevelInputCallCount++;

  len = 0;
  if (lwip_geth_PrepareRxHandle(netif, &ethernetif) == 0u)
  {
    lwip_geth_DebugRxNullBufferCnt++;
    g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
    return (pbuf_t *)0;
  }

  rxDescr = lwip_geth_GetValidatedRxDescriptor(ethernetif);
  lwip_geth_DebugLastRxDescrAddr = (uint32)rxDescr;
  g_LwipRxCurrentDescAddr = (uint32)rxDescr;
  descriptorIndex = lwip_geth_GetRxDescriptorIndex(rxDescr);
  g_LwipRxCurrentDescIndex = descriptorIndex;
  g_LwipRxStage = LWIP_GETH_RX_STAGE_DESCRIPTOR;

  if (descriptorIndex >= IFXGETH_MAX_RX_DESCRIPTORS)
  {
    lwip_geth_DebugRxBadDescriptorCnt++;
    g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
    return (pbuf_t *)0;
  }

//  lwip_geth_CacheInvalidateRange(rxDescr, sizeof(*rxDescr));

  if ((rxDescr != NULL_PTR) && (rxDescr->RDES3.R.OWN == 0u))
  {
    len = lwip_geth_GetRxFrameSize(rxDescr);
  }

  if (len == 0)
  {
    g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
    return (pbuf_t *)0;
  }

  g_LwipRxStage = LWIP_GETH_RX_STAGE_LENGTH;

  if (len == LWIP_GETH_RX_FRAME_INVALID)
  {
    lwip_geth_DebugRxInvalidFrameCnt++;
    lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
    g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
    return (pbuf_t *)0;
  }

#if ETH_PAD_SIZE
    len += ETH_PAD_SIZE; /* allow room for Ethernet padding */
#endif

  /* We allocate a pbuf chain of pbufs from the pool. */
  p = pbuf_alloc(PBUF_RAW, len, PBUF_POOL);
  g_LwipRxStage = LWIP_GETH_RX_STAGE_ALLOC;

  if (p != NULL)
  {
    g_LwipRxCurrentPbufPtr = (uint32)p;
    g_LwipRxCurrentPbufPayloadPtr = (uint32)p->payload;
    g_LwipRxCurrentPbufLen = (uint32)p->len;
    g_LwipRxCurrentPbufTotLen = (uint32)p->tot_len;
    g_LwipRxCurrentPbufRef = (uint32)p->ref;
#if ETH_PAD_SIZE
    pbuf_header(p, -ETH_PAD_SIZE); /* drop the padding word */
#endif

    copyLen = p->tot_len;
    src = (rxDescr != NULL_PTR) ? (u8_t *)rxDescr->RDES0.U : NULL_PTR;
    lwip_geth_DebugLastRxBufferAddr = (uint32)src;
    lwip_geth_DebugLastRxLen = (uint32)copyLen;
    g_LwipRxCurrentBufferAddr = (uint32)src;
    g_LwipRxCurrentPbufPayloadPtr = (uint32)p->payload;
    g_LwipRxCurrentPbufLen = (uint32)p->len;
    g_LwipRxCurrentPbufTotLen = (uint32)p->tot_len;
    g_LwipRxCurrentPbufRef = (uint32)p->ref;
    g_LwipRxStage = LWIP_GETH_RX_STAGE_BUFFER;

    if (src == NULL_PTR)
    {
      lwip_geth_DebugRxNullBufferCnt++;
      pbuf_free(p);
      lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
      g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
      return (pbuf_t *)0;
    }

    if (lwip_geth_IsRxBufferValid(descriptorIndex, src, (uint32)copyLen) == 0u)
    {
      lwip_geth_DebugRxInvalidBufferCnt++;
      pbuf_free(p);
      lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
      g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
      return (pbuf_t *)0;
    }

//    lwip_geth_CacheInvalidateRange(src, (uint32)copyLen);
    lwip_geth_DebugLowLevelInputPacketCount++;
    lwip_geth_LowLevelInputPacketCount++;
    g_LwipRxStage = LWIP_GETH_RX_STAGE_COPY;
    remaining = copyLen;

    /* We iterate over the pbuf chain until we have read the entire
     * packet into the pbuf. */
    for (q = p; q != NULL; q = q->next)
    {
      g_LwipRxCurrentPbufPtr = (uint32)q;
      g_LwipRxCurrentPbufPayloadPtr = (uint32)q->payload;
      g_LwipRxCurrentPbufLen = (uint32)q->len;
      g_LwipRxCurrentPbufTotLen = (uint32)q->tot_len;
      g_LwipRxCurrentPbufRef = (uint32)q->ref;

      if (q->payload == NULL_PTR)
      {
        lwip_geth_DebugRxNullPayloadCnt++;
        pbuf_free(p);
        lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
        g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
        return (pbuf_t *)0;
      }

      if ((((uint32)q->payload & 0x1u) != 0u) || (q->len > remaining))
      {
        lwip_geth_DebugRxPbufChainInvalidCnt++;
        pbuf_free(p);
        lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
        g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
        return (pbuf_t *)0;
      }

      /* Read enough bytes to fill this pbuf in the chain. The
       * available data in the pbuf is given by the q->len
       * variable.
       * This does not necessarily have to be a memcpy, you can also preallocate
       * pbufs for a DMA-enabled MAC and after receiving truncate it to the
       * actually received size. In this case, ensure the tot_len member of the
       * pbuf is the sum of the chained pbuf len members.
       */
      /* read data into q->payload, q->len */
      lwip_geth_CopyBytes(q->payload, src, (uint32)q->len);
      src = &src[q->len];
      remaining = (u16_t)(remaining - q->len);

      LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_input: payload=0x%p, len=%d\n", q->payload, q->len));
    }

    if (remaining != 0u)
    {
      lwip_geth_DebugRxPbufChainInvalidCnt++;
      pbuf_free(p);
      lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
      g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
      return (pbuf_t *)0;
    }

    /* acknowledge that packet has been read */
    g_LwipRxStage = LWIP_GETH_RX_STAGE_RELEASE;
    lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);

#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

    LINK_STATS_INC(link.recv);
  }
  else
  {
    lwip_geth_DebugRxAllocFailCnt++;
    LINK_STATS_INC(link.memerr);
    LINK_STATS_INC(link.drop);
    lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
  }

  g_LwipRxStage = LWIP_GETH_RX_STAGE_IDLE;
  return p;
}


FBL_RAM_ETH_CODE
uint8 lwip_geth_netif_input_once(netif_t *netif)
{
  eth_hdr_t *ethhdr;
  pbuf_t    *p;
  err_t      inputRet;

  lwip_geth_DebugNetifInputOnceCount++;

  if (netif == NULL_PTR)
  {
    return 0u;
  }

  p = lwip_geth_low_level_input(netif);

  if (p == NULL_PTR)
  {
    return 0u;
  }

  ethhdr = (eth_hdr_t *)p->payload;
  lwip_geth_DebugLastEthType = (uint32)htons(ethhdr->type);

  switch (htons(ethhdr->type))
  {
    case ETHTYPE_IP:
    case ETHTYPE_ARP:
#if PPPOE_SUPPORT
    case ETHTYPE_PPPOEDISC:
    case ETHTYPE_PPPOE:
#endif
      inputRet = netif->input(p, netif);
      if (inputRet != ERR_OK)
      {
        lwip_geth_DebugNetifInputFailCount++;
        pbuf_free(p);
      }
      else
      {
        lwip_geth_DebugNetifInputOkCount++;
      }
      break;

    default:
      lwip_geth_DebugNetifInputUnknownTypeCount++;
      pbuf_free(p);
      break;
  }

  return 1u;
}

FBL_RAM_ETH_CODE
void lwip_geth_netif_input(void * pvParameters)
{
  netif_t *netif = (netif_t *)pvParameters;
  uint8 processed;
  uint8 budget;

  do
  {
    lwip_geth_DebugNetifInputLoopCount++;
    budget = LWIP_GETH_RX_TASK_BUDGET;

    do
    {
      processed = lwip_geth_netif_input_once(netif);
      if (budget > 0u)
      {
        budget--;
      }
    } while ((processed != 0u) && (budget > 0u));

    if ((processed != 0u) && (budget == 0u))
    {
      lwip_geth_DebugRxBudgetHitCount++;
    }

#if LWIP_GETH_RTOS_ENABLED
    if (processed == 0u)
    {
      lwip_geth_DebugRxWaitCount++;
      lwip_geth_Lwip_WaitForInput();
    }
#endif
  } while (LWIP_GETH_RTOS_ENABLED);
}

FBL_RAM_ETH_CODE
uint8 lwip_geth_RamClosureIsValid(void)
{
  g_LwipGethRuntimeClosureFailStep = 0u;

#define LWIP_GETH_CLOSURE_CHECK(step, symbol) \
  do { if(FblRamRuntime_IsExecutableAddress((uint32)(symbol)) == 0u) { g_LwipGethRuntimeClosureFailStep = (step); return 0u; } } while(0)

  LWIP_GETH_CLOSURE_CHECK(1u, lwip_geth_CopyBytes);
  LWIP_GETH_CLOSURE_CHECK(2u, lwip_geth_IsExpectedRxDescriptorAddress);
  LWIP_GETH_CLOSURE_CHECK(3u, lwip_geth_GetRxDescriptorIndex);
  LWIP_GETH_CLOSURE_CHECK(4u, lwip_geth_GetValidatedRxDescriptor);
  LWIP_GETH_CLOSURE_CHECK(5u, lwip_geth_PrepareRxHandle);
  LWIP_GETH_CLOSURE_CHECK(6u, lwip_geth_IsDmaNonCachedRange);
  LWIP_GETH_CLOSURE_CHECK(7u, lwip_geth_IsRxBufferValid);
  LWIP_GETH_CLOSURE_CHECK(8u, lwip_geth_RestoreRxDescriptorBuffer);
//  LWIP_GETH_CLOSURE_CHECK(9u, lwip_geth_CacheInvalidateRange);
  LWIP_GETH_CLOSURE_CHECK(10u, lwip_geth_CacheWritebackInvalidateRange);
  LWIP_GETH_CLOSURE_CHECK(11u, lwip_geth_FreeReceiveDescriptor);
  LWIP_GETH_CLOSURE_CHECK(12u, lwip_geth_WaitTransmitBufferBounded);
  LWIP_GETH_CLOSURE_CHECK(13u, lwip_geth_SendSingleTransmitBuffer);
  LWIP_GETH_CLOSURE_CHECK(14u, lwip_geth_low_level_output);
  LWIP_GETH_CLOSURE_CHECK(15u, lwip_geth_GetRxFrameSize);
  LWIP_GETH_CLOSURE_CHECK(16u, lwip_geth_low_level_input);
  LWIP_GETH_CLOSURE_CHECK(17u, lwip_geth_netif_input_once);
  LWIP_GETH_CLOSURE_CHECK(18u, lwip_geth_netif_input);
  LWIP_GETH_CLOSURE_CHECK(19u, lwip_geth_AssertFail);
  LWIP_GETH_CLOSURE_CHECK(20u, FblRamGeth_SetLineSpeed);
  LWIP_GETH_CLOSURE_CHECK(21u, FblRamGeth_FreeReceiveBuffer);
  LWIP_GETH_CLOSURE_CHECK(22u, FblRamGeth_ShuffleRxDescriptor);
  LWIP_GETH_CLOSURE_CHECK(23u, FblRamGeth_GetTransmitBuffer);
  LWIP_GETH_CLOSURE_CHECK(24u, FblRamGeth_WakeupReceiver);
  LWIP_GETH_CLOSURE_CHECK(25u, FblRamGeth_WakeupTransmitter);

  if ((g_Lwip.netif.input != NULL_PTR) &&
      (FblRamRuntime_IsExecutableAddress((uint32)g_Lwip.netif.input) == 0u))
  {
    g_LwipGethRuntimeClosureFailStep = 25u;
    return 0u;
  }

  if ((g_Lwip.netif.output != NULL_PTR) &&
      (FblRamRuntime_IsExecutableAddress((uint32)g_Lwip.netif.output) == 0u))
  {
    g_LwipGethRuntimeClosureFailStep = 26u;
    return 0u;
  }

  if ((g_Lwip.netif.linkoutput != NULL_PTR) &&
      (FblRamRuntime_IsExecutableAddress((uint32)g_Lwip.netif.linkoutput) == 0u))
  {
    g_LwipGethRuntimeClosureFailStep = 27u;
    return 0u;
  }

#undef LWIP_GETH_CLOSURE_CHECK

  return 1u;
}

/**
 * Should be called at the beginning of the program to set up the
 * network interface. It calls the function low_level_init() to do the
 * actual setup of the hardware.
 *
 * This function should be passed as a parameter to netif_add().
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return ERR_OK if the loopif is initialized
 *         ERR_MEM if private data couldn't be allocated
 *         any other err_t on error
 */
err_t lwip_geth_netif_init(netif_t *netif)
{
  IfxGeth_Eth *ethernetif;

  LWIP_ASSERT("netif != NULL", (netif != NULL));
  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("ifx_netif_init ( %p)\n", netif));

  ethernetif = lwip_geth_IfxGeth_get();

  if (ethernetif == NULL)
  {
    LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_init: out of memory\n"));
    return ERR_MEM;
  }

#if LWIP_NETIF_HOSTNAME
  /* Initialize interface hostname */
  netif->hostname = "lwip";
#endif /* LWIP_NETIF_HOSTNAME */

  /*
   * Initialize the snmp variables and counters inside the struct netif.
   * The last argument should be replaced with your link speed, in units
   * of bits per second.
   */
  /* NETIF_INIT_SNMP(netif, snmp_ifType_ethernet_csmacd, LINK_SPEED_OF_YOUR_NETIF_IN_BPS); */

  netif->state      = ethernetif;
  netif->name[0]    = IFNAME0;
  netif->name[1]    = IFNAME1;
  /* We directly use etharp_output() here to save a function call.
   * You can instead declare your own function an call etharp_output()
   * from it if you have to do some checks before sending (e.g. if link
   * is available...) */
  netif->output     = etharp_output;
  netif->linkoutput = lwip_geth_low_level_output;

  /* initialize the hardware */
  if (lwip_geth_low_level_init(netif) == 0u)
  {
    return ERR_IF;
  }

  return ERR_OK;
}

/* CODE_BLOCK_END */
