/**
 * @file lwip_geth_netif.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * Copyright (c) 2015-2025, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/*
 * Copyright (c) 2001-2004 Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * This file is part of the lwIP TCP/IP stack.
 *
 * Author: Adam Dunkels <adam@sics.se>
 *
 */

/**
 * This file is a skeleton for developing Ethernet network interface
 * drivers for lwIP. Add code to the low_level functions and do a
 * search-and-replace for the word "ethernetif" to replace it with
 * something that better describes your network interface.
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "lwip/opt.h"

#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include <lwip/stats.h>
#include <lwip/snmp.h>
#include "netif/etharp.h"
#include "netif/ppp/pppoe.h"
#include "Cpu/Std/IfxCpu_Intrinsics.h"
#include "IfxGeth_Eth.h"
#include "lwip_geth_lwip.h"
#include "lwip_geth_netif.h"
#include "lwip_geth_conf.h"
#include <string.h>
#if (PHY_DEVICE_NAME == PHY_DP83825I)
#include "lwip_geth_private_phy_dp83825i.h"
#endif
#if (PHY_DEVICE_NAME == PHY_RTL8211F)
#include "lwip_geth_private_phy_rtl8211f.h"
#endif

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
/* Define those to better describe your network interface. */
#define IFNAME0 'e'
#define IFNAME1 'n'
#define LWIP_GETH_RX_TASK_BUDGET       64u
#define LWIP_GETH_RX_FRAME_INVALID     0xFFFFu
#define LWIP_GETH_CACHE_LINE_SIZE      32u

#ifndef __cacheai
#define __cacheai(p)  __asm__ volatile("cachea.i [%0]0"::"a"(p))
#endif

#ifndef __cacheawi
#define __cacheawi(p) __asm__ volatile("cachea.wi [%0]0"::"a"(p))
#endif

volatile uint32 lwip_geth_DebugRxInvalidFrameCnt;
volatile uint32 lwip_geth_DebugRxAllocFailCnt;
volatile uint32 lwip_geth_DebugRxNullBufferCnt;
volatile uint32 lwip_geth_DebugRxNullPayloadCnt;
volatile uint32 lwip_geth_DebugTxNoBufferCnt;
volatile uint32 lwip_geth_DebugLowLevelOutputCount;
volatile uint32 lwip_geth_DebugLowLevelOutputOkCount;
volatile uint32 lwip_geth_DebugLowLevelOutputErrCnt;
volatile uint32 lwip_geth_DebugLowLevelInputCallCount;
volatile uint32 lwip_geth_DebugLowLevelInputPacketCount;
volatile uint32 lwip_geth_DebugNetifInputLoopCount;
volatile uint32 lwip_geth_DebugNetifInputOnceCount;
volatile uint32 lwip_geth_DebugNetifInputOkCount;
volatile uint32 lwip_geth_DebugNetifInputFailCount;
volatile uint32 lwip_geth_DebugNetifInputUnknownTypeCount;
volatile uint32 lwip_geth_DebugRxWaitCount;
volatile uint32 lwip_geth_DebugRxBudgetHitCount;
volatile uint32 lwip_geth_DebugLastRxLen;
volatile uint32 lwip_geth_DebugLastTxLen;
volatile uint32 lwip_geth_DebugLastEthType;
volatile uint32 lwip_geth_DebugLastTxDescrAddr;
volatile uint32 lwip_geth_DebugLastTxBufferAddr;
volatile uint32 lwip_geth_DebugLastRxDescrAddr;
volatile uint32 lwip_geth_DebugLastRxBufferAddr;
volatile uint32 lwip_geth_DebugRxCacheInvalidateCnt;
volatile uint32 lwip_geth_DebugTxCacheWritebackCnt;

/***********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/
/**
 * Helper struct to hold private data used to operate your ethernet interface.
 * Keeping the ethernet address of the MAC in this struct is not necessary
 * as it is already kept in the struct netif.
 * But this is only an example, anyway...
 */
struct ethernetif
{
  eth_addr_t *ethaddr;
  /* Add whatever per-interface state that is needed here. */
};

static void lwip_geth_CacheInvalidateRange(const void *address, uint32 length)
{
  uint32 line;
  uint32 end;

  if ((address == NULL_PTR) || (length == 0u))
  {
    return;
  }

  line = ((uint32)address) & ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);
  end = (((uint32)address) + length + (LWIP_GETH_CACHE_LINE_SIZE - 1u)) &
      ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);

  while (line < end)
  {
    __cacheai((uint8 *)line);
    line += LWIP_GETH_CACHE_LINE_SIZE;
  }

  __dsync();
  lwip_geth_DebugRxCacheInvalidateCnt++;
}

static void lwip_geth_CacheWritebackInvalidateRange(const void *address, uint32 length)
{
  uint32 line;
  uint32 end;

  if ((address == NULL_PTR) || (length == 0u))
  {
    return;
  }

  line = ((uint32)address) & ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);
  end = (((uint32)address) + length + (LWIP_GETH_CACHE_LINE_SIZE - 1u)) &
      ~(LWIP_GETH_CACHE_LINE_SIZE - 1u);

  while (line < end)
  {
    __cacheawi((uint8 *)line);
    line += LWIP_GETH_CACHE_LINE_SIZE;
  }

  __dsync();
  lwip_geth_DebugTxCacheWritebackCnt++;
}

static void lwip_geth_FreeReceiveDescriptor(IfxGeth_Eth *ethernetif, IfxGeth_RxDescr *rxDescr)
{
  IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
  lwip_geth_CacheWritebackInvalidateRange(rxDescr, sizeof(*rxDescr));
  IfxGeth_Eth_wakeupReceiver(ethernetif, IfxGeth_RxDmaChannel_0);
}

static void lwip_geth_PrepareDmaMemory(const IfxGeth_Eth_Config *config)
{
  const IfxGeth_Eth_TxChannelConfig *txConfig;
  const IfxGeth_Eth_RxChannelConfig *rxConfig;
  uint32 i;

  if ((config == NULL_PTR) || (config->dma.numOfTxChannels == 0u) || (config->dma.numOfRxChannels == 0u))
  {
    return;
  }

  for (i = 0u; i < config->dma.numOfTxChannels; i++)
  {
    txConfig = &config->dma.txChannel[i];

    if ((txConfig->channelEnable != FALSE) && (txConfig->txDescrList != NULL_PTR))
    {
      lwip_geth_CacheWritebackInvalidateRange(txConfig->txDescrList->descr,
          (uint32)(IFXGETH_MAX_TX_DESCRIPTORS * sizeof(IfxGeth_TxDescr)));
    }

    if ((txConfig->channelEnable != FALSE) &&
        (txConfig->txBuffer1StartAddress != NULL_PTR) &&
        (txConfig->txBuffer1Size > 0u))
    {
      lwip_geth_CacheWritebackInvalidateRange(txConfig->txBuffer1StartAddress,
          (uint32)(IFXGETH_MAX_TX_DESCRIPTORS * txConfig->txBuffer1Size));
    }
  }

  for (i = 0u; i < config->dma.numOfRxChannels; i++)
  {
    rxConfig = &config->dma.rxChannel[i];

    if ((rxConfig->channelEnable != FALSE) && (rxConfig->rxDescrList != NULL_PTR))
    {
      lwip_geth_CacheWritebackInvalidateRange(rxConfig->rxDescrList->descr,
          (uint32)(IFXGETH_MAX_RX_DESCRIPTORS * sizeof(IfxGeth_RxDescr)));
    }

    if ((rxConfig->channelEnable != FALSE) &&
        (rxConfig->rxBuffer1StartAddress != NULL_PTR) &&
        (rxConfig->rxBuffer1Size > 0u))
    {
      lwip_geth_CacheWritebackInvalidateRange(rxConfig->rxBuffer1StartAddress,
          (uint32)(IFXGETH_MAX_RX_DESCRIPTORS * rxConfig->rxBuffer1Size));
    }
  }
}

static void lwip_geth_SendSingleTransmitBuffer(IfxGeth_Eth *ethernetif, uint16 packetLength)
{
  volatile IfxGeth_TxDescr *firstDescr =
      IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
  volatile IfxGeth_TxDescr *lastDescr =
      &ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrList->descr[IFXGETH_MAX_TX_DESCRIPTORS - 1u];
  volatile IfxGeth_TxDescr *nextDescr;

  if (firstDescr == lastDescr)
  {
    nextDescr = IfxGeth_Eth_getBaseTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
  }
  else
  {
    nextDescr = &firstDescr[1];
  }

  firstDescr->TDES3.R.FL_TPL = packetLength;
  firstDescr->TDES3.R.TSE = 0u;
  firstDescr->TDES3.R.CIC_TPL = 3u;
  firstDescr->TDES3.R.SAIC = 0u;
  firstDescr->TDES3.R.CPC = 0u;
  firstDescr->TDES3.R.FD = 1u;
  firstDescr->TDES3.R.LD = 1u;
  firstDescr->TDES2.R.IOC = 1u;
  firstDescr->TDES2.R.B1L = packetLength;
  firstDescr->TDES3.R.OWN = 1u;

  lwip_geth_CacheWritebackInvalidateRange((const void *)firstDescr, sizeof(*firstDescr));
  ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrPtr = firstDescr;
  IfxGeth_dma_setTxDescriptorTailPointer(ethernetif->gethSFR, IfxGeth_TxDmaChannel_0, (uint32)nextDescr);
  IfxGeth_Eth_wakeupTransmitter(ethernetif, IfxGeth_TxDmaChannel_0);
  ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrPtr = nextDescr;
  ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txCount++;
}

/***********************************************************************************************************************
 * FUNCTION IMPLEMENTATIONS
 **********************************************************************************************************************/
/**
 * In this function, the hardware should be initialized.
 * Called from ethernetif_init().
 *
 * @param netif the already initialized lwip network interface structure
 *        for this ethernetif
 */
static void lwip_geth_low_level_init(netif_t *netif)
{
  IfxGeth_Eth *ethernetif = netif->state;
  int         i;

  /* set MAC hardware address length */
  netif->hwaddr_len = ETHARP_HWADDR_LEN;

  /* set MAC hardware address */
  for (i = 0; i < ETHARP_HWADDR_LEN; i++)
  {
    netif->hwaddr[i] = g_Lwip.eth_addr.addr[i];
  }

  /* maximum transfer unit */
  netif->mtu = lwip_geth_handle->app_config->mtu;

  /* device capabilities */
  /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
  /* we don't set the LINK_UP flag because we don't say when it is linked */
  netif->flags = NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP;

  /* Do whatever else is needed to initialize interface. */
  {
    IfxGeth_Eth_Config GethConfig;
    GethConfig = *(lwip_geth_handle->app_config->geth_lld_config);

    /* We get the ID of Ethernet Phy do determine the board version, also needed for SCR */
    if (lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins != NULL)
    {
      IfxPort_setPinModeOutput(lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdc->pin.port,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdc->pin.pinIndex,IfxPort_OutputMode_pushPull,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdc->select);

      GETH_GPCTL.B.ALTI0  = lwip_geth_handle->app_config->geth_lld_config->pins.rmiiPins->mdio->inSelect;
    }
    else if (lwip_geth_handle->app_config->geth_lld_config->pins.miiPins != NULL)
    {
      IfxPort_setPinModeOutput(lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdc->pin.port,
                               lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdc->pin.pinIndex,IfxPort_OutputMode_pushPull,
                               lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdc->select);

      GETH_GPCTL.B.ALTI0  = lwip_geth_handle->app_config->geth_lld_config->pins.miiPins->mdio->inSelect;
    }
    else
    {
      IfxPort_setPinModeOutput(lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdc->pin.port,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdc->pin.pinIndex,IfxPort_OutputMode_pushPull,
                               lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdc->select);

      GETH_GPCTL.B.ALTI0  = lwip_geth_handle->app_config->geth_lld_config->pins.rgmiiPins->mdio->inSelect;
    }

    IFXGETH_PHY_WAIT_GMII_READY();
    /* first we wait that we are able to communicate with the Phy */
    do
    {
      uint32 dataToSend = 0x8000;
      IfxGeth_phy_Clause22_readMDIORegister(0,0,&dataToSend);
    } while (GETH_MAC_MDIO_DATA.U & 0x8000);                                                      /* wait for reset to finish */

    /* reset PHY */
    /* put data */
    IfxGeth_Phy_Clause22_writeMDIORegister(0,0,0x8000);

    do
    {
      uint32 dataToSend = 0x8000;
      IfxGeth_phy_Clause22_readMDIORegister(0,0,&dataToSend);
    } while (GETH_MAC_MDIO_DATA.U & 0x8000);                                                      /* wait for reset to finish */

    /* initialize the module */
    IfxGeth_Eth_initModule(ethernetif, &GethConfig);
    lwip_geth_PrepareDmaMemory(&GethConfig);

    /* initialize the PHY */
#if (PHY_DEVICE_NAME == PHY_DP83825I)
    lwip_geth_private_Phy_Dp83825i_init();
#endif

#if (PHY_DEVICE_NAME == PHY_RTL8211F)
    lwip_geth_private_Phy_Rtl8211f_init();
#endif
    /* and enable transmitter/receiver */
    IfxGeth_Eth_startTransmitters(ethernetif, 1);
    IfxGeth_Eth_startReceivers(ethernetif, 1);

    /* The ETH is ready for use now! */
    /* we set the LINK_UP flag if we have a valid link */
    if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSTS == 1)
    {
      /* we have a valid link */
      netif->flags |= NETIF_FLAG_LINK_UP;
      /* we set the correct duplexMode */
      if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKMOD == 1)
      {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
      }
      else
      {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
      }
      /* we set the correct speed */
      if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 0)
      {
        /* 10MBit speed */
        IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
      }
      else
      {
        if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 1)
        {
          /* 100MBit speed */
          IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
        }
        else
        {
          /* 1000MBit speed */
          IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_1000Mbps);
        }
      }
    }
  }
}

/**
 * This function should do the actual transmission of the packet. The packet is
 * contained in the pbuf that is passed to the function. This pbuf
 * might be chained.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
 * @return ERR_OK if the packet could be sent
 *         an err_t value if the packet couldn't be sent
 *
 * @note Returning ERR_MEM here if a DMA queue of your MAC is full can lead to
 *       strange results. You might consider waiting for space in the DMA queue
 *       to become availale since the stack doesn't retry to send a packet
 *       dropped because of memory failure (except for the TCP timers).
 */
static err_t lwip_geth_low_level_output(netif_t *netif, pbuf_t *p)
{
  IfxGeth_Eth *ethernetif = netif->state;
  struct pbuf *q;
  u8_t *tbuf;
  u16_t l;

  lwip_geth_DebugLowLevelOutputCount++;

#ifdef LWIP_DEBUG
  u16_t       length = p->tot_len;
#endif
  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output (p=%p)\n", p));

#if ETH_PAD_SIZE
  pbuf_header(p, -ETH_PAD_SIZE); /* drop the padding word */
#endif

  if (p->tot_len > IFXGETH_MAX_TX_BUFFER_SIZE)
  {
#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif
    LINK_STATS_INC(link.drop);
    lwip_geth_DebugLowLevelOutputErrCnt++;
    return ERR_BUF;
  }

  tbuf = IfxGeth_Eth_waitTransmitBuffer(ethernetif, IfxGeth_TxDmaChannel_0);
  lwip_geth_DebugLastTxBufferAddr = (uint32)tbuf;

  if (tbuf == NULL_PTR)
  {
#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif
    LINK_STATS_INC(link.drop);
    lwip_geth_DebugTxNoBufferCnt++;
    lwip_geth_DebugLowLevelOutputErrCnt++;
    return ERR_MEM;
  }

  l = 0u;

  for (q = p; q != NULL; q = q->next)
  {
    if (((u32_t)l + (u32_t)q->len) > IFXGETH_MAX_TX_BUFFER_SIZE)
    {
#if ETH_PAD_SIZE
      pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif
      LINK_STATS_INC(link.drop);
      lwip_geth_DebugLowLevelOutputErrCnt++;
      return ERR_BUF;
    }

    memcpy((u8_t *)&tbuf[l], q->payload, q->len);
    l = l + q->len;
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: data=%p, %d\n", q->payload, q->len));
    LWIP_ASSERT("low_level_output: length overflow the buffer\n", (l <= IFXGETH_MAX_TX_BUFFER_SIZE));
  }

  {
    IfxGeth_TxDescr *pactTxDescriptor;
    pactTxDescriptor = (IfxGeth_TxDescr *)IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
    lwip_geth_DebugLastTxDescrAddr = (uint32)pactTxDescriptor;
    pactTxDescriptor->TDES2.R.B1L = l;
  }

  lwip_geth_CacheWritebackInvalidateRange(tbuf, (uint32)l);
  lwip_geth_DebugLastTxLen = (uint32)l;
  lwip_geth_SendSingleTransmitBuffer(ethernetif, l);
  lwip_geth_DebugLowLevelOutputOkCount++;

  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: signal length: %d\n", length));

#if ETH_PAD_SIZE
  pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

  LINK_STATS_INC(link.xmit);

  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: return OK\n"));

  return ERR_OK;
}

static uint16 lwip_geth_GetRxFrameSize(IfxGeth_RxDescr *descr)
{
  uint16 len;

  uint32 rdes3 = descr->RDES3.U;
  uint32 rdes1 = descr->RDES1.U;

  if (((rdes3 & (1UL << 15)) != 0U) ||
      ((rdes1 & (1UL << 7)) != 0U) ||
      ((rdes3 & (1UL << 28)) == 0U))
  {
    /* Error, this block is invalid */
    len = 0xFFFFU;
  }
  else
  {
    uint32 frameLength = rdes3 & 0x7FFFu;

    if (frameLength <= 4u)
    {
      len = LWIP_GETH_RX_FRAME_INVALID;
    }
    else
    {
      /* Subtract CRC */
      len = (uint16)(frameLength - 4u);
    }
  }

  return len;
}

/**
 * Should allocate a pbuf and transfer the bytes of the incoming
 * packet from the interface into the pbuf.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return a pbuf filled with the received packet (including MAC header)
 *         NULL on memory error
 */
static pbuf_t *lwip_geth_low_level_input(netif_t *netif)
{
  IfxGeth_Eth *ethernetif = netif->state;
  IfxGeth_RxDescr *rxDescr = NULL_PTR;
  pbuf_t      *p, *q;
  u8_t        *src;
  u16_t       len;

  lwip_geth_DebugLowLevelInputCallCount++;

  len = 0;
  rxDescr = (IfxGeth_RxDescr *)IfxGeth_Eth_getActualRxDescriptor(ethernetif, IfxGeth_RxDmaChannel_0);
  lwip_geth_DebugLastRxDescrAddr = (uint32)rxDescr;
  lwip_geth_CacheInvalidateRange(rxDescr, sizeof(*rxDescr));

  if ((rxDescr != NULL_PTR) && (rxDescr->RDES3.R.OWN == 0u))
  {
    len = lwip_geth_GetRxFrameSize(rxDescr);
  }

  if (len == 0)
  {
    return (pbuf_t *)0;
  }

  if (len == LWIP_GETH_RX_FRAME_INVALID)
  {
    lwip_geth_DebugRxInvalidFrameCnt++;
    lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
    return (pbuf_t *)0;
  }

#if ETH_PAD_SIZE
    len += ETH_PAD_SIZE; /* allow room for Ethernet padding */
#endif

  /* We allocate a pbuf chain of pbufs from the pool. */
  p = pbuf_alloc(PBUF_RAW, len, PBUF_POOL);

  if (p != NULL)
  {
#if ETH_PAD_SIZE
    pbuf_header(p, -ETH_PAD_SIZE); /* drop the padding word */
#endif

    src = (rxDescr != NULL_PTR) ? (u8_t *)rxDescr->RDES0.U : NULL_PTR;
    lwip_geth_DebugLastRxBufferAddr = (uint32)src;
    lwip_geth_DebugLastRxLen = (uint32)len;

    if (src == NULL_PTR)
    {
      lwip_geth_DebugRxNullBufferCnt++;
      pbuf_free(p);
      lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
      return (pbuf_t *)0;
    }

    lwip_geth_CacheInvalidateRange(src, (uint32)len);
    lwip_geth_DebugLowLevelInputPacketCount++;

    /* We iterate over the pbuf chain until we have read the entire
     * packet into the pbuf. */
    for (q = p; q != NULL; q = q->next)
    {
      if (q->payload == NULL_PTR)
      {
        lwip_geth_DebugRxNullPayloadCnt++;
        pbuf_free(p);
        lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
        return (pbuf_t *)0;
      }

      /* Read enough bytes to fill this pbuf in the chain. The
       * available data in the pbuf is given by the q->len
       * variable.
       * This does not necessarily have to be a memcpy, you can also preallocate
       * pbufs for a DMA-enabled MAC and after receiving truncate it to the
       * actually received size. In this case, ensure the tot_len member of the
       * pbuf is the sum of the chained pbuf len members.
       */
      /* read data into q->payload, q->len */
      memcpy(q->payload, src, q->len);
      src = &src[q->len];

      LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_input: payload=0x%p, len=%d\n", q->payload, q->len));
    }

    /* acknowledge that packet has been read */
    lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);

#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

    LINK_STATS_INC(link.recv);
  }
  else
  {
    lwip_geth_DebugRxAllocFailCnt++;
    LINK_STATS_INC(link.memerr);
    LINK_STATS_INC(link.drop);
    lwip_geth_FreeReceiveDescriptor(ethernetif, rxDescr);
  }

  return p;
}


uint8 lwip_geth_netif_input_once(netif_t *netif)
{
  eth_hdr_t *ethhdr;
  pbuf_t    *p;
  err_t      inputRet;

  lwip_geth_DebugNetifInputOnceCount++;

  if (netif == NULL_PTR)
  {
    return 0u;
  }

  p = lwip_geth_low_level_input(netif);

  if (p == NULL_PTR)
  {
    return 0u;
  }

  ethhdr = (eth_hdr_t *)p->payload;
  lwip_geth_DebugLastEthType = (uint32)htons(ethhdr->type);

  switch (htons(ethhdr->type))
  {
    case ETHTYPE_IP:
    case ETHTYPE_ARP:
#if PPPOE_SUPPORT
    case ETHTYPE_PPPOEDISC:
    case ETHTYPE_PPPOE:
#endif
      inputRet = netif->input(p, netif);
      if (inputRet != ERR_OK)
      {
        lwip_geth_DebugNetifInputFailCount++;
        pbuf_free(p);
      }
      else
      {
        lwip_geth_DebugNetifInputOkCount++;
      }
      break;

    default:
      lwip_geth_DebugNetifInputUnknownTypeCount++;
      pbuf_free(p);
      break;
  }

  return 1u;
}

void lwip_geth_netif_input(void * pvParameters)
{
  netif_t *netif = (netif_t *)pvParameters;
  uint8 processed;
  uint8 budget;

  do
  {
    lwip_geth_DebugNetifInputLoopCount++;
    budget = LWIP_GETH_RX_TASK_BUDGET;

    do
    {
      processed = lwip_geth_netif_input_once(netif);
      if (budget > 0u)
      {
        budget--;
      }
    } while ((processed != 0u) && (budget > 0u));

    if ((processed != 0u) && (budget == 0u))
    {
      lwip_geth_DebugRxBudgetHitCount++;
    }

#if LWIP_GETH_RTOS_ENABLED
    if (processed == 0u)
    {
      lwip_geth_DebugRxWaitCount++;
      lwip_geth_Lwip_WaitForInput();
    }
#endif
  } while (LWIP_GETH_RTOS_ENABLED);
}

/**
 * Should be called at the beginning of the program to set up the
 * network interface. It calls the function low_level_init() to do the
 * actual setup of the hardware.
 *
 * This function should be passed as a parameter to netif_add().
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return ERR_OK if the loopif is initialized
 *         ERR_MEM if private data couldn't be allocated
 *         any other err_t on error
 */
err_t lwip_geth_netif_init(netif_t *netif)
{
  IfxGeth_Eth *ethernetif;

  LWIP_ASSERT("netif != NULL", (netif != NULL));
  LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("ifx_netif_init ( %p)\n", netif));

  ethernetif = lwip_geth_IfxGeth_get();

  if (ethernetif == NULL)
  {
    LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_init: out of memory\n"));
    return ERR_MEM;
  }

#if LWIP_NETIF_HOSTNAME
  /* Initialize interface hostname */
  netif->hostname = "lwip";
#endif /* LWIP_NETIF_HOSTNAME */

  /*
   * Initialize the snmp variables and counters inside the struct netif.
   * The last argument should be replaced with your link speed, in units
   * of bits per second.
   */
  /* NETIF_INIT_SNMP(netif, snmp_ifType_ethernet_csmacd, LINK_SPEED_OF_YOUR_NETIF_IN_BPS); */

  netif->state      = ethernetif;
  netif->name[0]    = IFNAME0;
  netif->name[1]    = IFNAME1;
  /* We directly use etharp_output() here to save a function call.
   * You can instead declare your own function an call etharp_output()
   * from it if you have to do some checks before sending (e.g. if link
   * is available...) */
  netif->output     = etharp_output;
  netif->linkoutput = lwip_geth_low_level_output;

  /* initialize the hardware */
  lwip_geth_low_level_init(netif);

  return ERR_OK;
}

/* CODE_BLOCK_END */
