/**
 * @file lwip_geth_lwip.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * LWIP_GETH - Configures a GETH module with LwIP stack.
 *
 * Copyright (c) 2015-2025, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG.
 ***********************************************************************************************************************
 *
 * @endcond
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include <Cpu/Std/Ifx_Types.h>
#include <Cpu/Std/IfxCpu.h>
#include "Ifx_Cfg.h"
#include "IfxGeth_Eth.h"
#include "lwip_geth_lwip.h"
#include "lwipopts.h"
#include "lwip_geth_netif.h"
#include <string.h>
#include <stdarg.h>
#include "lwip_geth_conf.h"
#if (PHY_DEVICE_NAME == PHY_DP83825I)
#include "lwip_geth_private_phy_dp83825i.h"
#endif
#if (PHY_DEVICE_NAME == PHY_RTL8211F)
#include "lwip_geth_private_phy_rtl8211f.h"
#endif
#if LWIP_GETH_RTOS_ENABLED
#include "tcpip.h"
#include "FreeRTOS.h"
#include "task.h"
#include "portmacro.h"
#endif

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
#define IFX_LWIP_TIMER_TICK_MS              (1U)    /* number of timer ticks per millisecond */

#define IFX_LWIP_ARP_PERIOD                 (ARP_TMR_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_TCP_FAST_PERIOD            (TCP_FAST_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_TCP_SLOW_PERIOD            (TCP_SLOW_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_DHCP_COARSE_PERIOD         (DHCP_COARSE_TIMER_MSECS / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_DHCP_FINE_PERIOD           (DHCP_FINE_TIMER_MSECS / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_LINK_PERIOD                (100U / IFX_LWIP_TIMER_TICK_MS) /* 100 ms */
#define IFX_LWIP_EMAC_BLOCK_TIME_FOR_INPUT  ( ( portTickType ) 100 )
#define LWIP_GETH_RX_POLL_BUDGET            (32U)
#define LWIP_GETH_TIMER_HZ_PER_MS           (1000U)
#define LWIP_GETH_TIMER_FALLBACK_FREQ_HZ    (100000000U)
#define LWIP_GETH_TIMER_CATCHUP_LIMIT       (100U)
#if LWIP_IPV4 && LWIP_ACD
#define IFX_LWIP_ACD_PERIOD                 (ACD_TMR_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#endif

#define IFX_LWIP_FLAG_ARP                   (1U << 1)
#define IFX_LWIP_FLAG_TCP_FAST              (1U << 2)
#define IFX_LWIP_FLAG_TCP_SLOW              (1U << 3)
#define IFX_LWIP_FLAG_LINK                  (1U << 4)
#define IFX_LWIP_FLAG_DHCP_COARSE           (1U << 5)
#define IFX_LWIP_FLAG_DHCP_FINE             (1U << 6)
#if LWIP_IPV4 && LWIP_ACD
#define IFX_LWIP_FLAG_ACD                   (1U << 7)
#endif

#define Ifx_Lwip_timerIncr(var, PERIOD, FLAG) \
{                                             \
  var += 1;                                   \
  if (var >= PERIOD)                          \
  {                                           \
    var         = 0;                          \
    timerFlags |= FLAG;                       \
  }                                           \
}

#define LWIP_GETH_STATIC_ASSERT(name, expression) typedef char name[(expression) ? 1 : -1]
#define LWIP_GETH_RX_DESCRIPTOR_BYTES (IFXGETH_NUM_MODULES * IFXGETH_NUM_RX_CHANNELS * \
                                       IFXGETH_MAX_RX_DESCRIPTORS * sizeof(IfxGeth_RxDescr))
#define LWIP_GETH_TX_DESCRIPTOR_BYTES (IFXGETH_NUM_MODULES * IFXGETH_NUM_TX_CHANNELS * \
                                       IFXGETH_MAX_TX_DESCRIPTORS * sizeof(IfxGeth_TxDescr))
#define LWIP_GETH_RX_BUFFER_BYTES     (IFXGETH_MAX_RX_DESCRIPTORS * IFXGETH_MAX_RX_BUFFER_SIZE)
#define LWIP_GETH_TX_BUFFER_BYTES     (IFXGETH_MAX_TX_DESCRIPTORS * IFXGETH_MAX_TX_BUFFER_SIZE)
#define LWIP_GETH_DMA_BYTES           (LWIP_GETH_RX_DESCRIPTOR_BYTES + LWIP_GETH_TX_DESCRIPTOR_BYTES + \
                                       LWIP_GETH_RX_BUFFER_BYTES + LWIP_GETH_TX_BUFFER_BYTES)

LWIP_GETH_STATIC_ASSERT(lwip_geth_rx_descriptor_count_nonzero, IFXGETH_MAX_RX_DESCRIPTORS > 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_tx_descriptor_count_nonzero, IFXGETH_MAX_TX_DESCRIPTORS > 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_rx_descriptor_size_word_aligned, (sizeof(IfxGeth_RxDescr) % 4u) == 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_tx_descriptor_size_word_aligned, (sizeof(IfxGeth_TxDescr) % 4u) == 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_rx_buffer_size_aligned, (IFXGETH_MAX_RX_BUFFER_SIZE % AURIX_ETH_DMA_ALIGNMENT) == 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_tx_buffer_size_aligned, (IFXGETH_MAX_TX_BUFFER_SIZE % AURIX_ETH_DMA_ALIGNMENT) == 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_rx_buffer_size_word_aligned, (IFXGETH_MAX_RX_BUFFER_SIZE % 4u) == 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_tx_buffer_size_word_aligned, (IFXGETH_MAX_TX_BUFFER_SIZE % 4u) == 0u);
LWIP_GETH_STATIC_ASSERT(lwip_geth_dma_memory_fits_window, LWIP_GETH_DMA_BYTES <= AURIX_ETH_DMA_WINDOW_BYTES);
LWIP_GETH_STATIC_ASSERT(lwip_geth_lwip_mem_alignment, (MEM_ALIGNMENT >= 4u) && ((MEM_ALIGNMENT % 4u) == 0u));
LWIP_GETH_STATIC_ASSERT(lwip_geth_lwip_eth_pad_aligns_ip_header, ETH_PAD_SIZE == 2u);

static void lwip_geth_CopyBytes(void *destination, const void *source, uint32 length)
{
  volatile uint8 *dst = (volatile uint8 *)destination;
  const volatile uint8 *src = (const volatile uint8 *)source;
  uint32 index;

  for (index = 0u; index < length; index++)
  {
    dst[index] = src[index];
  }
}

/***********************************************************************************************************************
 * PRIVATE VARIABLES
 **********************************************************************************************************************/
volatile uint32 g_TickCount_1ms;
Ifx_Lwip        g_Lwip;
IfxGeth_Eth     g_IfxGeth;
IFX_ALIGN(32) AURIX_ETH_DMA uint8 channel0TxBuffer1[IFXGETH_MAX_TX_DESCRIPTORS][IFXGETH_MAX_TX_BUFFER_SIZE];
IFX_ALIGN(32) AURIX_ETH_DMA uint8 channel0RxBuffer1[IFXGETH_MAX_RX_DESCRIPTORS][IFXGETH_MAX_RX_BUFFER_SIZE];
volatile uint32 g_LwipSoftwareTimerTickCounter;
volatile uint32 g_LwipRxPollLoopCounter;
volatile uint32 g_LwipRxPollPacketCounter;
volatile uint32 g_LwipRxPollBudgetHitCounter;
volatile uint32 g_LwipRxPollInProgress;
volatile uint32 g_LwipRxPollReentryBlockedCounter;
volatile uint32 g_LwipLastTimerTicks;
volatile uint32 g_LwipNetifAddFailed;
volatile uint32 g_LwipForcedMacConfigCounter;
volatile uint32 g_LwipNetifLinkUp;

/***********************************************************************************************************************
 * FUNCTION IMPLEMENTATIONS
 **********************************************************************************************************************/
void lwip_geth_UpdateTickCount(void);

static TIMER_STM_t *lwip_geth_Lwip_getStmHandle(void)
{
  return (lwip_geth_handle != NULL_PTR) ? lwip_geth_handle->stm_module : NULL_PTR;
}

static Ifx_STM *lwip_geth_Lwip_getStmModule(TIMER_STM_t *stmHandle)
{
  if ((stmHandle != NULL_PTR) &&
      (stmHandle->app_config != NULL_PTR) &&
      (stmHandle->app_config->stm != NULL_PTR))
  {
    return stmHandle->app_config->stm;
  }

  return &MODULE_STM0;
}

static uint32 lwip_geth_Lwip_getTimerTicksPerLwipTick(TIMER_STM_t *stmHandle)
{
  uint32 frequency = LWIP_GETH_TIMER_FALLBACK_FREQ_HZ;

  if ((stmHandle != NULL_PTR) &&
      (stmHandle->app_config != NULL_PTR) &&
      (stmHandle->app_config->frequency != 0u))
  {
    frequency = stmHandle->app_config->frequency;
  }

  return (frequency / LWIP_GETH_TIMER_HZ_PER_MS) * IFX_LWIP_TIMER_TICK_MS;
}

static void lwip_geth_Lwip_configureForcedMacMode(IfxGeth_Eth *ethernetif)
{
  if ((ethernetif == NULL_PTR) || (ethernetif->gethSFR == NULL_PTR))
  {
    return;
  }

  IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
  FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
  g_LwipForcedMacConfigCounter++;
}

static void lwip_geth_Lwip_forceNetifUp(void)
{
  netif_set_default(&g_Lwip.netif);
#if LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
  g_Lwip.netif.flags |= (NETIF_FLAG_UP | NETIF_FLAG_LINK_UP);
#else
  netif_set_up(&g_Lwip.netif);
  netif_set_link_up(&g_Lwip.netif);
#endif
}

static void lwip_geth_Lwip_applyLinkStatus(void)
{
  Ifx_GETH_MAC_PHYIF_CONTROL_STATUS ctrl_status;
  IfxGeth_Eth *ethernetif = g_Lwip.netif.state;

  if (ethernetif == NULL_PTR)
  {
    return;
  }

#if (PHY_DEVICE_NAME == PHY_DP83825I)
  lwip_geth_private_Phy_Dp83825i_mainFunction_100ms();
  ctrl_status.U = lwip_geth_private_Phy_Dp83825i_link_status();
#else
  ctrl_status.U = GETH_MAC_PHYIF_CONTROL_STATUS.U;
#endif

  g_LwipNetifLinkUp = (uint32)ctrl_status.B.LNKSTS;

  if (ctrl_status.B.LNKSTS == 0u)
  {
#if LWIP_GETH_FORCE_LINK_UP_FOR_BRINGUP
    lwip_geth_Lwip_configureForcedMacMode(ethernetif);
    lwip_geth_Lwip_forceNetifUp();
#else
    netif_set_link_down(&g_Lwip.netif);
#endif
    return;
  }

  if (ctrl_status.B.LNKMOD == 1u)
  {
    IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
  }
  else
  {
    IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
  }

  if (ctrl_status.B.LNKSPEED == 0u)
  {
    FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
  }
  else
  {
    FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
  }

  lwip_geth_Lwip_forceNetifUp();
}

/** \brief Timer interrupt callback */
void lwip_geth_Lwip_onTimerTick(void)
{
  Ifx_Lwip *lwip       = &g_Lwip;
  uint16    timerFlags = lwip->timerFlags;

  Ifx_Lwip_timerIncr(lwip->timer.arp, IFX_LWIP_ARP_PERIOD, IFX_LWIP_FLAG_ARP);

  Ifx_Lwip_timerIncr(lwip->timer.tcp_fast, IFX_LWIP_TCP_FAST_PERIOD, IFX_LWIP_FLAG_TCP_FAST);
  Ifx_Lwip_timerIncr(lwip->timer.tcp_slow, IFX_LWIP_TCP_SLOW_PERIOD, IFX_LWIP_FLAG_TCP_SLOW);

#if LWIP_DHCP
  Ifx_Lwip_timerIncr(lwip->timer.dhcp_coarse, IFX_LWIP_DHCP_COARSE_PERIOD, IFX_LWIP_FLAG_DHCP_COARSE);
  Ifx_Lwip_timerIncr(lwip->timer.dhcp_fine, IFX_LWIP_DHCP_FINE_PERIOD, IFX_LWIP_FLAG_DHCP_FINE);
#endif

  Ifx_Lwip_timerIncr(lwip->timer.link, IFX_LWIP_LINK_PERIOD, IFX_LWIP_FLAG_LINK);
#if LWIP_IPV4 && LWIP_ACD
  Ifx_Lwip_timerIncr(lwip->timer.acd, IFX_LWIP_ACD_PERIOD, IFX_LWIP_FLAG_ACD);
#endif

  lwip->timerFlags = timerFlags;
}

static void lwip_geth_Lwip_advanceElapsedTime(void)
{
  TIMER_STM_t *stmHandle = lwip_geth_Lwip_getStmHandle();
  uint32 timerTicksPerLwipTick = lwip_geth_Lwip_getTimerTicksPerLwipTick(stmHandle);
  uint32 nowTicks = IfxStm_getLower(lwip_geth_Lwip_getStmModule(stmHandle));
  uint32 elapsedTicks = nowTicks - g_LwipLastTimerTicks;
  uint32 ticks;
  uint32 tick;

  if (timerTicksPerLwipTick == 0u)
  {
    return;
  }

  ticks = elapsedTicks / timerTicksPerLwipTick;

  if (ticks == 0u)
  {
    return;
  }

  if (ticks > LWIP_GETH_TIMER_CATCHUP_LIMIT)
  {
    g_LwipLastTimerTicks = nowTicks;
    return;
  }
  else
  {
    g_LwipLastTimerTicks += ticks * timerTicksPerLwipTick;
  }

  for (tick = 0u; tick < ticks; tick++)
  {
    lwip_geth_Lwip_onTimerTick();
    lwip_geth_UpdateTickCount();
    g_LwipSoftwareTimerTickCounter++;
  }
}

/** \brief Polling the timer event flags */
void lwip_geth_Lwip_pollTimerFlags(void)
{
  Ifx_Lwip *lwip = &g_Lwip;
  uint16    timerFlags;
  boolean   interruptState;

  lwip_geth_Lwip_advanceElapsedTime();

  /* disable interrupts */
  interruptState = IfxCpu_disableInterrupts();

  timerFlags       = lwip->timerFlags;
  lwip->timerFlags = 0;

  /* enable interrupts again */
  IfxCpu_restoreInterrupts(interruptState);

#if LWIP_DHCP
  if (timerFlags & IFX_LWIP_FLAG_DHCP_COARSE)
  {
    /* only if we have a link we will check the dhcp */
    if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
    {
      dhcp_coarse_tmr();
    }
  }

  if (timerFlags & IFX_LWIP_FLAG_DHCP_FINE)
  {
    /* only if we have a link we will check the dhcp */
    if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
    {
      dhcp_fine_tmr();
    }
  }
#endif

  if (timerFlags & IFX_LWIP_FLAG_TCP_FAST)
  {
    /* only if we have a link we will check the tcp */
    if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
    {
      tcp_fasttmr();
    }
  }

  if (timerFlags & IFX_LWIP_FLAG_TCP_SLOW)
  {
    /* only if we have a link we will check the tcp */
    if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
    {
      tcp_slowtmr();
    }
  }

  if (timerFlags & IFX_LWIP_FLAG_ARP)
  {
    /* only if we have a link we will check the arp */
    if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
    {
      etharp_tmr();
    }
  }

  if (timerFlags & IFX_LWIP_FLAG_LINK)
  {
    lwip_geth_Lwip_applyLinkStatus();
  }
#if LWIP_IPV4 && LWIP_ACD
  if (timerFlags & IFX_LWIP_FLAG_ACD)
  {
    /* only if we have a link we will check the arp */
    if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
    {
      acd_tmr();
    }
  }
#endif
}

/** \brief Polling the ETH receive event flags */
void lwip_geth_Lwip_pollReceiveFlags(void)
{
  uint8 processed;
  uint8 budget = LWIP_GETH_RX_POLL_BUDGET;
  boolean interruptState;

  interruptState = IfxCpu_disableInterrupts();

  if (g_LwipRxPollInProgress != 0u)
  {
    g_LwipRxPollReentryBlockedCounter++;
    IfxCpu_restoreInterrupts(interruptState);
    return;
  }

  g_LwipRxPollInProgress = 1u;
  IfxCpu_restoreInterrupts(interruptState);

  g_LwipRxPollLoopCounter++;

  do
  {
    processed = lwip_geth_netif_input_once(&g_Lwip.netif);

    if (processed != 0u)
    {
      g_LwipRxPollPacketCounter++;
    }

    if (budget > 0u)
    {
      budget--;
    }
  } while ((processed != 0u) && (budget > 0u));

  if ((processed != 0u) && (budget == 0u))
  {
    g_LwipRxPollBudgetHitCounter++;
  }

  interruptState = IfxCpu_disableInterrupts();
  g_LwipRxPollInProgress = 0u;
  IfxCpu_restoreInterrupts(interruptState);
}

#if LWIP_GETH_RTOS_ENABLED
void lwip_geth_Lwip_WaitForInput( void )
{
  /* Just wait until we are signled from an ISR that data is available, or
   * we simply time out.
   */
  ulTaskNotifyTake(pdFALSE, IFX_LWIP_EMAC_BLOCK_TIME_FOR_INPUT);
}
#endif

#if LWIP_GETH_RTOS_ENABLED
void lwip_geth_LinkStatus(void *pvParameter)
{
  Ifx_GETH_MAC_PHYIF_CONTROL_STATUS ctrl_status;

  for (;;)
  {
    ctrl_status.U = GETH_MAC_PHYIF_CONTROL_STATUS.U;
    if (ctrl_status.B.LNKSTS == 0)
    {
      netif_set_link_up(&g_Lwip.netif);
    }
    else
    {
      IfxGeth_Eth *ethernetif = g_Lwip.netif.state;
      /* we set the correct duplexMode */
      if (ctrl_status.B.LNKMOD == 1)
      {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
      }
      else
      {
        IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
      }
      /* we set the correct speed */
      if (ctrl_status.B.LNKSPEED == 0)
      {
        /* 10MBit speed */
        FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
      }
      else
      {
        if (ctrl_status.B.LNKSPEED == 1)
        {
          /* 100MBit speed */
          FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
        }
        else
        {
          /* 1000MBit speed */
          FblRamGeth_SetLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_1000Mbps);
        }
      }
      netif_set_link_up(&g_Lwip.netif);
    }
    vTaskDelay(1000);  /* Check every second the Link (Cable Plugged or not) */
  }
}
#endif

#if LWIP_NETIF_EXT_STATUS_CALLBACK
static netif_ext_callback_t g_extCallback;

void netif_state_changed(struct netif* netif, netif_nsc_reason_t reason, const netif_ext_callback_args_t* args)
{
  if (reason | LWIP_NSC_IPV4_ADDRESS_CHANGED)
  {
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE | LWIP_DBG_STATE,
                ("netif: new ip address assigned: %"U16_F".%"U16_F".%"U16_F".%"U16_F"\n",
                 ip4_addr1_16(netif_ip4_addr(netif)),
                 ip4_addr2_16(netif_ip4_addr(netif)),
                 ip4_addr3_16(netif_ip4_addr(netif)),
                 ip4_addr4_16(netif_ip4_addr(netif))));
  }
}
#endif

/** \brief LWIP initialization function */
void lwip_geth_Lwip_init(void)
{
  ip_addr_t default_ipaddr, default_netmask, default_gw;
  TIMER_STM_t *stmHandle;

  g_LwipNetifAddFailed = 0u;
#if LWIP_DHCP
  IP4_ADDR(&default_gw, 0, 0, 0, 0);
  IP4_ADDR(&default_ipaddr, 0, 0, 0, 0);
  IP4_ADDR(&default_netmask, 0, 0, 0, 0);
#else
  IP4_ADDR(&default_gw, GW_ADDR0,GW_ADDR1, GW_ADDR2,GW_ADDR3);
  IP4_ADDR(&default_ipaddr, IP_ADDR0, IP_ADDR1, IP_ADDR2, IP_ADDR3);
  IP4_ADDR(&default_netmask, NETMASK_ADDR0, NETMASK_ADDR1, NETMASK_ADDR2, NETMASK_ADDR3);
#endif

  LWIP_DEBUGF(LWIP_GETH_DEBUG, ("Lwip_geth_lwip_init start!\n"));
  stmHandle = lwip_geth_Lwip_getStmHandle();
  g_LwipLastTimerTicks = IfxStm_getLower(lwip_geth_Lwip_getStmModule(stmHandle));

  /** - initialise LWIP (lwip_init()) */
#if !LWIP_GETH_RTOS_ENABLED
  lwip_init();
#endif
  /** - initialise and add a \ref netif */
  lwip_geth_CopyBytes(&g_Lwip.eth_addr,
                      lwip_geth_handle->app_config->geth_lld_config->mac.macAddress,
                      (uint32)sizeof(g_Lwip.eth_addr));

#if LWIP_GETH_RTOS_ENABLED
  if (netif_add(&g_Lwip.netif, &default_ipaddr, &default_netmask, &default_gw,
            (void *)0, lwip_geth_netif_init, tcpip_input) == NULL_PTR)
  {
    g_LwipNetifAddFailed = 1u;
    return;
  }
  /* Create a Task for checking the Link */
  xTaskCreate(lwip_geth_LinkStatus,"Eth Link Stat",LWIP_GETH_PHY_TASK_STACK_SIZE,NULL,LWIP_GETH_PHY_TASK_PRIO,NULL);
  /* Task is woken up by an Rx Ethernet Event using Binary Semaphore */
  xTaskCreate(lwip_geth_netif_input,"Eth RX",LWIP_GETH_TASK_STACK_SIZE,&g_Lwip.netif,LWIP_GETH_TASK_PRIO_RX,&g_Lwip.EthRxTask);
#else
  if (netif_add(&g_Lwip.netif, &default_ipaddr, &default_netmask, &default_gw,
            (void *)0, lwip_geth_netif_init, ethernet_input) == NULL_PTR)
  {
    g_LwipNetifAddFailed = 1u;
    return;
  }
#endif

#if LWIP_NETIF_STATUS_CALLBACK == 1 /* If callback enabled */
  /* Initialize interface status change callback */
  netif_set_status_callback(&g_Lwip.netif, LWIP_GETH_NETIF_STATUS_CB_FUNCTION);
#endif
  lwip_geth_Lwip_forceNetifUp();
  lwip_geth_Lwip_applyLinkStatus();

#if LWIP_NETIF_HOSTNAME
  g_Lwip.netif.hostname = lwip_geth_handle->app_config->hostname;
#endif

#if LWIP_DHCP
  /** - assign \ref dhcp to \ref netif */
  dhcp_set_struct(&g_Lwip.netif, &g_Lwip.dhcp);

  /* we start the dhcp always here also when we don't have a link here */
  dhcp_start(&g_Lwip.netif);
#endif

#if LWIP_NETIF_EXT_STATUS_CALLBACK
  netif_add_ext_callback(&g_extCallback, netif_state_changed);
#endif
  LWIP_DEBUGF(LWIP_GETH_DEBUG, ("Lwip_geth_lwip_init end!\n"));
}

/** Returns the current time in milliseconds, may be the same as sys_jiffies or at least based on it. */
#if !LWIP_GETH_RTOS_ENABLED
inline u32_t sys_now(void)
{
  return g_TickCount_1ms;
}
#endif

/** Increase the system time in milliseconds. */
void lwip_geth_UpdateTickCount(void)
{
  g_TickCount_1ms++;
}

/* CODE_BLOCK_END */
