/**********************************************************************************************************************
 * \file SafetyKit_InternalWatchdogs.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SafetyKit_InternalWatchdogs.h"
#include "SafetyKit_Main.h"
#include "SafetyKit_Cfg.h"
#include "BSW/Sys/Wdg/Wdg_Cfg.h"
#include "IfxScuWdt.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_mutexLock safetyWatchdogLock;
volatile uint32 SafetyKit_CpuWdtInitCount[3u];
volatile uint32 SafetyKit_CpuWdtServiceCount[3u];
volatile uint32 SafetyKit_CpuWdtInitCon0[3u];
volatile uint32 SafetyKit_CpuWdtInitCon1[3u];
volatile uint32 SafetyKit_CpuWdtLastServiceCon0[3u];
volatile uint32 SafetyKit_CpuWdtLastServiceCon1[3u];
volatile uint32 SafetyKit_CpuWdtLastServiceCore;
volatile uint32 SafetyKit_SafetyWdtInitCon0;
volatile uint32 SafetyKit_SafetyWdtInitCon1;
volatile uint32 SafetyKit_SafetyWdtServiceCount;
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/*
 * function initial safety watch dog
 * */
void initSafetyWatchdog(void)
{
    IfxScuWdt_Config cfgSafetyWatchdog;
    Ifx_SCU_WDTS *safetyWatchdog;

    safetyWatchdog = &MODULE_SCU.WDTS;

    IfxScuWdt_initConfig(&cfgSafetyWatchdog);

    cfgSafetyWatchdog.inputFrequency = WDG_INPUT_FREQUENCY;
    cfgSafetyWatchdog.globalEndInitInputFrequency = WDG_INPUT_FREQUENCY;
    cfgSafetyWatchdog.reload = WDG_RELOAD_VALUE;

    IfxScuWdt_initSafetyWatchdog(safetyWatchdog, &cfgSafetyWatchdog);
    SafetyKit_SafetyWdtInitCon0 = safetyWatchdog->CON0.U;
    SafetyKit_SafetyWdtInitCon1 = safetyWatchdog->CON1.U;

}
/*
 * run safety watch dog
 * */
void serviceSafetyWatchdog(void)
{
    /* Only service Safety Watchdog if ENDINIT is set, otherwise ENDINIT is currently cleared and in
     * use somewhere else */
    if((IfxCpu_getCoreIndex() == IfxCpu_ResourceCpu_0) &&
            (IfxScuWdt_getSafetyWatchdogEndInit()))
    {
        SafetyKit_SafetyWdtServiceCount++;
        IfxScuWdt_setSafetyEndinitInline(IfxScuWdt_getSafetyWatchdogPasswordInline());
    }
    else
    {
        /* Do nothing. */
    }
}

/*
 * This function is initializing the CPU watchdog. It can be called by every CPU to initialize
 * its respective watchdog
 * */
void initCpuWatchdog(uint8 cpuIndex)
{
    IfxScuWdt_Config cpuXwdgCfg;
    Ifx_SCU_WDTCPU *ptrCpuXwatchdog = (Ifx_SCU_WDTCPU *)0;

    switch (cpuIndex)
    {
        case IfxCpu_ResourceCpu_0:
            ptrCpuXwatchdog = &MODULE_SCU.WDTCPU[0];
            break;
#if (IFXCPU_NUM_MODULES > 1)
        case IfxCpu_ResourceCpu_1:
            ptrCpuXwatchdog = &MODULE_SCU.WDTCPU[1];
            break;
#endif
#if (IFXCPU_NUM_MODULES > 2)
        case IfxCpu_ResourceCpu_2:
            ptrCpuXwatchdog = &MODULE_SCU.WDTCPU[2];
            break;
#endif
        default:
            break;
    }

    if (ptrCpuXwatchdog == (Ifx_SCU_WDTCPU *)0)
    {
        return;
    }

    IfxScuWdt_initConfig(&cpuXwdgCfg);

    cpuXwdgCfg.inputFrequency = WDG_INPUT_FREQUENCY;
    cpuXwdgCfg.globalEndInitInputFrequency = WDG_INPUT_FREQUENCY;
    cpuXwdgCfg.reload = WDG_RELOAD_VALUE;
    cpuXwdgCfg.disableWatchdog = FALSE;

    IfxScuWdt_initCpuWatchdog(ptrCpuXwatchdog, &cpuXwdgCfg);
    if (cpuIndex < 3u)
    {
        SafetyKit_CpuWdtInitCount[cpuIndex]++;
        SafetyKit_CpuWdtInitCon0[cpuIndex] = ptrCpuXwatchdog->CON0.U;
        SafetyKit_CpuWdtInitCon1[cpuIndex] = ptrCpuXwatchdog->CON1.U;
    }
    else
    {
        /* Do nothing. */
    }
}

/*
 * service the CPU watch dog
 * */
void serviceCpuWatchdog(void)
{
    uint8 coreIndex = IfxCpu_getCoreIndex();
    /* Only service Safety Watchdog if ENDINIT is set, otherwise ENDINIT is currently cleared and in used somewhere else */
    if(IfxScuWdt_getCpuWatchdogEndInitInline(&MODULE_SCU.WDTCPU[coreIndex]))
    {
        uint16 password = IfxScuWdt_getCpuWatchdogPasswordInline(&MODULE_SCU.WDTCPU[coreIndex]);

        SafetyKit_CpuWdtLastServiceCore = coreIndex;
        if (coreIndex < 3u)
        {
            SafetyKit_CpuWdtServiceCount[coreIndex]++;
        }
        else
        {
            /* Do nothing. */
        }
        IfxScuWdt_setCpuEndinitInline(&MODULE_SCU.WDTCPU[coreIndex], password);
        if (coreIndex < 3u)
        {
            SafetyKit_CpuWdtLastServiceCon0[coreIndex] = MODULE_SCU.WDTCPU[coreIndex].CON0.U;
            SafetyKit_CpuWdtLastServiceCon1[coreIndex] = MODULE_SCU.WDTCPU[coreIndex].CON1.U;
        }
        else
        {
            /* Do nothing. */
        }
    }
    else
    {
        /* Do nothing. */
    }
}
