/**********************************************************************************************************************
 * \file SafetyKit_VoltMon.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SafetyKit_VoltMon.h"
#include "SafetyKit_Main.h"
#include "SafetyKit_Cfg.h"
#include "IfxPmsEvr.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PMS_MILLIVOLT_TO_VOLT(value) ((float32)((value) / 1000.0f))
#define PMS_TC007_MONSTAT1_REFRESH_WAIT_LIMIT 1000000u
#define PMS_TC007_MONSTAT1_SETTLE_SAMPLES     4u

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void safetyKitPmsErrataCaptureRegisters(void);
static void safetyKitPmsErrataUpdateStatus(uint32 failureMask);
static Ifx_PMS_MONSTAT1 safetyKitPmsErrataReadFreshMonStat1(void);
static Ifx_PMS_MONSTAT1 safetyKitPmsErrataReadSettledMonStat1(void);
static void safetyKitVerifyPmsTcH003Thresholds(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static void safetyKitPmsErrataCaptureRegisters(void)
{
    g_SafetyKitStatus.voltStatus.pmsErrataEvrStat = PMS_EVRSTAT.U;
    g_SafetyKitStatus.voltStatus.pmsErrataEvrAdcStat = PMS_EVRADCSTAT.U;
    g_SafetyKitStatus.voltStatus.pmsErrataEvrMonStat1 = PMS_EVRMONSTAT1.U;
    g_SafetyKitStatus.voltStatus.pmsErrataEvrRstCon = PMS_EVRRSTCON.U;
    g_SafetyKitStatus.voltStatus.pmsErrataEvrOvMon2 = PMS_EVROVMON2.U;
    g_SafetyKitStatus.voltStatus.pmsErrataEvrUvMon2 = PMS_EVRUVMON2.U;
}

static void safetyKitPmsErrataUpdateStatus(uint32 failureMask)
{
    g_SafetyKitStatus.voltStatus.pmsErrataFailureMask |= failureMask;
    g_SafetyKitStatus.voltStatus.pmsErrataCheckStatus =
            (g_SafetyKitStatus.voltStatus.pmsErrataFailureMask == 0u) ?
                    SAFETYKIT_PMS_ERRATA_STATUS_PASSED :
                    SAFETYKIT_PMS_ERRATA_STATUS_FAILED;
    safetyKitPmsErrataCaptureRegisters();
}

static Ifx_PMS_MONSTAT1 safetyKitPmsErrataReadFreshMonStat1(void)
{
    uint32 waitCount = PMS_TC007_MONSTAT1_REFRESH_WAIT_LIMIT;
    Ifx_PMS_MONSTAT1 initialMonStat1;
    Ifx_PMS_MONSTAT1 currentMonStat1;

    initialMonStat1.U = PMS_EVRMONSTAT1.U;
    currentMonStat1.U = initialMonStat1.U;

    while (waitCount > 0u)
    {
        currentMonStat1.U = PMS_EVRMONSTAT1.U;
        if (currentMonStat1.B.ACTVCNT != initialMonStat1.B.ACTVCNT)
        {
            break;
        }
        serviceCpuWatchdog();
        serviceSafetyWatchdog();
        waitCount--;
    }

    if (waitCount == 0u)
    {
        g_SafetyKitStatus.voltStatus.pmsErrataTc007RefreshTimeoutCount++;
    }
    else
    {
        /* Do nothing. */
    }

    return currentMonStat1;
}

static Ifx_PMS_MONSTAT1 safetyKitPmsErrataReadSettledMonStat1(void)
{
    uint32 sample;
    Ifx_PMS_MONSTAT1 currentMonStat1;

    currentMonStat1.U = PMS_EVRMONSTAT1.U;

    for(sample = 0u; sample < PMS_TC007_MONSTAT1_SETTLE_SAMPLES; sample++)
    {
        currentMonStat1 = safetyKitPmsErrataReadFreshMonStat1();
        g_SafetyKitStatus.voltStatus.pmsErrataTc007SampleCount++;
    }

    return currentMonStat1;
}

void initPmsErrataWorkarounds(void)
{
    uint16 passwd;
    uint32 failureMask = 0u;
    uint32 standbyWakeIgnoredMask = 0u;
    Ifx_PMS_EVRRSTCON evrRstCon;
    Ifx_PMS_EVRSTAT checkedEvrStat;
    Ifx_PMS_MONSTAT1 checkedMonStat1;
    float32 vddp3Secondary;
    float32 vddSecondary;
    boolean tc007SamplesFresh;
    boolean tc007Vddp3Ov;
    boolean tc007VddOv;

    g_SafetyKitStatus.voltStatus.pmsErrataFailureMask = 0u;
    g_SafetyKitStatus.voltStatus.pmsErrataStandbyWakeIgnoredMask = 0u;
    g_SafetyKitStatus.voltStatus.pmsErrataTc007SampleCount = 0u;
    g_SafetyKitStatus.voltStatus.pmsErrataTc007RefreshTimeoutCount = 0u;
    g_SafetyKitStatus.voltStatus.pmsErrataCheckStatus = SAFETYKIT_PMS_ERRATA_STATUS_NOT_EVALUATED;
    checkedMonStat1 = safetyKitPmsErrataReadSettledMonStat1();
    vddp3Secondary = IfxPmsEvr_getAdcVddp3Result((float32)checkedMonStat1.B.ADC33V);
    vddSecondary = IfxPmsEvr_getAdcVddResult((float32)checkedMonStat1.B.ADCCV);
    tc007SamplesFresh =
            (g_SafetyKitStatus.voltStatus.pmsErrataTc007RefreshTimeoutCount == 0u) ? TRUE : FALSE;
    checkedEvrStat.U = PMS_EVRSTAT.U;
    g_SafetyKitStatus.voltStatus.pmsErrataCheckedEvrStat = checkedEvrStat.U;
    g_SafetyKitStatus.voltStatus.pmsErrataCheckedEvrMonStat1 = checkedMonStat1.U;
    safetyKitPmsErrataCaptureRegisters();

    /* PMS_TC.007: PBIST may miss VDDP3/VDD overvoltage before SMU alarm enable. */
    tc007Vddp3Ov = (((tc007SamplesFresh != FALSE) &&
            (vddp3Secondary >= PMS_MILLIVOLT_TO_VOLT(EVR33_OV_VAL_MILLIVOLT))) ||
            (checkedEvrStat.B.OV33 != 0u)) ? TRUE : FALSE;
    tc007VddOv = (((tc007SamplesFresh != FALSE) &&
            (vddSecondary >= PMS_MILLIVOLT_TO_VOLT(EVRC_OV_VAL_MILLIVOLT))) ||
            (checkedEvrStat.B.OVC != 0u)) ? TRUE : FALSE;

    if ((tc007Vddp3Ov != FALSE) && (g_SafetyKitStatus.wakeupFromStandby == FALSE))
    {
        failureMask |= SAFETYKIT_PMS_ERRATA_FAIL_TC007_VDDP3_OV;
    }
    else if (tc007Vddp3Ov != FALSE)
    {
        standbyWakeIgnoredMask |= SAFETYKIT_PMS_ERRATA_FAIL_TC007_VDDP3_OV;
    }
    else
    {
        /* Do nothing. */
    }

    if ((tc007VddOv != FALSE) && (g_SafetyKitStatus.wakeupFromStandby == FALSE))
    {
        failureMask |= SAFETYKIT_PMS_ERRATA_FAIL_TC007_VDD_OV;
    }
    else if (tc007VddOv != FALSE)
    {
        standbyWakeIgnoredMask |= SAFETYKIT_PMS_ERRATA_FAIL_TC007_VDD_OV;
    }
    else
    {
        /* Do nothing. */
    }

    g_SafetyKitStatus.voltStatus.pmsErrataStandbyWakeIgnoredMask = standbyWakeIgnoredMask;

    if ((tc007SamplesFresh == FALSE) && (g_SafetyKitStatus.wakeupFromStandby == FALSE))
    {
        failureMask |= SAFETYKIT_PMS_ERRATA_FAIL_TC007_MONSTAT1_STALE;
    }
    else
    {
        /* Do nothing. */
    }

    /* PMS_TC.013: TC375TI with fSRI > 200 MHz requires VDD reset trim 0x58. */
    passwd = IfxScuWdt_getSafetyWatchdogPassword();
    IfxScuWdt_clearSafetyEndinit(passwd);
    evrRstCon.U = PMS_EVRRSTCON.U;
    evrRstCon.B.RSTCTRIM = PMS_TC013_RSTCTRIM_RECOMMENDED;
    PMS_EVRRSTCON.U = evrRstCon.U;
    IfxScuWdt_setSafetyEndinit(passwd);

    if (PMS_EVRRSTCON.B.RSTCTRIM != PMS_TC013_RSTCTRIM_RECOMMENDED)
    {
        failureMask |= SAFETYKIT_PMS_ERRATA_FAIL_TC013_RSTCTRIM;
    }
    else
    {
        /* Do nothing. */
    }

    safetyKitPmsErrataUpdateStatus(failureMask);
}

static void safetyKitVerifyPmsTcH003Thresholds(void)
{
    uint32 failureMask = 0u;

    if (PMS_EVROVMON2.B.PREOVVAL != PMS_TCH003_PREOVVAL_RECOMMENDED)
    {
        failureMask |= SAFETYKIT_PMS_ERRATA_FAIL_TCH003_PREOVVAL;
    }
    else
    {
        /* Do nothing. */
    }

    if (PMS_EVRUVMON2.B.PREUVVAL != PMS_TCH003_PREUVVAL_RECOMMENDED)
    {
        failureMask |= SAFETYKIT_PMS_ERRATA_FAIL_TCH003_PREUVVAL;
    }
    else
    {
        /* Do nothing. */
    }

    safetyKitPmsErrataUpdateStatus(failureMask);
}

/*
 * SM:PMS:VX_MONITOR_CFG and SM:PMS:MON_REDUNDANCY_CFG
 * */
void initVoltageMonitors(void)
{
    /* SM:PMS:VX_MONITOR_CFG */
    /* Set all Threshold parameters for each Vx_MONITOR in EVROVMON, EVROVMON2, EVRUVMON, EVRUVMON2 registers */
    IfxPmsEvr_setSecondaryOverVoltageThresholdMv(&MODULE_PMS, SWD_OV_VAL_MILLIVOLT,     IfxPmsEvr_SupplyMode_swd);
    IfxPmsEvr_setSecondaryUnderVoltageThresholdMv(&MODULE_PMS, SWD_UV_VAL_MILLIVOLT,     IfxPmsEvr_SupplyMode_swd);
    IfxPmsEvr_setSecondaryOverVoltageThresholdMv(&MODULE_PMS, EVR33_OV_VAL_MILLIVOLT,   IfxPmsEvr_SupplyMode_evr33);
    IfxPmsEvr_setSecondaryUnderVoltageThresholdMv(&MODULE_PMS, EVR33_UV_VAL_MILLIVOLT,   IfxPmsEvr_SupplyMode_evr33);
    IfxPmsEvr_setSecondaryOverVoltageThresholdMv(&MODULE_PMS, EVRC_OV_VAL_MILLIVOLT,    IfxPmsEvr_SupplyMode_evrc);
    IfxPmsEvr_setSecondaryUnderVoltageThresholdMv(&MODULE_PMS, EVRC_UV_VAL_MILLIVOLT,    IfxPmsEvr_SupplyMode_evrc);
    IfxPmsEvr_setSecondaryOverVoltageThresholdMv(&MODULE_PMS, SB_OV_VAL_MILLIVOLT,      IfxPmsEvr_SupplyMode_sb);
    IfxPmsEvr_setSecondaryUnderVoltageThresholdMv(&MODULE_PMS, SB_UV_VAL_MILLIVOLT,      IfxPmsEvr_SupplyMode_sb);
    IfxPmsEvr_setSecondaryOverVoltageThresholdMv(&MODULE_PMS, VDDM_OV_VAL_MILLIVOLT,    IfxPmsEvr_SupplyMode_vddm);
    IfxPmsEvr_setSecondaryUnderVoltageThresholdMv(&MODULE_PMS, VDDM_UV_VAL_MILLIVOLT,    IfxPmsEvr_SupplyMode_vddm);
    IfxPmsEvr_setSecondaryOverVoltageThresholdMv(&MODULE_PMS, PRE_OV_VAL_MILLIVOLT,     IfxPmsEvr_SupplyMode_evrpr);
    IfxPmsEvr_setSecondaryUnderVoltageThresholdMv(&MODULE_PMS, PRE_UV_VAL_MILLIVOLT,     IfxPmsEvr_SupplyMode_evrpr);
    /* Save the configured undervoltage limits of register EVRUVMON to a global struct to enable modification via TFT */
    g_SafetyKitStatus.voltStatus.vextVoltageUvLimit     = SWD_UV_VAL_MILLIVOLT  /1000;
    g_SafetyKitStatus.voltStatus.vddp3VoltageUvLimit    = EVR33_UV_VAL_MILLIVOLT / 1000;
    g_SafetyKitStatus.voltStatus.coreVoltageUvLimit     = EVRC_UV_VAL_MILLIVOLT /1000;
    /* Enable over- and undervoltage monitoring and direction of voltage crossing in the EVRMONCTRL register*/
    IfxPmsEvr_setOverVoltageMonitoringMode(&MODULE_PMS, IfxPmsEvr_OverVoltageMonitoring_lowToHighVoltageTransition,
            IfxPmsEvr_SupplyMode_swd);
    IfxPmsEvr_setUnderVoltageMonitoringMode(&MODULE_PMS, IfxPmsEvr_UnderVoltageMonitoring_highToLowVoltageTransition,
            IfxPmsEvr_SupplyMode_swd);
    IfxPmsEvr_setOverVoltageMonitoringMode(&MODULE_PMS, IfxPmsEvr_OverVoltageMonitoring_lowToHighVoltageTransition,
            IfxPmsEvr_SupplyMode_evr33);
    IfxPmsEvr_setUnderVoltageMonitoringMode(&MODULE_PMS, IfxPmsEvr_UnderVoltageMonitoring_highToLowVoltageTransition,
            IfxPmsEvr_SupplyMode_evr33);
    IfxPmsEvr_setOverVoltageMonitoringMode(&MODULE_PMS, IfxPmsEvr_OverVoltageMonitoring_lowToHighVoltageTransition,
            IfxPmsEvr_SupplyMode_evrc);
    IfxPmsEvr_setUnderVoltageMonitoringMode(&MODULE_PMS, IfxPmsEvr_UnderVoltageMonitoring_highToLowVoltageTransition,
            IfxPmsEvr_SupplyMode_evrc);
    /* SM:PMS:MON_REDUNDANCY_CFG */
    IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());
    /* Configure threshold parameters for each Vx_MONITOR (Primary voltage monitors) in HSMOVMON, HSMUVMON registers */
    /* +20mV just to have a different limit as EVROV*/
    PMS_HSMOVMON.B.SWDOVVAL = (uint8) (((SWD_OV_VAL_MILLIVOLT + 20) - 1050)  / 20);
    /* -20mV just to have a different limit as EVRUV*/
    PMS_HSMUVMON.B.SWDUVVAL = (uint8) (((SWD_UV_VAL_MILLIVOLT - 20) - 1050)  / 20);
    /* +20mV just to have a different limit as EVROV*/
    PMS_HSMOVMON.B.EVR33OVVAL = (uint8) (((EVR33_OV_VAL_MILLIVOLT + 20) - 937.5) / 15);
    /* -20mV just to have a different limit as EVRUV*/
    PMS_HSMUVMON.B.EVR33UVVAL = (uint8) (((EVR33_UV_VAL_MILLIVOLT - 20) - 937.5) / 15);
    /* +20mV just to have a different limit as EVROV*/
    PMS_HSMOVMON.B.EVRCOVVAL = (uint8) (((EVRC_OV_VAL_MILLIVOLT + 20) - 712.5) / 5);
    /* -20mV just to have a different limit as EVRUV*/
    PMS_HSMUVMON.B.EVRCUVVAL = (uint8) (((EVRC_UV_VAL_MILLIVOLT - 20) - 712.5) / 5);
    IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());
    safetyKitVerifyPmsTcH003Thresholds();
    /* Initialize Lowest and Highest variables for runtime minimum maximum runtime tracking */
    g_SafetyKitStatus.voltStatus.vextVoltageLowest      = 6.0f;
    g_SafetyKitStatus.voltStatus.vextVoltageHighest     = 0.0f;
    g_SafetyKitStatus.voltStatus.vddp3VoltageLowest     = 6.0f;
    g_SafetyKitStatus.voltStatus.vddp3VoltageHighest    = 0.0f;
    g_SafetyKitStatus.voltStatus.coreVoltageLowest      = 6.0f;
    g_SafetyKitStatus.voltStatus.coreVoltageHighest     = 0.0f;
}
/*
 * Function gets the PMS voltage measurement
 * */
void getPmsVoltageMeasurements(void)
{
    /* We get the voltage result of the primary monitor */
    float32 vext = IfxPmsEvr_getAdcVextResult((float32)PMS_EVRADCSTAT.B.ADCSWDV);
    /* If new result is higher or lower then the actual Highest and Lowest variables
     * overwrite Highest and Lowest variables. */
    if(vext > g_SafetyKitStatus.voltStatus.vextVoltageHighest)
    {
        g_SafetyKitStatus.voltStatus.vextVoltageHighest = vext;
    }
    else
    {
        /* Do nothing. */
    }

    if(vext < g_SafetyKitStatus.voltStatus.vextVoltageLowest)
    {
        g_SafetyKitStatus.voltStatus.vextVoltageLowest = vext;
    }
    else
    {
        /* Do nothing. */
    }

    g_SafetyKitStatus.voltStatus.vextVoltage = vext;
    /* We get the voltage result of the primary monitor */
    float32 vddp3 = IfxPmsEvr_getAdcVddp3Result((float32)PMS_EVRADCSTAT.B.ADC33V);
    /* If new result is higher or lower then the actual Highest and Lowest variables
     * overwrite Highest and Lowest variables. */
    if(vddp3 > g_SafetyKitStatus.voltStatus.vddp3VoltageHighest)
    {
        g_SafetyKitStatus.voltStatus.vddp3VoltageHighest = vddp3;
    }
    else
    {
        /* Do nothing. */
    }

    if(vddp3 < g_SafetyKitStatus.voltStatus.vddp3VoltageLowest)
    {
        g_SafetyKitStatus.voltStatus.vddp3VoltageLowest = vddp3;
    }
    else
    {
        /* Do nothing. */
    }

    g_SafetyKitStatus.voltStatus.vddp3Voltage = vddp3;
    /* We get the voltage result of the primary monitor */
    float32 coreVoltage = IfxPmsEvr_getAdcVddResult((float32)PMS_EVRADCSTAT.B.ADCCV);
    /* If new result is higher or lower then the actual Highest and Lowest variables
     * overwrite Highest and Lowest variables. */
    if(coreVoltage > g_SafetyKitStatus.voltStatus.coreVoltageHighest)
    {
        g_SafetyKitStatus.voltStatus.coreVoltageHighest = coreVoltage;
    }
    else
    {
        /* Do nothing. */
    }

    if(coreVoltage < g_SafetyKitStatus.voltStatus.coreVoltageLowest)
    {
        g_SafetyKitStatus.voltStatus.coreVoltageLowest  = coreVoltage;
    }
    else
    {
        /* Do nothing. */
    }

    g_SafetyKitStatus.voltStatus.coreVoltage = coreVoltage;
}
